### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by kaloyan-raev** [felixfbecker/php-language-server#1]
Please, add an explicit LICENSE file to the repo that states the license of this project.

I see composer.json has a `"license": "ISC"` declaration, but please confirm it in a LICENSE file too.

**Comment by felixfbecker** [comment]
Added. Out of interest, are you planning to use this in some way or to contribute?

**Comment by kaloyan-raev** [comment]
Thank you!

I am currently experimenting with adding PHP support in Eclipse Che. Che is integrating the language server protocol - still a work in progress. So, I am looking at the available PHP language servers and try to make them working with Che.

So far, I played with the https://github.com/HvyIndustries/crane

My next step is to look at your project. I believe that having a PHP language server implemented in PHP is the most sustainable solution for the long term. It has the highest potential for attracting the PHP community for contributing. And it can take advantage of the plenty of PHP tools that are already available.

It's great you have already done the heavy lifting of implementing the server-side of the low-level protocol.

**Comment by felixfbecker** [comment]
Enabling other IDEs to use this is the exact reason why I did the server as a separate package on Packagist, and not inside the vscode extension.

I also looked at crane-php, but it is implementing its own PHP Parser in TypeScript, even though there is already a very great PHP Parser out there that is well-tested.

Currently I only implemented all the classes for the requests and the parsing/method dispatching in the advanced-json-rpc package. The initialize request is already handled called correctly. From here, I want to implement one request after another, and I would love contributions. I would be open to adding you as a maintainer.

**Comment by kaloyan-raev** [comment]
Good progress so far. Perhaps, one thing we will try looking at in the next days is adding code validation using the same PHP parser.

**Comment by felixfbecker** [comment]
That should be relatively simple: https://github.com/felixfbecker/php-language-server/blob/master/src/TextDocumentManager.php#L80-L83

I wanted to first implement documentSymbols, because I figured it would be the most simple if you have an AST. The biggest challenge will be provideCompletion of course (I definitely do not want to restrict it to the open file like crane, but follow autoloading standards).

**Comment by felixfbecker** [comment]
Also, I pursue full test coverage (afaik crane doesn't have any tests)
