### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#12]
I don't know what is the best linter for PHP and how to configure it?
Needs to be integrated in CI

**Comment by MadHed** [comment]
I've been using https://github.com/squizlabs/PHP_CodeSniffer at work.
It's extendable with custom validation rules and already contains rules for PSR-2.
It's available as a composer package and actively maintained.

Overall very nice, haven't integrated it with a CI solution, howver.

**Comment by kaloyan-raev** [comment]
How about using the [PHP Mess Detector](https://phpmd.org) for additional static code analysis?

**Comment by felixfbecker** [comment]
What I desire is a linter, that can be configured through a config file and defaults to some coding best practices, that can be installed with Composer, run in CI and has an editor plugin for VS Code

**Comment by kaloyan-raev** [comment]
As far as I am familiar there is no one tool to rule them all. http://phpqatools.org/ is a nice collection of popular tools that are used in CI. Some of them like Code Sniffer and Mess Detector are also often integrated in the editor/IDE.

I can imagine that the language server look for the specific configuration files in the project and if found, activate the corresponding linting tool. For example, if there is a `phpcs.xml` file then the language server will activate use Code Sniffer to report additional diagnostics. Of course, the client should be able to override this default behavior.

**Comment by felixfbecker** [comment]
@kaloyan-raev This issue is not for adding linting to the LS, it is for linting this repository (for PRs etc) 😄

**Comment by kaloyan-raev** [comment]
OK :)

**Comment by ADmad** [comment]
> ..and has an editor plugin for VS Code

This phpcs plugin works just fine https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs
