### ISSUE TITLE
Parsing of dependencies

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#121]
Currently the biggest part while indexing is indexing the dependencies. For example, this project has 78 files + 1560 files in dependencies. I was thinking about whether we can skip re-parsing of dependencies by inspecting composer.lock. For example, we could make a separate cache for each dependency and copy the composer.lock to the cache folder, then only reparse if the installed version changed. This would drastically reduce the index time and CPU usage.

**Comment by yarcowang** [comment]
Yes, I think so. Or maybe you can keep a copy of `composer.lock` and only re-parsing those changed dependencies packages.

**Comment by diffen** [comment]
Is there any way to exclude certain files from LSP permanently? I found this issue via the CPU overloading issue on VSCode. It seems that the caching extension has been implemented but there is no .phpls folder anywhere on my Mac. So the files don't seem to be cached and the language server parsing seems to go on forever. In fact, I think it's an endless loop and the parsing never ends.

**Comment by felixfbecker** [comment]
This issue is outdated. Please open a new issue and check your logs
