### ISSUE TITLE
Changing document formating

### ISSUE THREAD

**Issue by soderlind** [felixfbecker/php-language-server#124]
Where do I add new rules for my `phpcs.xml`. I'm doing WordPress development and I'd like to use  https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

**Comment by mniewrzal** [comment]
Configuration `phpcs.xml` file should be in your project root directory. Description how configure such file you can found here https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml

**Comment by soderlind** [comment]
Thank you, and I can use the phpcs with rules I already have  ? or do I have to tie it in with the php language server.

I'm using atom with it's linters, including the phpcs linter, but are moving to vscode.

**Comment by felixfbecker** [comment]
It should work just fine with all your rules.
