### ISSUE TITLE
Nothing is working

### ISSUE THREAD

**Issue by andreshg112** [felixfbecker/php-language-server#126]
None of your extension functions are working.
It can be seen that:
- There's no any symbol shown,
- My installed extensions related to PHP (It could be a reason of why It's not working).

I tested previous versions of this extensions and they worked, but not this.

![php intellisense](https://cloud.githubusercontent.com/assets/15859884/19826756/16fd9e28-9d59-11e6-8190-235c98a3ebcf.png)

VS Code:
Versión 1.6.1
Confirmación 9e4e44c19e393803e2b05fe2323cf4ed7e36880e
Fecha 2016-10-13T15:43:46.054Z
Shell 1.3.7
Representador 52.0.2743.82
Node 6.5.0

Ubuntu 16.04 LTS

**Comment by felixfbecker** [comment]
Go to Help > Toggle developer tools and see if there is any stack trace

**Comment by felixfbecker** [comment]
Closing for lack of response
