### ISSUE TITLE
Parse USE statements in function definitions

### ISSUE THREAD

**Issue by vakata** [felixfbecker/php-language-server#127]
First of all - thank you for this great piece of code.

In the following example (just meaningless code) using VS code I get a nice peek of the `getInstance` definition, but not of the `debug` definition:
```
$log = new Logger();
(new Router())->middleware(function ($req, $next) use ($log) {
    $di = new DI();
    $di->getInstance(SomeClass::class);
    $log->debug("Got class");
    return $next();
})
```

Is it possible to hint for the variables imported using `use`?

**Comment by felixfbecker** [comment]
See #54

**Comment by vakata** [comment]
Thank you for the fast reply. I created the issue exactly because I saw that `use` statements should work (as described in the same issue). I must have misunderstood - I guess you mean the imported vars are resolved to the actual `use` statement, and not recursively. 
I will follow the other issue - thank you.

**Comment by felixfbecker** [comment]
Yeah, the definition should be resolved to the `use` statement - this allows you to find all references for the `use` and if there is none, you know you can remove it.

**Comment by felixfbecker** [comment]
I agree though that for method definitions, this is counter-intuitive. #54 will solve this by adding a concept of "types", so we have the type of the `use`.
