### ISSUE TITLE
Cannot open file path in warning with spaces in path

### ISSUE THREAD

**Issue by tungvn** [felixfbecker/php-language-server#130]
OS: Window 10
VS Code: 1.6.1

When I click some warnings, vscode return an error "Unable to open 'common.php': File not found (e:\path\to\common\file\common.php)."

Like this
![error](https://cloud.githubusercontent.com/assets/7405101/19843454/2ae3d530-9f55-11e6-8ea1-7bef9ecf920a.JPG)

**Comment by tungvn** [comment]
Bug happens when path of file contains space, like `e:\Project\My Project\path\to\file` is converted to `e:\Project\My+Project\path\to\file`

**Comment by felixfbecker** [comment]
That is a helpful insight, will fix!

**Comment by felixfbecker** [comment]
Turns out this is actually a problem on the VS Code side, will move the issue

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/vscode-php-intellisense#27

**Comment by felixfbecker** [comment]
This issue was moved to Microsoft/vscode#15063

**Comment by felixfbecker** [comment]
Response from VS Code was that `+` is not supported in URIs, reopening
