### ISSUE TITLE
Short tags <? not supported

### ISSUE THREAD

**Issue by z-ax** [felixfbecker/php-language-server#131]
Hi. Almost nothing of described features don't work on my project. If something's wrong on my side, would be great to check. Here's an example:

**composer.json**:
```json
{
    "name": "...",
    "config": {
        "vendor-dir": "vendor"
    },
    "require": {
        "ext-mbstring": "*",
        "php": ">=5.6",
        "facebook/graph-sdk": "~5.3",
        "...": "..."
    },
    "autoload": {
        "classmap": [
            "core",
            "module"
        ],
        "psr-4": {
            "Aaa\\": [
                "core/",
                "module/"
            ]
        }
    }
}
```

**core/Aaa.php**:
```php
<?
namespace Aaa;

class Aaa {
	const foo = 'bar';

	public static function init($a = '')
	{ /* ... */ }
}
```

**core/Bbb.php**:
```php
<?
namespace Aaa;

use \Facebook\Facebook;

class Bbb {
	const bar = 'baz';

	public $locale = 'en';
	public $bbb = 'en';

	public static function bbb($b = '')
	{ /* ... */ }

	public function __construct($locale = 'en', $b = false)
	{
		$this->locale = $locale;
		$this->bbb = Aaa::foo;

		$fb = new Facebook();
	}
}
```

Actually, same structure without namespaces also didn't work for me.
No auto-complete, nor go to definition or references (empty popup).

For class like `Bbb` I can't get the `self::baz`, can't go to `Aaa::foo` or even `$this->bbb`.
Can't do that for `Facebook`.

PhpStorm works like a charm with this same project, just for example. But I'd love to have only VSCode on other machine, without Java etc, so decided to check the extension. Hope it actually works and there's something I missed.

I have macOS (Sierra), PHP 7 (via brew, specified in IDE - otherwise got error because OS has 5.x).

**Comment by felixfbecker** [comment]
It is because of the short tags. Using `<?php` works correctly. I don't know why though, and I don't see it as a high priority - so feel free to do a PR if you feel strongly about this

**Comment by z-ax** [comment]
Yes, by default installed (via brew) PHP 7 has `short_open_tag` off. At least should probably specify this in docs here.
But maybe `ini_set()` could be used to enable it by default here (or on demand via config flag)?

**Comment by z-ax** [comment]
After enabling `short_open_tag` in local machine's `php.ini` seems like it works at least. A lot of extra stuff in auto-complete (e.g. for `self::`), but Go to Definition works. Find all References is empty still for anything I tried.

<img width="319" alt="screen shot 2016-11-02 at 12 27 59" src="https://cloud.githubusercontent.com/assets/1391015/19925366/555c315a-a0f8-11e6-9643-72812edc6db4.png">

**Comment by felixfbecker** [comment]
I don't think we should set it with `ini_set` because if you don't use it (and it is disabled by default) it is just plain HTML. I told you before completion is not even implemented in this language server, this is VS Code's completion you are seeing 😉 
If Find all References doesn't work for you please open a separate issue.
