### ISSUE TITLE
Find references works only when definition is selected

### ISSUE THREAD

**Issue by mniewrzal** [felixfbecker/php-language-server#132]
For example if class name is selected in use statement then `Find All references` show no results. For the same element `Go to Definition` is working (element can be resolved).

**Comment by felixfbecker** [comment]
Working as intended, references themselves cannot be "referenced". Only definitions can be referenced, so you can only get the references of a definition.

**Comment by mniewrzal** [comment]
I understand but its more about usability. Now to find references you need go to element definition and then search for references. This is one additional move to do what you want. If e.g. class name in use statement can be resolved to definition then there is no obstacle to search for references of it.

**Comment by felixfbecker** [comment]
I will solve this with #54
