### ISSUE TITLE
Incorrect error/warning for "@see" tag in docblock with URL

### ISSUE THREAD

**Issue by ADmad** [felixfbecker/php-language-server#139]
If I have a `@see` tag with a URL like `@see http://someurl` I get warning like `[php] "\Current\Namesapce\http://someurl is not a valid Fqsen.`

As per phpDocumentor's [manual](https://www.phpdoc.org/docs/latest/references/phpdoc/tags/see.html) the `@see` can be of form `@see [URI | FQSEN] [<description>]`. So the error/warning shown is incorrect.

**Comment by felixfbecker** [comment]
This is tracked here: https://github.com/phpDocumentor/ReflectionDocBlock/issues/78
