### ISSUE TITLE
Server initialization failed

### ISSUE THREAD

**Issue by nonameolsson** [felixfbecker/php-language-server#142]
I just upgraded to VS Code Insiders v1.8, with the new PHP Extension Pack. 

After this I can't get the debugger to work. Nothing happens, and the page doesn't load. I have a Vagrant box, and it has worked from the beginning until now without any problems.

When I open up VSCode I get the following error:
![screenshot_1](https://cloud.githubusercontent.com/assets/1493018/20097390/72f0331e-a5ae-11e6-873f-9bb23556f598.png)

This is my `launch.json`, which I haven't changed at all. It was working before the upgrade.
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "localSourceRoot": "${workspaceRoot}/www",
            "serverSourceRoot": "/var/www"
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
```

Am I missing something, or is this a bug?

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/vscode-php-debug#81

**Comment by felixfbecker** [comment]
I thought it was related to the debugger, but it is not. This is the same issue as https://github.com/felixfbecker/php-language-server/issues/113
