### ISSUE TITLE
Server does fail if there is a files or directories without access

### ISSUE THREAD

**Issue by lucassabreu** [felixfbecker/php-language-server#143]
When there is a file or a dir that is blocked for access to the user the server just drop out and crashes.

I am using it with VSCode, to make the error occur, just create a folder inside the project and apply a `chmod -R <folder>` and when the VSCode is restarted the message bellow will be shown.
```
[Error - 14:44:53] Server initialization failed.
  Message: RecursiveDirectoryIterator::__construct(/home/developer/workspace/project/Backend/data/db/fiscal): failed to open dir: Permission denied
  Code: -32603 
```

**Comment by felixfbecker** [comment]
This should be fixed in the latest release. Files that fail to access will just be ignored
