### ISSUE TITLE
Ignore folders for libraries

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#146]
_From @jaimerod on November 3, 2016 6:25_

Add the ability to ignore folders that contain libraries. That way I don't get hundreds of warnings from somebody elses code.

_Copied from original issue: felixfbecker/vscode-php-intellisense#26_

**Comment by felixfbecker** [comment]
Ignore from indexing, or ignore from errors/warnings?

**Comment by felixfbecker** [comment]
_From @jaimerod on November 3, 2016 7:55_

Ignore the errors/warnings because it is code we should not be changing. Is there a way of muting those warnings? It is a good idea to index them because those libraries are still going to be used in the application and intellisense should still work.

**Comment by felixfbecker** [comment]
_From @toretto460 on November 3, 2016 23:49_

I need also this feature to ignore some folders because i don't have read permissions.
Ex. I have a `.mysql` folder used to mount a docker volume and I receive the following error

```
[Error - 7:59:42 PM] Server initialization failed.
  Message: RecursiveDirectoryIterator::__construct(/project/.mysql/my_db_name): failed to open dir: Permission denied
  Code: -32603 
```

**Comment by felixfbecker** [comment]
_From @simonrozsival on November 4, 2016 11:11_

+1

**Comment by felixfbecker** [comment]
_From @d0x2f on November 14, 2016 2:10_

When using Composer, PHP-Intellisense simply fills my error box with hundreds of errors and warnings from third party dependencies in the vendor directory.

I think it shouldn't show errors from directories within the files.exclude vscode setting. That setting seems to align with this issue.

**Comment by kaloyan-raev** [comment]
In Eclipse PDT we have the concept of "library folders". These a folders that are indexed, but no validation is done for them. Composer's "vendor" folder is automatically set as a library folder. Users can mark and unmark library folders as they wish.

**Comment by Seldaek** [comment]
I agree that defaulting to vendor/ is ok, but it should be configurable as some people change the vendor dir to be something else (composer.json > config > vendor-dir lets you do that), and other projects have libraries in more places than one.

**Comment by felixfbecker** [comment]
Sure, but currently there is no configuration at all for the LS so `didChangeConfiguration` etc. would have to be implemented first.

**Comment by ianfoulds** [comment]
+1 for this.
It's intensely annoying every time I open a Symfony project I get recursive directory crashes from the LS..

**Comment by felixfbecker** [comment]
@ianfoulds This issue is already implemented and closed. If you experience crashes, please open a new issue.
