### ISSUE TITLE
Connection to server got closed. Server will restart.

### ISSUE THREAD

**Issue by cesaraaron** [felixfbecker/php-language-server#150]
Hi.
I'm having problems with the extension. 
Doesn't work and always throws five times the '_Connection to server got closed. Server will restart_' and then shuts down.

The console log is always:

> PHP Fatal error:  Method AdvancedJsonRpc\ErrorResponse::__toString() must not throw an exception, caught TypeError: Return value of AdvancedJsonRpc\Message::__toString() must be of the type string, boolean returned in C:\Users\Cesar Aaron\.vscode\extensions\felixfbecker.php-intellisense-0.0.11\vendor\felixfbecker\language-server\src\Protocol\Message.php on line 0

**Comment by felixfbecker** [comment]
Could you give me some guidance how to reproduce this?

**Comment by corretge** [comment]
Same for me, but I don't view any error:

`[Info  - 3:03:08 PM] Parsing file 15078/19685: vendor/symfony/monolog-bundle/DependencyInjection/Compiler/AddSwiftMailerTransportPass.php.
[Info  - 3:03:08 PM] Parsing file 15079/19685: vendor/symfony/monolog-bundle/DependencyInjection/Compiler/DebugHandlerPass.php.
[Info  - 3:03:08 PM] Parsing file 15080/19685: vendor/symfony/monolog-bundle/DependencyInjection/Compiler/LoggerChannelPass.php.

[Info  - 3:03:08 PM] Connection to server got closed. Server will restart.

[Info  - 3:03:20 PM] Parsing file 1/19685: app/AppCache.php`

**Comment by felixfbecker** [comment]
@corretge Please go Help > Toggle Developer Tools

**Comment by corretge** [comment]
lots of thanks @felixfbecker :)

I will fix, but FYI:

```
extensionHost.ts:255 [Extension Host] PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /Users/acorretge/.vscode/extensions/felixfbecker.php-intellisense-0.0.11/vendor/nikic/php-parser/lib/PhpParser/NodeAbstract.php on line 97
PHP Stack trace:
PHP   1. {main}() /Users/acorretge/.vscode/extensions/felixfbecker.php-intellisense-0.0.11/vendor/felixfbecker/language-server/bin/php-language-server.php:0
PHP   2. Sabre\Event\Loop\run() /Users/acorretge/.vscode/extensions/felixfbecker.php-intellisense-0.0.11/vendor/felixfbecker/language-server/bin/php-language-server.php:40
PHP   3. Sabre\Event\Loop\

```

**Comment by felixfbecker** [comment]
Yeah, XDebug a) cripples performance and b) will throw on large files because of recursion depth. @cesaraaron Does this solve your issue too?

**Comment by cesaraaron** [comment]
Nope, but I just find out the problem.

It looks that the server gets closed due to the 'overwhelmed' amount of php files _outside_ of the project (I'm working on a wordpress theme and I've got only that folder open in vscode, but it seems the server looks backwards for php files till the root of... ??).

**Comment by felixfbecker** [comment]
It should only search for PHP files inside the workspace

**Comment by cesaraaron** [comment]
By the way, how can I do for the server to ignore paths? I got everything working well but I'm having an 'RecursiveDirectoryIterator' exception because the server looks inside the node_modules (and there is always a lot of stuff; needless for this case).

**Comment by felixfbecker** [comment]
https://github.com/felixfbecker/php-language-server/issues/159 https://github.com/felixfbecker/php-language-server/issues/113
