### ISSUE TITLE
Indexing progress is at the end of process

### ISSUE THREAD

**Issue by mniewrzal** [felixfbecker/php-language-server#154]
Recently I noticed that indexing progress is not displayed after every file but only at the end of indexing. It's dangerous because LS is sending several hundreds (or thousands) messages in small time frame.

**Comment by felixfbecker** [comment]
For me a message is displayed after every parse - are you using latest release or master?

**Comment by mniewrzal** [comment]
I have this issue with master. Also indexing time and memory consumption increased dramatically:
```
[Info  - 4:00:20 PM] All 739 PHP files parsed in 147 seconds. 870 MiB allocated.
```
Previously the same project was done in 5 sec and with 25mb.

**Comment by felixfbecker** [comment]
Since file retrieval is now an async operation, I do the indexing in parallel with `Promise\all()`:
https://github.com/felixfbecker/php-language-server/pull/136/files?w=1#diff-b7156ac1be31f214d6450d4dbfa3d15fR182

This might have something to do with it. I could very easily switch it back to serial, but in theory it should actually be faster (it can consume much more memory of course if it is done in parallel).

**Comment by mniewrzal** [comment]
Do I need php extension for parallel execution?

**Comment by felixfbecker** [comment]
No, this is done through the event loop. If the client does not support `textDocument/xcontent` request it will not be async really as `file_get_contents()` is used as a fallback. But the indexing will still be triggered on all files simultaneously. The more I think about it though, it might not be a great idea to trigger parsing on 24k files at once.

**Comment by mniewrzal** [comment]
Any idea why its slower and consuming more memory?

**Comment by felixfbecker** [comment]
Higher memory usage is expected
Before:
```
parse 1
       parse 2
              parse 3
```
Now:
```
parse 1
  parse 2
    parse 3
```

But below a certain threshold it is probably not faster for some reason.

**Comment by mniewrzal** [comment]
But its much much slower with just 700 files.

**Comment by mniewrzal** [comment]
Progress works ok now. Thanks!
