### ISSUE TITLE
Size limit for indexed file is missing

### ISSUE THREAD

**Issue by mniewrzal** [felixfbecker/php-language-server#158]
I noticed that size limit for indexed file is missing. This is the reason for longer indexing and bigger memory consumption in my case.

**Comment by felixfbecker** [comment]
Yeah, removed it because there is no way to get the file size without reading from disk... open for suggestions

**Comment by mniewrzal** [comment]
Maybe it will be possible to limit content size (string length)?

**Comment by felixfbecker** [comment]
Sure, that would work, but the file would still be read from disk

**Comment by mniewrzal** [comment]
Should be ok. It just needs to be ignored before parsing.
