### ISSUE TITLE
Problem with Zend 3

### ISSUE THREAD

**Issue by v0idmp3** [felixfbecker/php-language-server#174]
When I open Zend 3 skeleton application, I'm always getting this error: "The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.". But, I dont have problem with any other framework. I tried Laravel 5, Laravel 4, Zend 1.12 and Zend 2. So problem is only with Zend 3 applications. I'm usin PHP 7 on Ubuntu 14.04 but I have same issue on Windows OS.

**Comment by felixfbecker** [comment]
Please give me some stack trace. If you use VS Code, it's printed under Help > Toogle developer tools

**Comment by v0idmp3** [comment]
[-1479725087793.txt](https://github.com/felixfbecker/php-language-server/files/603321/-1479725087793.txt)

**Comment by felixfbecker** [comment]
```
[Extension Host] PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /home/ilija/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeAbstract.php on line 97
```
Increase `xdebug.max_nesting_level` or disable XDebug

**Comment by v0idmp3** [comment]
Yes, XDebug was problem. When I disable it, everything works fine. Thank you :)
