### ISSUE TITLE
Make processId optional for initialization

### ISSUE THREAD

**Issue by mniewrzal** [felixfbecker/php-language-server#177]
According to docs `processId` should be optional:
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#initialize-request

**Comment by felixfbecker** [comment]
Was only changed recently: https://github.com/Microsoft/language-server-protocol/commit/79e553fd4d7e449a4fc1b678a4edcf96320210de

PR welcome :)

**Comment by mniewrzal** [comment]
Yes, I will fix this :)
