### ISSUE TITLE
php process 100% cpu time

### ISSUE THREAD

**Issue by deli6z** [felixfbecker/php-language-server#193]
When this module is turned on on my mac php process takes up to 100% CPU time. I know this explanation is not very detailed and this may be happening on my machine but please help me figure it out. If you need more info about my system I can provide that.

Thank you

**Comment by felixfbecker** [comment]
The LS will index your project at startup, which can take a lot of CPU. If you are using VS Code, you can see the progress in the output panel. Please check if the CPU usage persists after the indexing is finished.

**Comment by deli6z** [comment]
Appreciate your response. Yeah I checked the output panel and it spits out lots of files being indexed. I have a big project so it will take some time. Will check the CPU load after it is finished.
And again thank you for your work, this is amazing!!

**Comment by felixfbecker** [comment]
Atm every time VS Code is opened. Caching will be added in the future, but cache invalidation is one of the hardest challenges in computer science 😉

**Comment by deli6z** [comment]
haha yeah, other one is naming things :)
ps is there a way to exclude a folder from being indexed then? I have a vendor folder with zillion of files which takes forever.

**Comment by kaloyan-raev** [comment]
Check also if you have Xdebug enabled in your PHP stack. Disabling Xdebug improves the speed 5-10 times.

**Comment by deli6z** [comment]
I do have xdebug enabled and I use it extensively. I tried to disable it but it did not affect the php process load.

**Comment by felixfbecker** [comment]
excluding files: #159
Since you are familiar with XDebug, why not enable the profiler and find out what takes so much CPU? 🙂

**Comment by deli6z** [comment]
CPU load is high when I don't even run php scripts and/or XDebug.
Pretty sure it is caused by files indexing. Eagerly awaiting on #159 to be done.

**Comment by felixfbecker** [comment]
Yes, but it could help us optimize the CPU usage if you enabled XDebug and the profiler and get a small profile of the language server

**Comment by deli6z** [comment]
The indexing output is weird. It spits out 'Parsing file N/6310 path/to/file' but when it get to the last file it starts over. So it never ends.

**Comment by deli6z** [comment]
Ok I will try to play with profiler, never used it before.

**Comment by felixfbecker** [comment]
@deli6z Maybe it is crashing and restarting? Look at Help > Toggle developer tools

**Comment by deli6z** [comment]
it crushes on /zend/Validate/Hostname/Com.php file I think. I after that it restarts and starts over 
[Info  - 9:46:05 AM] Connection to server got closed. Server will restart.
this is the error 

[Extension Host] PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in 
{"method":"window\/logMessage","params":{"type":4,"message":"Parsing file 5691\/6310: file:/path/zend\/Validate\/Hostname\/Com.php"},"jsonrpc":"2.0"}
path/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeAbstract.php on line 97

**Comment by felixfbecker** [comment]
That is an XDebug error. Either disable XDebug or increase `max_nesting_level`. Does it crash when you disable XDebug too?

**Comment by deli6z** [comment]
By disable XDebug you mean just disable the VS code extension? I did it and it still crashes.

**Comment by felixfbecker** [comment]
In php.ini you are loading XDebug with `zend_extension = ...`. Comment that line out.

**Comment by deli6z** [comment]
Yeah it was XDebug. Why is it even running in this case?
Now, I need to have XDebug enabled so I need to change max_nesting_level? This looks hackish.
The file itself is causing the error. I should probably look into how I can avoid indexing it.

**Comment by felixfbecker** [comment]
XDebug is always "running". Increasing max_nesting_level is not hackish - it is just the recursion protection that prevents you from infinite loops. In this case, it is a false positive, because it is not actually an infinite loop, just a very nested call, and this can very easily happen during parsing. Set it to something like 3000 and you will be fine and it will still abort in infinite loops. There is no way to exclude a file atm.

**Comment by maaarghk** [comment]
hey, I'm seeing this as well - not running xdebug, and my output window says parsing files ended hours ago - but the language server is still using 100% cpu. is there any kind of 'debug mode' that might help you work out what i'm seeing here?

i'm on ubuntu 16.04.

**Comment by felixfbecker** [comment]
Is there a public project you can reproduce this with? Are the features working?

**Comment by maaarghk** [comment]
Hmm, I'll try a few big ones out. Some features are working - phpdocs for classes is one that works every time, but if I put `/** @var ClassName ... */` notation above a variable or property autocomplete doesn't seem to work.  I tried killing the process and it seems to have restarted and is behaving for now. I'll try to reproduce sometime soon.

**Comment by kwisatz** [comment]
I'm experiencing the same issue as @maaarghk. The language server is running at 100%. No output and features are working. This isn't a public project though.

**Comment by rhildred** [comment]
I am using @theia/php on an amazon ec2 linux instance. I am building a docker container also with theia in it. On the yarn step 4 there is a php process that goes to 100% cpu usage and stays there, Yarn step 4 takes forever.

**Comment by rhildred** [comment]
never mind. It's not you at all. It is composer building the extension @theia/php extension and taking forever.
