### ISSUE TITLE
Not all class members are proposed in completion

### ISSUE THREAD

**Issue by mniewrzal** [felixfbecker/php-language-server#194]
If statement with class members (e.g. method or field) is finished then invoking completion inside such element will not return all possible members with prefix before cursor. Example:
```php
$a = new TestClass();
$a->test|Method();
```
[TestClass](https://github.com/felixfbecker/php-language-server/blob/master/fixtures/global_symbols.php#L21) is from fixtures. If completion will be triggered in place of `|` then only `testMethod()` is proposed. Property `testProperty` should be also visible.

**Comment by felixfbecker** [comment]
Good point. I think this can only be solved by not filtering by the property name at all at the server-side, because the property name is only a string and has no offset information, therefor we cannot get the substring between the beginning of the property name and the cursor.

**Comment by mniewrzal** [comment]
If you mean that it will be filtered only by class name then I think this is good idea. It will return all possible type members and client (e.g. vscode) will do the rest of filtering.

**Comment by felixfbecker** [comment]
Yeah, the fix should be quite easy. Just not include the name in the prefix search. FYI though, currently the completion will not overwrite the `Method`.
