### ISSUE TITLE
Register foreach variables

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#200]

**Comment by felixfbecker** [comment]
@jens1o are you working on this?

**Comment by jens1o** [comment]
Yes, but I'm not sure whether I forgot anything, because I couldn't test it out, because I don't know how I could achieve that... :/

**Comment by felixfbecker** [comment]
Why couldn't you test it?

**Comment by jens1o** [comment]
I don't know how. The symlinks does not seem to work unfortunately. This way, I only could write tests, but I don't want to create a pr where I can't test it out in the wild, so something like that `define` things won't happen again where I missed something that only happens in the wild.

**Comment by felixfbecker** [comment]
What do you mean with the symlinks do not work? What symlinks?

**Comment by jens1o** [comment]
Symlinks that references to my clone... How am I supposed to test it out, maybe I did something wrong? But this was my one-and-only approach.

**Comment by MadHed** [comment]
Are you talking about linking your working copy into the .vscode/extensions folder?

**Comment by jens1o** [comment]
yep, but Felix gave me a heads up, so it should work now. But thanks for wanting to help :)

**Comment by MadHed** [comment]
alright

**Comment by jens1o** [comment]
will create the pr(depending whether I need to add something) tomorrow or on Saturday.

**Comment by NateEag** [comment]
@jens1o, any progress on this? I just ran into this issue myself.

**Comment by jens1o** [comment]
Actually, I didn't touched it seriously anymore since the new parser. I'll take a look now.

**Comment by jens1o** [comment]
@felixfbecker https://github.com/jens1o/php-language-server/commit/5c9b155004946f6af3315650354f35651169151d
Where do I need to register it, too? I think it isn't complete, yet.

**Comment by felixfbecker** [comment]
That's it for go to definition, I think you need to implement it in the CompletionProvider too

**Comment by jens1o** [comment]
Unfortunately `Go to Definition` doesn't works either. :/

**Comment by jens1o** [comment]
Okay, it works now.

**Comment by NateEag** [comment]
Nice. Thanks for working on this, @jens1o!
