### ISSUE TITLE
Find-all-refs for namespaces in use statements

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#204]
Every reference of a symbol in a namespace should count as a reference to the namespace too

**Comment by beyang** [comment]
Does this mean that `textDocument/reference` requests for a namespace will return references to symbols in the namespace?

e.g.,
File 1
```
namespace LanguageServer;

class ClientHandler
{
}
```
File 2
```
using LanguageServer;

$c = new LanguageServer()
```

A reference request on `new LanguageServer()` will display both the `ClientHandler` definition and the `LanguageServer` definition?

**Comment by felixfbecker** [comment]
No, the other way around. A reference request for the namespace would return `new LanguageServer`, probably also `use LanguageServer`. Currently it returns nothing (see the referencing issue)

**Comment by beyang** [comment]
Ah got it.

I made a typo in the original description. I really meant to have `$c = new ClientHandler()` as the 3rd line in File 2.

Would `$c = new ClientHandler()` be counted as a reference to both `ClientHandler` and `LanguageServer`? In the languages that I use, I'd expect it only to be a reference to `ClientHandler`. If I were a user, I think references to `using ...` references would be enough to get me to all the files that use the namespace. Additional references to things within that namespace might just clutter up the interface.

But I also don't write PHP on a regular basis, so will defer to your judgment.

**Comment by felixfbecker** [comment]
I thought so. In PHP there are basically three ways to reference a symbol:
```php
// A fully qualified
namespace Whatever;
new \LanguageServer\ClientHandler();

// B `use`d
namespace Whatever;
use LanguageServer\ClientHandler;
new ClientHandler();

// C local
namespace LanguageServer;
new ClientHandler();
```
As I think about it, it might make sense to only count A and the `use` from B.

**Comment by felixfbecker** [comment]
I have this implemented for `use` statements. Qualified references like `new TestNamespace\TestClass()` depend on https://github.com/nikic/PHP-Parser/pull/331
