### ISSUE TITLE
No completion outside of function

### ISSUE THREAD

**Issue by mniewrzal** [felixfbecker/php-language-server#211]
Example:
```php
<?php
$abc = 1;
$abc2 = 2;
echo $ab
```

**Comment by felixfbecker** [comment]
This only happens when there is no `function` node around the variable, it is not related to the semicolon (there are tests for that)

**Comment by cweagans** [comment]
I started looking into this. Here's what I had:

```patch
diff --git a/fixtures/completion/bare_php.php b/fixtures/completion/bare_php.php
new file mode 100644
index 0000000..36b5ad9
--- /dev/null
+++ b/fixtures/completion/bare_php.php
@@ -0,0 +1,5 @@
+<?php
+
+$abc = 1;
+$abc2 = 2;
+echo $ab
diff --git a/tests/Server/TextDocument/CompletionTest.php b/tests/Server/TextDocument/CompletionTest.php
index 15349ed..3512113 100644
--- a/tests/Server/TextDocument/CompletionTest.php
+++ b/tests/Server/TextDocument/CompletionTest.php
@@ -433,4 +433,35 @@ class CompletionTest extends TestCase
             )
         ], true), $items);
     }
+
+    public function testBarePhp()
+    {
+        $completionUri = pathToUri(__DIR__ . '/../../../fixtures/completion/bare_php.php');
+        $this->loader->open($completionUri, file_get_contents($completionUri));
+        $items = $this->textDocument->completion(
+            new TextDocumentIdentifier($completionUri),
+            new Position(5, 8)
+        )->wait();
+        $this->assertEquals(new CompletionList([
+            new CompletionItem(
+                '$abc',
+                CompletionItemKind::VARIABLE,
+                null,
+                null,
+                null,
+                null,
+                '$abc'
+            ),
+            new CompletionItem(
+                '$abc2',
+                CompletionItemKind::VARIABLE,
+                null,
+                null,
+                null,
+                null,
+                '$abc2'
+            ),
+        ], true), $items);
+    }
+
 }
```

I started debugging, but I'm out of time to spend on this for today, but here's the gist of what I found:

`$doc` that's passed to `CompletionProvider::provideCompletion()` when this test is run is incomplete - it only contains AST nodes for the variable assignments, so `$doc->getNodeAtPosition()` returns NULL for the position at the end of the last line. I'm wondering if there's something weird going on with the parser because the last line is invalid PHP syntax.

**Comment by felixfbecker** [comment]
If that is the case, this is a bug in the parser. In any case, feel free to open a PR, that unit test is valuable

**Comment by cweagans** [comment]
Happy to do so. Just wasn't sure if you wanted a failing test or not.

**Comment by nikic** [comment]
This should now be fixed in PHP-Parser. Please test :)

**Comment by felixfbecker** [comment]
@nikic just tested with v3.0.3.
This is the AST with the code snippet in the original post:

![image](https://cloud.githubusercontent.com/assets/10532611/22643061/48638ac4-ec5d-11e6-99fb-f8fbfa601788.png)

The `echo` statement is missing

**Comment by nikic** [comment]
The change isn't in v3.03, can you try 3.0-dev?

**Comment by felixfbecker** [comment]
@nikic works. Please ping me when you release it :)
