### ISSUE TITLE
Symbols list isn't updated after change in empty file

### ISSUE THREAD

**Issue by mniewrzal** [felixfbecker/php-language-server#212]
To reproduce use VSCode:
- create php file with content:
```php
<?php
class Abc 
{
}
```
- trigger symbols in file (shift+ctrl+o), `Abc` symbol should be visible
- delete whole class code
- don't save file
- trigger symbols in file once again, `Abc` symbol is still visible

![screenshot from 2016-12-08 14-54-50](https://cloud.githubusercontent.com/assets/7313031/21012467/70f1d288-bd56-11e6-921e-b0779ef2c5d4.png)

**Comment by felixfbecker** [comment]
Any idea why? It should do here:
https://github.com/felixfbecker/php-language-server/blob/master/src/PhpDocument.php#L190-L195

**Comment by mniewrzal** [comment]
For only `<?php` tag `$stmts` is empty array (https://github.com/felixfbecker/php-language-server/blob/master/src/PhpDocument.php#L155)

**Comment by felixfbecker** [comment]
Oh, makes sense!
