### ISSUE TITLE
Eclipse Che integration

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#216]
@mniewrzal @kaloyan-raev I would like to know about the status/plans of using the LS in Eclipse Che - feel free to mention any blocking issues

**Comment by kaloyan-raev** [comment]
@felixfbecker The LS is currently used in Eclipse Che.

The easiest way to try it yourself is to create a free account at https://codenvy.io/ and start a workspace with a PHP or Zend stack.

The version that is currently there is 3.x + the initial code completion implementation by @mniewrzal. In the next days I am going to try the latest 4.0 version and if everything is OK I will update Eclipse Che with it.

**Comment by felixfbecker** [comment]
Cool! I would add Che to the "Used by" section to the readme then.

**Comment by kaloyan-raev** [comment]
Absolutely!
