### ISSUE TITLE
High CPU usage on startup

### ISSUE THREAD

**Issue by sjelfull** [felixfbecker/php-language-server#222]
VS Code version: 1.8.0
OSX: Sierra 10.12.1

I restarted VS Code just now, and on a non-PHP project, I see this in the process list:

![image](https://cloud.githubusercontent.com/assets/10508/21258434/4bedddc4-c37d-11e6-8773-257adacec981.png)

It's currently using 95% CPU without any indication of doing anything, and this is on a project that doesn't contain any PHP code.

**Comment by felixfbecker** [comment]
Dup of #193 ?
Look at the output panel, it is probably indexing.
Also, the LS is only activated when you open a PHP file, so this happening in a non-PHP project is very unlikely

**Comment by sjelfull** [comment]
If that's the case, it was probably hanging from when I was working on a PHP-project.

I restarted VS Code and killed the process. Will report back if it happens again.

It might be related to xdebug too, since I have that enabled.

**Comment by felixfbecker** [comment]
XDebug has a major impact on performance. If you notice a hang-up please open a new issue, thanks!
