### ISSUE TITLE
Possible useful features from Roave/BetterReflection

### ISSUE THREAD

**Issue by MarkRedeman** [felixfbecker/php-language-server#223]
Hi Felix,

Are you aware of the [Roave/BetterReflection](https://github.com/Roave/BetterReflection) library? They may have some features that could be useful for your project.
For instance there is currently a [pr](https://github.com/Roave/BetterReflection/pull/224) to add a variable collector which adds the option to get all variables (and their possible types) inside of function. 
This might help resolve #160 (though I'm not sure since I haven't yet looked at your code).

**Comment by felixfbecker** [comment]
No, wasn't aware of it. Does it resolve types recursively like I do?
I'm always for using existing packages and improving them.
#160 is a very easy ticket though, I just haven't got around to fixing it, it's low priority.

**Comment by MarkRedeman** [comment]
> No, wasn't aware of it. Does it resolve types recursively like I do?

I'm not quite sure yet how you do it (I might take a look at your code during my christmas break while I try to integrate this into my Emacs setup :) ). The PR that I mentioned currently only supports assigning variable definitions and determines its type by the right hand side of the assignment.

> I'm always for using existing packages and improving them.
> #160 is a very easy ticket though, I just haven't got around to fixing it, it's low priority.

Good, I will close this issue for now since it isn't a bug or feature request.
