### ISSUE TITLE
Composer cannot find jetbrains/phpstorm-stubs repository

### ISSUE THREAD

**Issue by iluuu1994** [felixfbecker/php-language-server#227]
When running `composer require felixfbecker/language-server` I get the following error message:

```
Using version ^4.1 for felixfbecker/language-server
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - felixfbecker/language-server v4.1.1 requires jetbrains/phpstorm-stubs dev-master -> no matching package found.
    - felixfbecker/language-server v4.1.0 requires jetbrains/phpstorm-stubs dev-master -> no matching package found.
    - Installation request for felixfbecker/language-server ^4.1 -> satisfiable by felixfbecker/language-server[v4.1.0, v4.1.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

It looks like Composer cannot find the `jetbrains/phpstorm-stubs` repository even though it is corrently configured in the [composer.json](https://github.com/felixfbecker/php-language-server/blob/662143abadfa8e1882f8870545325d8ac0454088/composer.json). Running `composer clear-cache` did not help. Any idea what's going on?

**Comment by iluuu1994** [comment]
Also, the `minimum-stability` is set to `dev` so that shouldn't be a problem.

**Comment by felixfbecker** [comment]
Repositories are only valid for the root package for security reasons, see https://getcomposer.org/doc/faqs/why-can't-composer-load-repositories-recursively.md

If you "trust" the repository, you need to duplicate the repository definition in your own composer.json. I have a pending PR on JetBrain's repository to add a composer.json and publish on Packagist.
This should maybe be highlighted in the readme, feel free to do a PR.

**Comment by iluuu1994** [comment]
Oh, I got it, thank you!

**Comment by oolleegg55** [comment]
Sorry, can you show me steps what I have to do in this case?

**Comment by 1298799999** [comment]
git clone url-of-this-project.git
composer install
