### ISSUE TITLE
Format code does nothing

### ISSUE THREAD

**Issue by BertoMejia** [felixfbecker/php-language-server#228]
I installed PHP IntelliSense to VS Code 1.8.1 on Win 7 with php-7.1.0 installed, and the code format does nothing. I've tried looking for a wrong setting, errors or a solution on the web, and found nothing. Can you please help fix this?

**Comment by jinformatique** [comment]
Hi, I installed VS Code 1.13.1 on KDE Neon 5.10 with PHP IntelliSense.
In my settings.json I added:
```
"php.suggest.basic": false,
"php.executablePath": "/usr/bin/php",
```

When I do a right click in any PHP file, I don't have the entry "Format Code" as show on the screenshot from the plugin:
![Format Code](https://github.com/felixfbecker/php-language-server/raw/master/images/formatDocument.gif)


This is what I got:
![Right click](https://framapic.org/zyl2lZlFZWPi/ljFh2Ktq7xbr.gif)

Is there something missing?

**Comment by felixfbecker** [comment]
VS Code renamed the entry to "Format Document"

**Comment by jinformatique** [comment]
Ok thanks. So the fact that it does nothing is still an open bug?

**Comment by BertoMejia** [comment]
Yes, that is still an open bug, but it seems that there is progress since the last update. When I try to format the document, it formats, but it does not format correctly.

This is before:
![image](https://user-images.githubusercontent.com/11620476/28192220-452715d8-67fa-11e7-912b-0d320f06c688.png)

The is after
![image](https://user-images.githubusercontent.com/11620476/28192223-4eea6e94-67fa-11e7-8065-2760ad41096f.png)

It ignores several lines, and others it just sends them to the beginning of the line.

**Comment by felixfbecker** [comment]
There is no longer a document formatter in the language server.
