### ISSUE TITLE
The PHP Language Server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by qobus** [felixfbecker/php-language-server#232]
Using Windows 7 Pro with VS Code 1.8.1 and PHP IntelliSense 0.0.12.

Since few days i've got the problem that my PHP server "crashes" everytime i (re)open my VS Code.

Path to my php.exe is in my PATH AND I've also added php.validate.executablePath to my workspace settings.

Recently i updated to PHP 7.1, but it also did'nt work with 7.0.13.

Are there any logs i can audit?

**Comment by MadHed** [comment]
Help->Toggle Developer Tools there you should see any php errors reported.

**Comment by felixfbecker** [comment]
Also FYI `php.validate.executablePath` is for the built-in validation. `php.executablePath` is for the language server.

**Comment by qobus** [comment]
After opening the Chrome Dev-Tools (thanks to @MadHed) i got the error **Permission denied (code: 5)**

It looks like the extension tries to find PHP files in my storage/cache directory (i'm using Laravel), but did'nt have the permissions to access them. A simple *chmod 777* did the job. Maybe there should be a feature to exclude some folders from "scanning".

Thanks for your help!
