### ISSUE TITLE
Add a fallback: go to first workspace symbol when go to definition fails

### ISSUE THREAD

**Issue by icetbr** [felixfbecker/php-language-server#233]
Hi, I have something like this (from vork)

get::model('car')->run()

Go to definition on "run" does nothing. If I search for workspace symbols "run", I can find it very easy. Wouldn't it be possible/easy/nice to have this as a fallback?

Other IDEs handle this with no problem, although they lack some of the other awesomeness of this plugin.

Thanks

**Comment by felixfbecker** [comment]
Are you suggesting to just jump to any method called `run` if the type of the object the method is called on could not be resolved?
Is `get::model()` properly annotated with a return type?

**Comment by icetbr** [comment]
Yes, something like that. What I currently have to do is "select word, copy, ctrl + t, ctrl + v, enter" as a replacement for when "goto definition" fails. Of course I'm using a somewhat unpopular framework that seems to break conventions, so that this plugin doen's work on some cases.

It could be a different command. The default behavior in editors with this functionality (regex based I think, like sublime and Atom, both which goto definition work with my code base) is to show a quick popup list of the matched found methods so you can easily pick one.

In my experience, the first option is most of the time the right choice. Also, the methods I work with usually have long unique names.

This seems to be that method, from webroot/vork (this is a file from the framework, it has no extension) http://www.vork.us/app/vork-enterprise-php-framework

```
class get {
...
    /**
     * Returns a model object
     *
     * @param string $model
     * @param mixed $args Optional - arguments to be passed to the model-object constructor
     * @return object
     */
    public static function model($model = null, $args = null) {
        return self::_loadObject('model', $model, $args);
    }

    /**
     * Loads an object as a singleton
     *
     * @param string $objectType
     * @param string $objectName
     * @param mixed $args Optional, default is null - this is sent as an argument to the constructor and used as part
     *                    of the criteria to determine a unique singleton object - differing args return new objects
     * @return object
     */
    protected static function _loadObject($objectType, $objectName, $args = null) {
...
}
```

**Comment by felixfbecker** [comment]
I am against doing this. This is a static analysis tool and falling back to essentially random methods with the same name makes the behavior totally unpredictable.
If your framework is not annotated properly, annotate your variables:
```php
/** @var Model */
$model = get::model('car');
$model->run();
```

**Comment by icetbr** [comment]
Thanks for the feedback. I understand your reasons and I know it is the frameworks fault not to support this. However, the regex approach does have its benefits, as it is in my case though.

**Comment by felixfbecker** [comment]
The annotation should do it, if not, please open a separate issue. Also please note the implementation would not use any regexps, it's all AST nodes and indexing.

**Comment by icetbr** [comment]
Yes, I know your implementation is not regexp based, I was talking about the other IDEs. Regarding the annotation, it is not very useful to me, because I would not be able to change the code (its not mine, I'm only translating it to node). If you think it would be beneficial, I would gladly open the issue and/or dig deeper into the problem.

**Comment by icetbr** [comment]
Yes, I know your implementation is not regexp based, I was talking about the other IDEs. Regarding the annotation, it is not very useful to me, because I would not be able to change the code (its not mine, I'm only translating it to node). If you think it would be beneficial, I would gladly open the issue and/or dig deeper into the problem.
