### ISSUE TITLE
Automatically add use statement

### ISSUE THREAD

**Issue by longrunningprocess** [felixfbecker/php-language-server#234]
When adding a class in the code, it would be great if the use statement was automatically written into the top of the file.  Thanks for considering!

**Comment by felixfbecker** [comment]
I would love to have this, and it is not even hard that hard to implement.

**Comment by wcjr** [comment]
Glad to hear it wouldn't be difficult.  I hope you'll forgive me for not contributing beyond the request 0:-)

**Comment by arturolinares** [comment]
:+1:

**Comment by felixfbecker** [comment]
Please don't +1 issues. It clutters the thread without adding value to the discussion and spams maintainers with notifications. Use GitHub reactions to upvote features.
![image](https://cloud.githubusercontent.com/assets/10532611/18344735/bb60c2f6-75b8-11e6-88a9-822fae298110.png)

**Comment by sugarmaster** [comment]
Here is the sublime equivalent if it helps.
https://github.com/erichard/SublimePHPCompanion/blob/master/php_companion/commands/find_use_command.py

**Comment by jens1o** [comment]
@felixfbecker Is there any protocol I can use?

**Comment by felixfbecker** [comment]
yeah, you can return `additionalTextEdits` from `textDocument/completion`

**Comment by jens1o** [comment]
@felixfbecker How to get the positon of the first php start tag after the namespace definition? I don't have any (serious) idea. Should I set a variable in `PhpDocument` with the place to enter while parsing the thing?

**Comment by felixfbecker** [comment]
Theres a `getClosestNode()` in helpers which you can use to find the closest namespace Node, then you can easily get the first statement inside it.

**Comment by jens1o** [comment]
Beautiful. I thought I need to implement this functionality myself.

**Comment by jens1o** [comment]
Ah, there is a bug. `getClosestNode` will return void instead of null. Short pull request comes...

**Comment by felixfbecker** [comment]
Functions that return nothing return `null`.

**Comment by jens1o** [comment]
This does not. That's the bug.

**Comment by felixfbecker** [comment]
```php
function foo() {
}

$f = foo()

var_dump($f); // null
```

**Comment by jens1o** [comment]
It's better to return that from the code, isn't it?

**Comment by felixfbecker** [comment]
It makes not difference

**Comment by jens1o** [comment]
okay.

**Comment by jens1o** [comment]
How is the PHP start tag called in php-parser? I'd looked in the files, but I couldn't find anything related.
`Node\Stmt\Namespace_` is for Namespaces
`???` is for the PHP start tag?

**Comment by felixfbecker** [comment]
There is no PHP start tag, only `InlineHtml`

**Comment by jens1o** [comment]
But I can't rely on that, can I?

**Comment by staabm** [comment]
before the first class definition?

**Comment by jens1o** [comment]
yes, and maybe behind the declare node.

**Comment by felixfbecker** [comment]
The fallback would just be at the root? Which is the `$stmts` array

**Comment by jens1o** [comment]
But then it may be possible to get a use statement right after inline html?

**Comment by thoresuenert** [comment]
@jens1o how is it going?
do you need help?
Where to contribute?

**Comment by jens1o** [comment]
Hmm, I didn't continued, since I have school again and I'm writing lots of exams... So yeah, I need some help. In the evening, I'll push my tries, maybe you can contribute..

**Comment by Munsio** [comment]
@jens1o where can we find the branch?

**Comment by jens1o** [comment]
On my old pc. Dammit. I'm again in exam phase, I'm sorry. Even though, I would have to write it again because of the new parser. Before I can do that, I would like to push forward foreach support.
