### ISSUE TITLE
query all symbols return fewer symbols in the folder?

### ISSUE THREAD

**Issue by lialan** [felixfbecker/php-language-server#238]
Hi @felixfbecker thanks for your amazing library, very useful.

At this moment I am trying to integrate php lsp using lsp4j, and want to query all of the symbols from the specified folder. 

What I did was to first initialize the server with the root path, and them query using an empty string. Ideally it should return all symbols in the designated folder. However it only returns a small part of all the symbols in the folder.

I've tried to query php-language-server itself: What I did was to point the root folder to src/ in the initialization, and query using an empty string. What I get are a few symbols from LanguageServer\Client\TextDocument and Language\Client.  If I point the root folder to the project's root folder then I get nothing from the query.

I remember a while ago I tried to print out $symbols in Workspace and it indeed only contained a few symbols. Maybe I remembered it incorrectly.

I am trying to get all the symbols. Perhaps you could shed some light on how it might achieve the goal?

**Comment by felixfbecker** [comment]
Until the most recent version indexing happenend in background, so you may got incomplete results.  Try v4.2 and see if you still experience it.

**Comment by lialan** [comment]
Thanks @felixfbecker , using v4.2 indeed returns more symbols than before. 

I tried to wait a bit after initialization using v3.1, and it is indeed returning more symbols as expected. 

One question is that when using v4.2, when I try to query Namespace, Class or Method, the server seems to not able to return anything, resulting a freeze. Waited for a few mins and it is still like this. Wondering if it is a know issue?

**Comment by felixfbecker** [comment]
Please open a new issue for that
