### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by levan-g** [felixfbecker/php-language-server#24]
Is it possible to debug language server with vscode?

**Comment by felixfbecker** [comment]
Sure! Have you tried it with https://github.com/felixfbecker/vscode-php-debug?

This launch.json config works to run PHPUnit tests:
```json
    {
      "name": "PHPUnit",
      "type": "php",
      "request": "launch",
      "program": "${workspaceRoot}\\vendor\\phpunit\\phpunit\\phpunit",
      "args": ["--bootstrap", "vendor/autoload.php", "tests"],
      "cwd": "${workspaceRoot}"
    }
```

If you want to debug it in action, I recommend to open vscode-php-intellisense in a seperate window and symlink vendor/felixfbecker/language-server to the git clone of the language server. Then in the window with php-language-server, you can use the "Listen for XDebug" configuration and set breakpoints. Launch the extension from the window with vscode-php-intellisense.

**Comment by levan-g** [comment]
I repeated steps that you described but nothing happens.

```json
{
   "name": "Listen for XDebug",
   "type": "php",
   "request": "launch",
   "port": 9000
}
```

**Comment by felixfbecker** [comment]
Running PHPUnit or debugging with vscode-php-intellisense? Did you install XDebug properly?

**Comment by levan-g** [comment]
running debug, yes XDebug is properly installed. I'll double check and let you know.

**Comment by felixfbecker** [comment]
You might wanna look into the troubleshooting section of vscode-php-debug. In particular, enable `xdebug.remote_log` in your php.ini.

**Comment by felixfbecker** [comment]
Try to run the tests with some breakpoints and see if that works.

**Comment by felixfbecker** [comment]
Just tried it again and it works for me.
Creating the symlink:
```
felix@FELIX-PC ~\git\OpenSource\vscode-php-intellisense\vendor\felixfbecker [master ≡]
$ rm -re -fo .\language-server\

felix@FELIX-PC ~\git\OpenSource\vscode-php-intellisense\vendor\felixfbecker [master ≡]
$ New-Symlink language-server ~\git\OpenSource\php-language-server

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----l       11.09.2016     20:30                language-server
```
launch.json in php-language-server:
```json
{
      "name": "Listen for XDebug",
      "type": "php",
      "request": "launch"
}
```
And the included "Launch Extension" config from vscode-php-intellisense. Of course you then need to open a PHP project so the extension gets activated.

**Comment by levan-g** [comment]
without port option?

**Comment by felixfbecker** [comment]
Port defaults to 9000.

**Comment by felixfbecker** [comment]
Can you run PHPUnit at least?

**Comment by levan-g** [comment]
when I launch extension development host and execute command to list symbols in document nothing happens, progress bar just runs.

**Comment by levan-g** [comment]
I just removed all breakpoints and extension work again, but without debugging :(

**Comment by felixfbecker** [comment]
Can you run PHPUnit with the debugger?

**Comment by levan-g** [comment]
I have finally launched debugging. I've just unchecked warnings and exceptions in breakpoints section of debugger.

**Comment by felixfbecker** [comment]
It is very hard for me to help you if you provide so little information... What did you finally launch (PHPUnit/intellisense)? Can you hit breakpoints?

**Comment by levan-g** [comment]
Yes, I can hit breakpoints. PHPUnit, Debugger and intellisense work.

**Comment by felixfbecker** [comment]
So everything is working now? It is probably a good idea to add some guidance to the readme.

**Comment by levan-g** [comment]
Yes everything works fine. I don't know why, but exceptions and warnings option in debugger was causing this behavior.

**Comment by felixfbecker** [comment]
That's not the way it should be... please open an issue at vscode-php-debug. Make sure to include what versions of PHP/XDebug you are running and the log from `xdebug.remote_log` :)

**Comment by levan-g** [comment]
ok. thank's for help.

**Comment by bmax** [comment]
Hello @felixfbecker,

Trying to do the same thing as @lgabeskiria and use xdebug on the php-language-server. 

I followed all your steps but am not ableto get the breakpoints to execute. the PHPUnit xdebug does work and when I use the `Listen for XDebug` and launch extension development host, I get this:

![image](https://user-images.githubusercontent.com/158370/32531524-20ba3cba-c412-11e7-9300-4e6120ff8d65.png)

as you can see there is Request's coming through but they never change from `Running` and I can't get that breakpoint to execute on https://github.com/felixfbecker/php-language-server/blob/master/src/LanguageServer.php#L114

Any help would be appreciated thanks!!

**Comment by felixfbecker** [comment]
I am confused, are you saying PHPUnit works or does not work?

Try setting the environment variable `COMPOSER_ALLOW_XDEBUG` to `1`

**Comment by bmax** [comment]
PHPUnit does work. I just added `COMPOSER_ALLOW_XDEBUG` as an env variable and it worked, interesting.

Thank you.

**Comment by felixfbecker** [comment]
Could you do a PR to add that to the README?

This is the reason why it's needed:
https://github.com/felixfbecker/php-language-server/blob/b03b9a239c38db5d4551ce5b9f0e3876e458edd4/bin/php-language-server.php#L34-L35

**Comment by bmax** [comment]
Sure! I'll do that tomorrow.

Thanks for help.
