### ISSUE TITLE
"is not a valid Fqsen" warnings

### ISSUE THREAD

**Issue by lumpysimon** [felixfbecker/php-language-server#244]
While indexing a WordPress site, Intellisense generates lots of `[Something] is not a valid Fqsen` warnings. They are all caused by DocBlock-style comments, so as far as I am aware they are valid and should not cause warnings:

![not-valid-fqsen](https://cloud.githubusercontent.com/assets/625372/22078731/f9ce26a4-ddb0-11e6-92b4-fc019ff2ad70.png)

**Comment by felixfbecker** [comment]
That is not a valid FQSEN, the quotes should not around it.

**Comment by lumpysimon** [comment]
Aha. So the offending part of the comment should read `{@see wp_head}`?

**Comment by felixfbecker** [comment]
Pretty sure

**Comment by lumpysimon** [comment]
Thanks - I'll raise a ticket on WordPress trac to see if that can be changed.

**Comment by bbak** [comment]
Got the same Error Message, but on URIs.

[@see should allow a FQSEN or a URI as per RFC2396](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#716-see).

Therefore, these should be valid:
```
@see http://www.php.net/manual/en/function.imagecreatefromgif.php#104473
@see http://foone.org/apng/
```

**Comment by felixfbecker** [comment]
@bbak https://github.com/felixfbecker/php-language-server/issues/139

**Comment by ikappas** [comment]
@lumpysimon Did you ever get around opening a WordPress trac ticket for this?

**Comment by khoazero123** [comment]
I have to comment this link :3
![untitled](https://user-images.githubusercontent.com/2802354/26879957-171e40fc-4bbd-11e7-978b-715524048a55.png)
