### ISSUE TITLE
Indexing stuck in an eternal loop

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#245]
_From @lumpysimon on January 18, 2017 18:57_

Intellisense is taking an enormous amount of time to index a project (a WordPress site with 2352 files to parse). After 30mins it's still chugging through. During this time CPU usage is at 99.8% and both fans are going bonkers (2015 top spec MacBook Pro 15").

So I looked at the output window and discovered it seems to be going round and round and never reaching the end. Here's the bit of the output showing where it gets to before a `Connection to server got closed. Server will restart` error occurs:

```
Parsing file 842/2352: file:///private/var/www/sites/mysite/wp-content/plugins/gravity-forms-advanced-file-uploader/inc/VideoUploader/includes/Zend/Validate/Hostname/Cn.php
[Info  - 6:46:48 PM] Ignoring file file:///private/var/www/sites/mysite/wp-content/plugins/gravity-forms-advanced-file-uploader/inc/VideoUploader/includes/Zend/Validate/Hostname/Cn.php because it exceeds size limit of 150000 bytes (168073)
Parsing file 843/2352: file:///private/var/www/sites/mysite/wp-content/plugins/gravity-forms-advanced-file-uploader/inc/VideoUploader/includes/Zend/Validate/Hostname/Com.php
[Info  - 6:46:48 PM] Connection to server got closed. Server will restart.
Parsing file 0/2352: file:///private/var/www/sites/mysite/a.php
Parsing file 1/2352: file:///private/var/www/sites/mysite/docs/temp/inc/admin.php
Parsing file 2/2352: file:///private/var/www/sites/mysite/docs/temp/inc/comments.php
Parsing file 3/2352: file:///private/var/www/sites/mysite/docs/temp/inc/core.php
Parsing file 4/2352: file:///private/var/www/sites/mysite/docs/temp/inc/courses.php
```

_Copied from original issue: felixfbecker/vscode-php-intellisense#48_

**Comment by felixfbecker** [comment]
Please look for a stack trace in Help > toggle developer tools

**Comment by jeffkotula** [comment]
Continues parsing even after the plugin is disabled too.

**Comment by jeffkotula** [comment]
[Extension Host] seNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0794   99141640 209. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0794   99142112 210. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0794   99142584 211. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0794   99143056 212. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0794   99143528 213. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0795   99144000 214. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0795   99144472 215. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0795   99144944 216. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0795   99145416 217. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0796   99145888 218. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0796   99146360 219. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0796   99146832 220. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0796   99147304 221. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0797   99147776 222. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0797   99148248 223. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0797   99148720 224. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0797   99149192 225. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0798   99149664 226. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0798   99150136 227. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0798   99150608 228. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0798   99151080 229. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0798   99151552 230. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0799   99152024 231. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0799   99152496 232. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0799   99152968 233. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0799   99153440 234. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0800   99153912 235. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0800   99154384 236. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0800   99154856 237. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0800   99155328 238. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0801   99155800 239. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0801   99156272 240. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0801   99156744 241. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0801   99157216 242. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0802   99157688 243. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0802   99158160 244. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0802   99158632 245. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0802   99159104 246. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0802   99159576 247. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0803   99160048 248. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:101
  287.0803   99160520 249. PhpParser\NodeTraverser->traverseNode() /Users/KotulaJ/.vscode/extensions/felixfbecker.php-intellisense-0

**Comment by jeffkotula** [comment]
Then it starts over at file 1

**Comment by jeffkotula** [comment]
In my case it is happening during parsing of LoggerChannelPass.php in symfony.

**Comment by felixfbecker** [comment]
That is just part of the stack trace, what is the error message?

**Comment by jeffkotula** [comment]
Oops. Yeah, sorry. Infinite recursion -- exceeded the allowed stack depth. The big problem is that it restarts all the parsing all over again, not really so much that it fails on a single file.

**Comment by jrobeson** [comment]
i'm seeing the same behavior here, although it's nothing is showing in the output window, just in the debug window.

**Comment by felixfbecker** [comment]
Increase or disable XDebug max_nexting_level.

**Comment by freephile** [comment]
https://xdebug.org/docs/all_settings#max_nesting_level
