### ISSUE TITLE
Completion does not work in VS Code

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#256]
Seems like there are restrictions on the legal combinations of properties in `CompletionItem`.
Also, `textEdit` is now deprecated and I will from now on use `range` and `insertText`.

@mniewrzal @kaloyan-raev let me know if this will cause problems in Eclipse (Che)

**Comment by kaloyan-raev** [comment]
@felixfbecker Can you point me to these changes in the protocol? I cannot find where it is stated that `textEdit` is deprecated. I also don't see the new `range` property in the `CompletionItem`. I am looking at version 3.0 of the protocol.

**Comment by mniewrzal** [comment]
At the moment changes in `CompletionItem` are missing. Something goes wrong with latest commit.

https://github.com/Microsoft/language-server-protocol/issues/165

**Comment by felixfbecker** [comment]
https://github.com/Microsoft/language-server-protocol/commit/b082a3bd761f7c50db0b538e954ac467e8aa5ba8 reverted the deprecation, very weird!

**Comment by kaloyan-raev** [comment]
@felixfbecker Regarding your question. This change will affect other clients like Eclipse Che and LSP4E. Most probably they will need to adapt to use `insertText` and `range` instead of `textEdit`. But, if this is the intended direction of the protocol, then feel free to do it.

**Comment by mniewrzal** [comment]
I agree with @kaloyan-raev. Main Java binding for LSP is still not updated with new `CompletionItem` but its just matter of time https://github.com/eclipse/lsp4j/issues/41

**Comment by felixfbecker** [comment]
I am not using `textEdit` consistently atm either so if I want to clean it up I think the best would be to go with the new properties now. Just wanted to check if it would be a breaking change (major release), I think it would not because your clients should in theory fall back to inserting the label.

**Comment by ADmad** [comment]
Not sure if my problem is directly related to this issue but here goes. 

Auto completion are not automatically triggering for me. For e.g. if I have a class method with argument `$options`, when typing `$op` in the method body i would expect to get completion suggestion for `$options`, but i don't. I do get suggestions list upon using Ctrl + Space keys. Is this expected behavior? 

I am using the language server release `4.2.2` and VS Code version `1.9.0-insider`
Commit `4265f5e35cb3ea8ba7e0cf6b14ec606b6f8647ea`

**Comment by felixfbecker** [comment]
Not related, please open new issue

**Comment by felixfbecker** [comment]
https://github.com/Microsoft/vscode-languageserver-node/issues/95
