### ISSUE TITLE
Javascript based intellisense for wysiwyg editors

### ISSUE THREAD

**Issue by staabm** [felixfbecker/php-language-server#257]
Thx for this awesome project..

I would like to build a intellisense for a html editor (or even a plain textarea) including intellisense and autocompletion capabilities in a browser.
Are you aware of any javascript based client libs which impelement the language server protocol?
Or do you even suggest going down another route to fix this kind of problem?

Thx, Markus

**Comment by felixfbecker** [comment]
Sure, take a look at vscode-languageserver. Just be aware that you will have to run the language server on the server (you could let them talk over a websocket) and need to be a bit creative to scale that :)
