### ISSUE TITLE
Packages are only searched for in composer.lock packages, not packages-dev

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#258]
workspace/xdependencies, workspace/xreferences all do not include data from dev dependencies

**Comment by ADmad** [comment]
If you are developing the project wouldn't you have done a dev install thereby also having the dev dependencies installed and listed in `composer.lock`?

**Comment by felixfbecker** [comment]
Yes, but we need to read it :)

**Comment by ADmad** [comment]
Guess is misunderstood :)  Perhaps it would be nice if using dev dependencies would be configurable. Dev depending could add a significant number of classes and it could slow down the indexing or other features. I am just speculating here.

**Comment by felixfbecker** [comment]
You are misunderstanding the issue, this is only about the mentioned methods. Here is the issue:
https://github.com/felixfbecker/php-language-server/blob/master/src/Server/Workspace.php#L127

this is what needs to look like (see `array_merge`):
https://github.com/felixfbecker/php-language-server/blob/b3855be9fb803b1fb4cd6a025520cf4ee01f3a9c/src/Indexer.php#L143

**Comment by ADmad** [comment]
Sorry for the trouble, I should keep my mouth shut about things i don't properly understand.

**Comment by felixfbecker** [comment]
no worries
