### ISSUE TITLE
How to make the VSCode extension work

### ISSUE THREAD

**Issue by BernalCarlos** [felixfbecker/php-language-server#26]
Hi,

I just downloaded the extension for VSCode, but it does not seem to work. For example, i cant find symbols (it says "unfortunately we have no symbol information for the file") or format code (the option doesn't appear on the context menu).

I'm using Linux Mint 18, the latest version of VSCode, and installed PHP 7 using `sudo apt-get install php`.

Is there something else i'm supposed to do?

Thank you.

**Comment by felixfbecker** [comment]
This issue was moved to felixfbecker/vscode-php-intellisense#9
