### ISSUE TITLE
failed to install package with `composer require felixfbecker/language-server`

### ISSUE THREAD

**Issue by roxma** [felixfbecker/php-language-server#265]
failed to install package with `composer require felixfbecker/language-server`

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - felixfbecker/language-server v4.2.3 requires squizlabs/php_codesniffer 3.0.x-dev#e8acf8e029301b0e3ea7e7c9eef0aee914db78bf -> satisfiable by squizlabs/php_codesniffer[3.0.x-dev] but these
 conflict with your requirements or minimum-stability.
    - felixfbecker/language-server v4.2.2 requires squizlabs/php_codesniffer 3.0.x-dev#e8acf8e029301b0e3ea7e7c9eef0aee914db78bf -> satisfiable by squizlabs/php_codesniffer[3.0.x-dev] but these
 conflict with your requirements or minimum-stability.
    - felixfbecker/language-server v4.2.1 requires squizlabs/php_codesniffer 3.0.x-dev#e8acf8e029301b0e3ea7e7c9eef0aee914db78bf -> satisfiable by squizlabs/php_codesniffer[3.0.x-dev] but these
 conflict with your requirements or minimum-stability.
    - felixfbecker/language-server v4.2.0 requires squizlabs/php_codesniffer 3.0.x-dev#e8acf8e029301b0e3ea7e7c9eef0aee914db78bf -> satisfiable by squizlabs/php_codesniffer[3.0.x-dev] but these
 conflict with your requirements or minimum-stability.
    - Installation request for felixfbecker/language-server ^4.2 -> satisfiable by felixfbecker/language-server[v4.2.0, v4.2.1, v4.2.2, v4.2.3].

```

**Comment by felixfbecker** [comment]
The error message says it, your minimum stability does not allow dev.

**Comment by roxma** [comment]
> The recommended installation method is through Composer. Simply run
> composer require felixfbecker/language-server
> and you will get the latest stable release and all dependencies.

So I'm expecting a stable one.

I tried using dev, but it's somehow not working today

```
  - Installing squizlabs/php_codesniffer (3.0.x-dev b21f9f4)
    Cloning b21f9f43a009f75701560ea9e56bbbb8989bec80
    Failed to download squizlabs/php_codesniffer from source: The process "git clone --no-checkout 'https://github.com/squizlabs/PHP_CodeSniffer.git' '/data/roxma/.local_software/neovim/plugged/nvim-cm-php-language-server/vendor/squizlabs/php_codesniffer' && cd '/data/roxma/.local_software/neovim/plugged/nvim-cm-php-language-server/vendor/squizlabs/php_codesniffer' && git remote add composer 'https://github.com/squizlabs/PHP_CodeSniffer.git' && git fetch composer" exceeded the timeout of 300 seconds.
    Now trying to download from dist
```

**Comment by felixfbecker** [comment]
The language server you get is a stable release, and unit tests assure that. That still means the dependencies might be pre-releases.

**Comment by roxma** [comment]
I believe a release with an unstable requirement is somehow wierd.

Maybe I should find some other workaround to get this working.

**Comment by felixfbecker** [comment]
I disagree. Just because some parts of the dependency are unstable/untested doesn't mean the parts we use are unstable. And our unit tests assure that.
What's the problem with setting `minimum-stability` to `dev`?

**Comment by roxma** [comment]
I set it to `dev`, but I failed to install dependencies:

```
 - Installing squizlabs/php_codesniffer (3.0.x-dev b21f9f4)
    Cloning b21f9f43a009f75701560ea9e56bbbb8989bec80
    Failed to download squizlabs/php_codesniffer from source: The process "git clone --no-checkout 'https://github.com/squizlabs/PHP_CodeSniffer.git' '/data/roxma/.local_software/neovim/plugged/nvim-cm-php-language-server/vendor/squizlabs/php_codesniffer' && cd '/data/roxma/.local_software/neovim/plugged/nvim-cm-php-language-server/vendor/squizlabs/php_codesniffer' && git remote add composer 'https://github.com/squizlabs/PHP_CodeSniffer.git' && git fetch composer" exceeded the timeout of 300 seconds.
    Now trying to download from dist
```

**Comment by felixfbecker** [comment]
Seems like a problem with your git setup? What about the dowload from dist?
I cannot reproduce this locally or in CI.

**Comment by roxma** [comment]
It seems there's something wrong with my cache, the downloaded result is empty. I'll fix it on my own.

**Comment by mityukov** [comment]
> What's the problem with setting minimum-stability to dev?

won't this option affect other (not phpcs/php-language-server) packages in my composer.json? (say, next "update") whould bring all untested components in?

**Comment by felixfbecker** [comment]
@mityukov not if you set `preferStable`

**Comment by mityukov** [comment]
is there an instruction on how to install this server globally? i.e, not to require it again in every project?

I've done like this:
```json
// ~/.composer/composer.json
{
    "require": {
        "laravel/installer": "^1.3",
        "laravel/valet": "^1.1",
        "phpunit/phpunit": "^5.6",
        "squizlabs/php_codesniffer": "3.*@RC",
        "codeception/codeception": "^2.2",
        "felixfbecker/language-server": "@RC"
    }
}
```

then `composer global update` -- now it went through

then `composer global run-script --working-dir=~/.composer/vendor/felixfbecker/language-server parse-stubs` -- now it fails:
```
  [RuntimeException]
  Invalid working directory specified, ~/.composer/vendor/felixfbecker/language-server does not exist.
```
(the dir I've checked, btw, it's there)

**Comment by mityukov** [comment]
P.S.:: I would actually be Ok with firing `composer require squizlabs/php_codesniffer` in each project dir… If it were only  this. But, as it turns out, one also have to add those `minimum-stability` and `preferStable` to each project's composer.js. Thus, I'd like to install it once, globally, if it's possible.

**Comment by felixfbecker** [comment]
Maybe you just have to set `miniumStability` and `preferStable` in `~/.composer/composer.json`.
Do you have a stack trace for that exception?

**Comment by felixfbecker** [comment]
minimumStability: dev and perferStable is widely used in a lot of projects

**Comment by mityukov** [comment]
Ok, I've modified the global composer.json:

```json
{
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "laravel/installer": "^1.3",
        "laravel/valet": "^1.1",
        "phpunit/phpunit": "^5.6",
        "squizlabs/php_codesniffer": "3.*",
        "codeception/codeception": "^2.2"
    }
}
```

now, when I run `composer global require felixfbecker/language-server`, I get the following error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install felixfbecker/language-server v4.3.2
    - Conclusion: don't install felixfbecker/language-server v4.3.1
    - Conclusion: remove felixfbecker/advanced-json-rpc v1.2.10
    - Installation request for felixfbecker/language-server ^4.3 -> satisfiable by felixfbecker/language-server[v4.3.0, v4.3.1, v4.3.2].
    - Conclusion: don't install felixfbecker/advanced-json-rpc v1.2.10
    - felixfbecker/language-server v4.3.0 requires felixfbecker/advanced-json-rpc ^2.0 -> satisfiable by felixfbecker/advanced-json-rpc[v2.0.0, v2.0.1].
    - Can only install one of: felixfbecker/advanced-json-rpc[v2.0.0, v1.2.10].
    - Can only install one of: felixfbecker/advanced-json-rpc[v2.0.1, v1.2.10].
    - Installation request for felixfbecker/advanced-json-rpc (locked at v1.2.10) -> satisfiable by felixfbecker/advanced-json-rpc[v1.2.10].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by mityukov** [comment]
Note: I had (3.*@RC) version of `php_codesniffer` installed globally before and O need to preserve this package. The exact version may be different, but it should be within "3".

**Comment by felixfbecker** [comment]
I think there are still versions locked in your global lockfile.
Please note that for global installation you will probably run into these issues sooner or later if you depend on different versions of code sniffer for example.

**Comment by mityukov** [comment]
Ok. I've removed both `php_codesniffer` and `language-server` from the json file, than removed `composer.lock`, then `composer global update` and `composer global require felixfbecker/language-server`. Now it's installed.

Should I run `php ~/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php` inthe project directory? How do I make Visual Studio Code to connect to it?

**Comment by felixfbecker** [comment]
Why are you not simply installing the PHP IntelliSense extension?

**Comment by mityukov** [comment]
> Why are you not simply installing the PHP IntelliSense extension?

It's been installed, but something's gone wrong. In particular, auto-completion was tooo slow. So, I decided that I had to install `php-language-server` — it's mentioned in the extension description as the back-end on which it runs, but isn't clearly stated whether one should install it or if it comes pre-installed with the extension… So, I don't need the server for using PHP IntelliSense extension, right?

**Comment by felixfbecker** [comment]
The server is bundled with the extension. Look in `~/.vscode/extensions/felixfbecker.vscode-php-intellisense/vendor`

**Comment by mityukov** [comment]
Ok. Is there anything I should run to, kind of, "build symbols cache" (to speed-up it a little)? Now it takes couple of seconds.

**Comment by lgelfan** [comment]
After the last update (1.2.0), this extension too unstable (on Mac anyway).
@mityukov - you could try bmewburn.vscode-intelephense-client as an alternative, it's much faster as well.
