### ISSUE TITLE
SymbolInformation ranges are not accurate

### ISSUE THREAD

**Issue by kaloyan-raev** [felixfbecker/php-language-server#27]
It looks like the `end` position of the ranges is shifted one character left than desired.

The `start` position for class members does not cover the access modifier.

The problem is not visible in VS Code, because it highlights the entire lines covered by the range.

But it is clearly visible in Eclipse Che which highlight the exact range. See the animation below.

![che-php-symbols](https://cloud.githubusercontent.com/assets/468091/18480222/836045bc-79e0-11e6-9764-f67787ee689b.gif)

**Comment by felixfbecker** [comment]
Need to remove the `-1` here https://github.com/felixfbecker/php-language-server/blob/master/src/SymbolFinder.php#L72

@kaloyan-raev would you like to get write access to the repo? I would be fine if you do simple fixes like this directly as long as bigger features are discussed and reviewed on a PR.

**Comment by kaloyan-raev** [comment]
Sure. Thanks!

**Comment by kaloyan-raev** [comment]
PR #28 fixes the end position. The rest should be fixed directly in the PHP Parser.
