### ISSUE TITLE
Intellisense slow on 5k files

### ISSUE THREAD

**Issue by TheColorRed** [felixfbecker/php-language-server#274]
I like the new auto completion tool and, I have a Laravel project that parses the files like so:

> All 5568 PHP files parsed in 253 seconds. 178 MiB allocated.

When I type `$someVar->` it takes about 2 seconds until the suggestions show up.

**Comment by felixfbecker** [comment]
Hmm, completion should be O(n).
This would be interesting to profile.

**Comment by TheColorRed** [comment]
Not sure if you saw this in the release notes of VSCode 1.9, but there is a php parser they are working on

https://github.com/Microsoft/tolerant-php-parser

Might be helpful in some way...

**Comment by felixfbecker** [comment]
Yes, I am aware of it 🙂

**Comment by autoferrit** [comment]
I have a similar issue on a Code igniter project. The autocompletion for class methods doesnt even pop up until I hit `ctrl + space`, then takes a few seconds. If i delete the `->` and do it again, same thing. it doesnt cache the results either. but that is probably a different issue?

**Comment by jens1o** [comment]
@autoferrit afaik the results are not cached, but only the files where we get the results right. I think that's the bottleneck, yes.

**Comment by binarious** [comment]
CTRL + Space takes about 12 seconds for me. I do have 10k PHP files:

> All 10140 PHP files parsed in 16 seconds. 504 MiB allocated.

macOS: 10.13
3,7 GHz Quad-Core
12 GB RAM
PHP: 7.1.10
Extension: 1.5.2
Code: 1.17.2

**Comment by bmax** [comment]
Hi! @felixfbecker willing to work on this -- Do you have any suggestions on the best place to start? Profiling it with XDebug?

**Comment by lndj** [comment]
Has anything help now?

**Comment by binarious** [comment]
I had to switch to [PHP Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client).

**Comment by lndj** [comment]
@binarious is it faster?

**Comment by binarious** [comment]
@lndj It just works for me. Suggestions and method signatures show up instantly on very large projects.

**Comment by madbbb** [comment]
@TheColorRed 
Have you disabled VSCode built-in suggestions? Try to set "php.suggest.basic" to false in settings.

**Comment by koloda** [comment]
Same trouble, about 15 seconds, Yii2 basic project. And i switch to PHP Intelephense.

**Comment by Vercoutere** [comment]
I've also switched to Intelephense for now. Unfortunately Intelephense has it's own set of issues, but I can't live with autocomplete times of over 5 seconds in my project.

I noticed @bmax didn't get any response to his offer to work on this in over 4 months. Can we expect this to be resolved at some point in the near future, or are we out of luck for the time being?

**Comment by bmax** [comment]
@Vercoutere I ended up not putting any time into working on this because there happened to be a couple of other PR's started. I'm not sure why they haven't been merged. I have heard good things about Intelephense though.

**Comment by Ciantic** [comment]
Is the slowness coming from this:

[CompletionProvider.php Lines 246-251](https://github.com/felixfbecker/php-language-server/blob/master/src/CompletionProvider.php#L246-L251)
```php
            foreach ($this->index->getDefinitions() as $fqn => $def) {
                foreach ($prefixes as $prefix) {
                    if (substr($fqn, 0, strlen($prefix)) === $prefix && $def->isMember) {
                        $list->items[] = CompletionItem::fromDefinition($def);
                    }
                }
            }
```

There is no trie index or anything like that, but everything is always looped through and it filters the matching ones in the loop?

**Comment by autoferrit** [comment]
Has there been any updates on fixing this?

**Comment by jens1o** [comment]
@felixfbecker Is it really neccessary to check each definition whether it starts with the prefix? Visual Studio Code is able to filter out, too?

**Comment by nmsmith22389** [comment]
Same issue here... Takes up to 15 seconds on <kbd>ctrl</kbd> + <kbd>space</kbd>. Looking for a solution.

**Comment by ifeltsweet** [comment]
A little discouraging that a few attempts have been made by community to fix this but not enough attention has been given to review it. The **main purpose** of this project is to assist developers in writing code **faster**. Unfortunately it fails at it right now due to these long standing performance problems. @felixfbecker, thank you for all your efforts! It's greatly appreciated, and I'm sorry to complain, but I felt like it's important to say this.

**Comment by felixfbecker** [comment]
Is anyone interested in bringing https://github.com/felixfbecker/php-language-server/pull/599 over the finish line?

**Comment by jens1o** [comment]
I could do that, but only in two weeks(having a trip from tomorrow until next week). Hope someone else can do that earlier. :)

**Comment by cmatzenbach** [comment]
We of the emacs-php community are eagerly awaiting this merge :)  Thanks to everyone who put time into this PR!  It's going to be big for the community

**Comment by jonnycyr** [comment]
Another member of the emacs-php community - just wanted to echo what @cmatzenbach said above! Thank you so much for all of your work! This is gonna make programming in PHP a much better experience in emacs.

**Comment by feedmeastraycat** [comment]
@felixfbecker I saw that the PR seems to be basically done. Is it possible somehow to test @jens1o's branch of php-language-server locally in vscode-php-intellisens?

**Comment by felixfbecker** [comment]
Yes, all you need to do is symlink your local language server repo clone into `~/.vscode/extensions/felixfbecker.php-intellisense-x.x.x/vendor/felixfbecker/language-server`

**Comment by jens1o** [comment]
Thanks for the ping. Forgot to push. This is the current thing I've on. Some tests are failing currently, however. https://github.com/jens1o/php-language-server/commit/f45c44f463bc763384cfab617ed1aecb02a126d8

**Comment by felixfbecker** [comment]
Feel free to open a work-in-progress PR

**Comment by MichaelBelgium** [comment]
> [Info  - 9:39:44 PM] All 5316 PHP files parsed in 8 seconds. 394 MiB allocated.

It's getting parsed for me in less seconds but yeah doesn't change the fact it's slow in auto completing. Can't wait for a fix!

**Comment by felixfbecker** [comment]
@MichaelBelgium if you can't wait, help out :)

**Comment by MichaelBelgium** [comment]
> @MichaelBelgium if you can't wait, help out :)

Is [this ](https://github.com/felixfbecker/php-language-server/pull/599#issuecomment-432758994)what needs to be done?

**Comment by felixfbecker** [comment]
Yes

**Comment by MichaelBelgium** [comment]
> Okay, thanks for taking your time. :)

Anytime :) if it's only a simple merge ... surprised nobody did it me.

**Comment by felixfbecker** [comment]
This is released for VS Code in https://github.com/felixfbecker/vscode-php-intellisense/releases/tag/v2.3.6 

I _think_ this also included these other PRs: https://github.com/felixfbecker/php-language-server/pulls?q=is%3Apr+is%3Aopen+author%3ADeclspeck+sort%3Aupdated-desc

**Comment by midN** [comment]
> I had to switch to [PHP Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client).

Same, the issue is still happening, had to switch, now it's instant..
