### ISSUE TITLE
Intellisense doesn't recognize parameters in methods

### ISSUE THREAD

**Issue by jens1o** [felixfbecker/php-language-server#278]
When having this snippet:
```php
<?php

/**
 * Echoes `Hello World` to the **user**
 * @param   string  $world  Additional text
 * @return void
 */
function hello(string $world): void {
    echo 'Hello World';
}

hello(); // Put your cursor in here
```
I am not able to see `Additional text` (or even that I have to enter a  string) as a popup. 

In the console, I see tons of warnings like this: `INVALID text edit -> must have at least a  #label`

P.S.: I wasn't quite sure where I have to create the issue, please say where I should report issues related to your (great) Intellisense in the future.

**Comment by felixfbecker** [comment]
#18
