### ISSUE TITLE
Throws errors in git diff view of vscode.

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#284]
_From @hworld on February 6, 2017 18:27_

`Message: InvalidArgumentException: Not a valid file URI: inmemory://model/26 in...`

I think it may be because the diff views shown aren't on disk, but instead loaded in memory? To reproduce, just open a repository folder, modify a PHP file, switch into the Git panel, and select the modified file.

_Copied from original issue: felixfbecker/vscode-php-intellisense#68_

**Comment by felixfbecker** [comment]
Can you please look for a stack trace in the output panel or Help > developer tools?

**Comment by hworld** [comment]
Hey, sorry, I can't seem to repro it anymore. It must've been a random issue or something. There was a stack but I didn't grab it at the time. If it happens I'll pull the stack into here. Feel free to close it, though. =]

**Comment by felixfbecker** [comment]
I have the feeling that it was a race condition in VS Code. They should send the document content through the protocol.
