### ISSUE TITLE
RFC: caching parsed result in .vscode/cache/php/

### ISSUE THREAD

**Issue by netroby** [felixfbecker/php-language-server#297]
```

[Info  - 8:01:20 PM] All 2218 PHP files parsed in 34 seconds. 138 MiB allocated.
```

When open a large php project. php will take more and more time to parse files. 
We have a large project with 10K+ files
using vscode open project will very slow. 
so i suggest if we can cache the files parsed on disk?

**Comment by felixfbecker** [comment]
This is already implemented.

**Comment by jens1o** [comment]
I thought its just implemented for libs, but not for normal files, huh?

**Comment by felixfbecker** [comment]
@jens1o that is right, how are we supposed to cache that though? How can we know the files didn't change, for example because a different branch was checked out?

**Comment by jens1o** [comment]
Maybe cache them anyway and check the md5 hash of a file, when you see that file again, you could update the index?

**Comment by felixfbecker** [comment]
The index is not on a per-file basis, that would would go against the purpose of the index. It is per-package. Under what key would you cache it?

**Comment by jens1o** [comment]
uhm... That wasn't a great idea.
