### ISSUE TITLE
Global symbol search

### ISSUE THREAD

**Issue by MadHed** [felixfbecker/php-language-server#30]
First off, great work! I am using your extension during daily development and it works very well.

A feature still missing is global symbol search. (ctrll+p, \#)
I started [working on a feature branch](https://github.com/MadHed/php-language-server/tree/workspace_symbols) and it already does the job.

Parsing the whole php-language-server project takes about 10 seconds on my machine.
The php-cli process takes up about 180MB of ram with all symbol information parsed.

Changes made:
* Added support for client:window/* commands
* Added support for server:workspace/* commands
* Refactored symbol database into own set of classes. (Was in Server/TextDocument before)
* Disabled memory limit
* ProtocolStreamReader was blocking the event loop, made non-blocking
* Find all .php files on startup and start parsing one at a time with Loop/nextTick

To do:
* Fix old tests
* Add new tests
* Reduce memory usage. Most of it is the AST, maybe we can throw it away after parsing,
* Figure out solution for blocking STDIN. The current one is a hack. This is a windows limitation, see [https://bugs.php.net/bug.php?id=34972](https://bugs.php.net/bug.php?id=34972)

Please let me know what you think about it and if you want any changes made. I can then open a pull request.

**Comment by felixfbecker** [comment]
Wow, nice work! I really like the refactor into separate classes. I would encourage you to open the PR right because then I can make comments there (you can still add stuff to the branch)

**Comment by MadHed** [comment]
Created the PR. #31
