### ISSUE TITLE
php.validate setting ignored

### ISSUE THREAD

**Issue by aidantwoods** [felixfbecker/php-language-server#301]
v1.1.2

VS Code Version 1.9.1, macOS 10.12.3.

Upon setting `"php.validate.run": "onSave"` (which is the default anyway), PHP IntelliSense will validate while typing.

Even upon setting `"php.validate.enable": false`, PHP IntelliSense will still validate while typing.

**Comment by felixfbecker** [comment]
That is the built-in validation of VS Code.

**Comment by aidantwoods** [comment]
Setting is only ignored *with* PHP IntelliSense installed

**Comment by felixfbecker** [comment]
`php.validate` controls the _built-in_ validation of VS Code.
It will not affect the validation of the PHP language server.
What is the behavior you expect?

**Comment by aidantwoods** [comment]
PHP IntelliSense honours the setting? 

i.e. doesn't attempt to validate code while typing (only validate on save) – personally I find it distracting when validation occurs before I've finished typing.

I understand that the setting is for the built in validator, but the setting being ignored is *caused* by installing PHP IntelliSense, so I'm assuming it's either a bug or a feature (I can't find any documentation on the latter behaviour).

**Comment by felixfbecker** [comment]
What you are seeing is probably PHP IntelliSense's own validation, which can not be configured.
PHP IntelliSense cannot influence the built-in validation in any way.

**Comment by aidantwoods** [comment]
Can I change this to a feature request to honour the user defined setting?

**Comment by felixfbecker** [comment]
It would have to be a new setting because as I said that setting is VS Code's own setting. But yeah, just open a new issue

**Comment by aidantwoods** [comment]
Awesome, thanks :)
