### ISSUE TITLE
Completion does not work

### ISSUE THREAD

**Issue by mjoksa** [felixfbecker/php-language-server#303]
Last time I tried to use PHP completion U stated that i have to wait on new VS Code that will have setting value for this purpose. Now, I've updated VS Code to latest version, changed settings as stated at https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense, but I still do not have completion on PHP objects like mysqli.

There are no errors either in developer tools or in PHP language server output window - I've attached some pics to illustrate this. Also, on one of attached pics U can see that local PHP files are parsed by language server, but 0 (zero) packages were parsed (do these packages contains definitions on PHP objects?).

Extension(s) that U made helped me a lot last couple of week during my small trip to PHP world (I am NET developer :) and I am used to all VS goodies) so keep up the good work (and do not hold against me if I missed something obvious here)

![vs code settings](https://cloud.githubusercontent.com/assets/14345655/23016775/0a555b44-f438-11e6-9ccd-74a46d0156f6.png)
![vs code](https://cloud.githubusercontent.com/assets/14345655/23016776/0ae1deac-f438-11e6-851b-670cb3e73f50.png)

**Comment by felixfbecker** [comment]
The actual code I can copy+paste would be more helpful than screenshots ;)

**Comment by mjoksa** [comment]
I am not sure about that code :) but here is one line from that screenshot
`$mysqli = new mysqli($cfg['serverName'], $cfg['serverUsername'], $cfg['serverPassword'], $cfg['databaseName']);`
As shown on screenshot, when I hovered over mysqli I expected to more data in that info window, similar to the gifs on extension site.
Let me know if u need more info from me

**Comment by felixfbecker** [comment]
So what exactly is not working for you?

![image](https://cloud.githubusercontent.com/assets/10532611/23017449/9914d2fe-f43a-11e6-9615-62ee754ab588.png)

**Comment by mjoksa** [comment]
Now, as far as I can tell, only thing that do not work for me is that tool tip when I hover over mysqli for example (shown on my pic above). With this I can live, so please close this issue and I wont be bothering U anymore, cause it seems that I expect VS Code to behave same as regular VS :)

Cheers and thanks for all help

**Comment by felixfbecker** [comment]
But what hover tooltip are you expecting? Your screenshot shows a correct hover tooltip?

**Comment by mjoksa** [comment]
That is where i was wrong. I expected hover tooltip with more info, like I saw on gifs on extension site, but now, after this little talk with U, I think that I got it wrong and in essence there is no problem.

Sorry for the inconvenience

**Comment by felixfbecker** [comment]
The tooltips in the readme don't show more: https://github.com/felixfbecker/php-language-server#hover
