### ISSUE TITLE
AutoComplete does not works with Wordpress or custom functions or class methods.

### ISSUE THREAD

**Issue by codewp** [felixfbecker/php-language-server#309]
Hi, and thank you for this project.

Is it possible to make this extension works with Wordpress functions and class methods or custom functions and custom class methods?

Because when I use `$this->` in my own custom class it can not show me class methods, also it can not shows method parameters.

Best Regards.

**Comment by felixfbecker** [comment]
Please clarify. Autocomplete does work for custom functions and class methods. What exact code does not give you expected suggestions?

**Comment by codewp** [comment]
Please look at these examples.

For Wordpress you can test it with `wp_enqueue_script` function of Wordpress.

![autocomplete-test-1](https://cloud.githubusercontent.com/assets/10684451/23106203/a2053f30-f6ff-11e6-9c36-420d88c705e8.PNG)
![autocomplete-test-2](https://cloud.githubusercontent.com/assets/10684451/23106251/ab0fd7f2-f6ff-11e6-9932-53f1eba3365e.PNG)
![autocomplete-test-3](https://cloud.githubusercontent.com/assets/10684451/23106252/ab153d82-f6ff-11e6-8887-e49ccbdf4666.PNG)
![autocomplete-test-4](https://cloud.githubusercontent.com/assets/10684451/23106253/ab16e7fe-f6ff-11e6-854f-7d4073314c3d.PNG)
![autocomplete-test-5](https://cloud.githubusercontent.com/assets/10684451/23106254/ab1e6ef2-f6ff-11e6-938a-0836ed458833.PNG)

As you can see for str_replace autocomplete works well, but for test class methods it suggests unrelated methods. Also it can't show parameters information of custom functions `write` like `str_replace`. example.

In image 2 after `$this->` it suggests unrelated functions too.

**Comment by felixfbecker** [comment]
That is VS Code's built-in autocompletion, which you should disable as explained in the readme
In the future please paste the code instead of screenshots ;)

**Comment by codewp** [comment]
I used `ctrl+space` to showing that autocomplete.
I used `"editor.quickSuggestions": false` to disabling VS Code built in autocomplete but it can't help.
So please let me know can this extension works with custom codes like above and Wordpress functions?

Best Regards.

**Comment by felixfbecker** [comment]
https://github.com/felixfbecker/vscode-php-intellisense#installation

**Comment by codewp** [comment]
Thanks.

When I disabled VS Code built in suggestion it can not shows php functions parameters information too like in image 1, so it seems that, that feature was built in feature of VS Code and does not relates to this extension.

Do you have any plan for supporting this feature `image 1` in this extension for custom codes and Wordpress?

**Comment by felixfbecker** [comment]
That is signature help, which is not supported atm #18
