### ISSUE TITLE
Hover shows just the very first doc comment paragraph

### ISSUE THREAD

**Issue by jens1o** [felixfbecker/php-language-server#312]
![image](https://cloud.githubusercontent.com/assets/11234139/23302206/0cf648ac-fa8e-11e6-9a9a-0c8510c44fa2.png)
![image](https://cloud.githubusercontent.com/assets/11234139/23302212/16920e50-fa8e-11e6-9783-184735ab5fea.png)
File: https://github.com/slimphp/Slim/blob/3.x/Slim/App.php

**Comment by felixfbecker** [comment]
This is as designed. Easy to fix, just needs to concatenate `getSummary()` with `getDescription()`
