### ISSUE TITLE
Microsoft/tolerant-php-parser adoption

### ISSUE THREAD

**Issue by mousetraps** [felixfbecker/php-language-server#323]
As discussed in https://github.com/Microsoft/tolerant-php-parser/issues/36#issuecomment-274563749, key benefits include:
* graceful error handling
* performance + memory usage
* fully-representative tree

I'm currently working with Felix to put together a functional prototype. This would be a pretty major change, there may be some temporary regressions, and we will certainly need to make some improvements to the parser before it's ready for primetime. 

This issue acts as a catch-all to track progress on that work.

<hr/>

## Current status:
**_Working branch:_**
* _Language server: https://github.com/felixfbecker/php-language-server/compare/master...mousetraps:tolerant_
* _Parser: https://github.com/Microsoft/tolerant-php-parser/compare/master...mousetraps:lang-server_

### Features
- [x] error diagnostics
- [x] find all symbols
- [x] find all symbols in workspace
- [x] **_[not impacted]_** format code
- [x] go to definition
- [x] find all references
- [x] hover
- [ ] completion

### Known regressions
* Error diagnostics produced by the parser are not currently "strict" because we parse things more loosely in order to provide error tolerance, so we won't get diagnostics for everything until we add relevant post-parse checks (this will happen on the parser side).
* The new parser has higher granularity when it comes to Node position info, which results in slightly different (but still correct) position locations in some cases (for instance for a function call `hello(/*cursor*/)`, go-to-definition at the denoted cursor position will not yield a result (but will yield a result if the function call name is selected)
* The new parser does not have pretty-printing yet, so the definition lines produced are exactly what the user has typed in (including whitespace), rather than a pretty-printed version.
* Magic constants are treated like normal constants and will therefore appear in "find all references" results. Their fqsen will be resolved to their namespace value if one is defined (even though this is not actually legal).
* true, false, and null are not included in find all references results (which is probably the expected behavior anyways)
* variables used within template strings are not currently included in find all references results
* _TODO_

### Related parser issues
Parser work for this next milestone is [tracked here](https://github.com/Microsoft/tolerant-php-parser/milestone/2). Any additional issues that should be prioritized?

**Comment by razvanphp** [comment]
Sorry to stress on this, but please keep #134 (PHPDoc) & #271 (dependency injection containers) on the feature list, without them, many of the real-world PHP applications are really hard for daily work, my colleagues (with PhpStorm) are still laughing at me when I can't CMD+click while debugging.

**Comment by felixfbecker** [comment]
@razvanphp The adoption will ease the implementation of these features, it is something I talked about with Sara :)

**Comment by jens1o** [comment]
any news on this?

**Comment by jens1o** [comment]
Nice that this will be handled in the next release!
