### ISSUE TITLE
Warnings given for code inside comments

### ISSUE THREAD

**Issue by mberneis** [felixfbecker/php-language-server#327]
In the PROBLEMS view panel I am getting a lot of PHP warnings as
`[php] “\(int)” is not a valid Fqsen` and
` 'Attempted to resolve "0" but it appears to be empty'`

However the actual code which triggers the warning is inside a comment
```
	/**
	 * Initialize code.
	 * @param $spec (array) array of ECC specification
	 * @return 0 in case of success, -1 in case of error
	 */
```

So these warnings should not be displayed

**Comment by felixfbecker** [comment]
Because this is invalid PHPDoc. `@return` needs to declare a return type. The LS needs to parse docblocks, so reporting parsing errors is expected behavior.
