### ISSUE TITLE
files.exclude setting being ignored

### ISSUE THREAD

**Issue by johnbillion** [felixfbecker/php-language-server#335]
In my `settings.json` file in VS Code, I have `"**/build": true,"` included in the `files.exclude` setting. This works as expected in VS Code's user interface, but the PHP language server appears to be ignoring this setting.

I'm currently debugging the following error:

`The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.`

In the PHP language server output I see the following:

`Parsing file:///sites/wp/build/wp-content/plugins/publishing-checklist/tests/test-publishing-checklist.php
[Error - 9:57:51 AM] Connection to server got closed. Server will not be restarted.`

As you can see, the file in question is in the `build` directory and therefore should be ignored by the PHP language server.

Is there a reason it isn't? If so, is there a way to exclude files/directories from being parsed by the PHP language server?

**Comment by diego-vieira** [comment]
Since this is just the server, it's up to the extension to pass the parameters.
See https://github.com/felixfbecker/php-language-server/issues/159
