### ISSUE TITLE
error Code: -32603 when reformatting file

### ISSUE THREAD

**Issue by Merange** [felixfbecker/php-language-server#342]
Hello,

I just install my old project in Visual Studio code and I try to reformat my code (plenty of tabs in place of spaces, ...) and I have this error code

here is the stack trace

_[Error - 07:12:26] Request textDocument/formatting failed.
  Message: Exception: Unable to format file in C:\Users\Moi\.vscode\extensions\felixfbecker.php-intellisense-1.1.4\vendor\felixfbecker\language-server\src\Formatter.php:52
Stack trace:
#0 C:\Users\Moi\.vscode\extensions\felixfbecker.php-intellisense-1.1.4\vendor\felixfbecker\language-server\src\PhpDocument.php(233): LanguageServer\Formatter::format('<?php\t\n\n\terror_...', 'file:///d:/Dev/...')
#1 C:\Users\Moi\.vscode\extensions\felixfbecker.php-intellisense-1.1.4\vendor\felixfbecker\language-server\src\Server\TextDocument.php(179): LanguageServer\PhpDocument->getFormattedText()
#2 C:\Users\Moi\.vscode\extensions\felixfbecker.php-intellisense-1.1.4\vendor\sabre\event\lib\Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#3 C:\Users\Moi\.vscode\extensions\felixfbecker.php-intellisense-1.1.4\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#4 C:\Users\Moi\.vscode\extensions\felixfbecker.php-intellisense-1.1.4\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#5 C:\Users\Moi\.vscode\extensions\felixfbecker.php-intellisense-1.1.4\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#6 C:\Users\Moi\.vscode\extensions\felixfbecker.php-intellisense-1.1.4\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#7 C:\Users\Moi\.vscode\extensions\felixfbecker.php-intellisense-1.1.4\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#8 {main}
  Code: -32603_ 

Please ask me if you need some oter information

**Comment by felixfbecker** [comment]
https://github.com/felixfbecker/php-language-server/issues/296
https://github.com/felixfbecker/php-language-server/issues/293
