### ISSUE TITLE
Code formating does not respect editor.tabSize

### ISSUE THREAD

**Issue by albertowd** [felixfbecker/php-language-server#343]
Hello, lately I'm using tab as 3 spaces but when the code is formatted the extension is using the default 4 spaces tab.
Btw, excellent extension!

**Comment by felixfbecker** [comment]
Formatting is currently done by PHP CodeSniffer. You can configure it with an XML file.

**Comment by albertowd** [comment]
My mistake, I just realized the VC let you choose if you want to use de default, configured or a custom tab size in the status bar. But I don't know how mine changed to force 4 spaces (not the default settings), maybe some shorcut that I don't know?
Thanks for the reply.

**Comment by MartinMa** [comment]
See also [[FEATURE] Respect identation settings when doing Format Document #93](https://github.com/felixfbecker/vscode-php-intellisense/issues/93). It's a WON'T FIX.
