### ISSUE TITLE
Vscode Vendor Class Definitions

### ISSUE THREAD

**Issue by zodiark23** [felixfbecker/php-language-server#349]
[x] Bug Report
[  ] Feature Request

Version : **1.1.5**

Class definitions works well if the class is defined in the current workspace. Methods are shown and other descriptions. But won't fetch class definitions on vendor frameworks.

I do not getting any suggestions or code completion from the classes in vendor folder.

Aside from that intellisense works perfectly.

**Comment by mirao** [comment]
I have similar issue in [Codeception](http://codeception.com) framework, somehow related to namespaces.
E.g. in [page object](http://codeception.com/docs/06-ReusingTestCode#PageObjects) class **I can** see definition or hint for local stuff (such as `use Page\headers\Headers;`), but **I cannot** see hints for vendor stuff (such as `use \Facebook\WebDriver\WebDriverBy;` or `class Login extends \Codeception\Module`).

**Comment by felixfbecker** [comment]
It is not clear to me how I am supposed to reproduce, please provide a clear reproduction.

**Comment by zodiark23** [comment]
Hi felix, I replicate the procedure for my project. But I think other frameworks that rely on `vendor` is also not working. Here is my project. The `app` class hover is working with its description. **But** the new *Application* doesn't give any completion.


If you can't replicate my project try starting a laravel. Same thing happens after composer install the laravel.

![image](https://cloud.githubusercontent.com/assets/18022149/25075844/fe19101a-234d-11e7-8fa5-5d078ee495dc.png)

This is the sample of what was happening. local defined works well. But on the `vendor` folder it doesn't pick up class *definitions* and *methods.*

Sample Folder structure

![folderstruc](https://cloud.githubusercontent.com/assets/18022149/25075880/8923ca6a-234e-11e7-89b5-c402b4e53871.PNG)


Steps to replicate.

1. Init *composer* and require this package.
````php
"require": {
        "r-forge/r-forge":"dev-master"
    }
````

2. on cli run `composer install` then `composer dump-autoload -o`.

> This is the sample code on the index.php

````php
<?php namespace Portfolio;

require_once __DIR__."/vendor/autoload.php";

use RForge\Application;
use RForge\Settings\Config;

Config::setConnection([
    "host"=>"127.0.0.1",
    "user"=>"root",
    "pass"=>"",
    "charset"=>"utf8",
    "driver"=>"mysql"
]);


/**
 * This app is testing intellisense
 */
class App{

}

$testApp = new App(); // <--- MOUSE HOVER SHOW'S THE CLASS DESCRIPTION


$myApp = new Application("Portfolio"); // <--- DOESN'T SHOW ANYTHING
$myApp->setTables('Models\\');
$myApp->database = "bld";
$myApp->start();

````


Thanks for making this extension!!!

**Comment by felixfbecker** [comment]
I can't find `r-forge/r-forge` on packagist.org, could you explain how to install?
https://packagist.org/search/?q=r-forge%2Fr-forge

**Comment by zodiark23** [comment]
here is the link https://packagist.org/packages/r-forge/r-forge. But i think even on any library on vendor it wont work.

**Comment by zodiark23** [comment]
Hi @felixfbecker , i reinstalled all vscode and new integration of the plugin. Now it detects the classes from vendor folder. I will close this issue now. Thanks !!
