### ISSUE TITLE
Ubuntu on Bash adaption

### ISSUE THREAD

**Issue by erdemece** [felixfbecker/php-language-server#356]
Hi,

Thank you for an awesome extension. 

With new Windows 10 Creator Update I can call php from windows cmd by typing bash -C "php --version"
Bash is in the environment path but not php along as we install windows php binaries.

How can I implement this into php.executablePath settings are can you enable this feature?

Thanks.

**Comment by felixfbecker** [comment]
This is the domain of the VS Code extension. It would need an `args` setting.

**Comment by erdemece** [comment]
I don't understand what you just said.

**Comment by jens1o** [comment]
He means that this is the job of vscode and not of this extension/language server, since this just uses the setting. You should create a suggestion at vscode's repo and wait what they'll say.

**Comment by felixfbecker** [comment]
No, it just needs to implemented in vscode-php-intellisense.

**Comment by jens1o** [comment]
Ah, I'd overread `extension`, sorry.
