### ISSUE TITLE
Is there a change log ?

### ISSUE THREAD

**Issue by Hexodus** [felixfbecker/php-language-server#358]
From time to time I see an update but unfortunately the changlog tab in VSC is empty. Is there a change log somewhere else?

**Comment by felixfbecker** [comment]
Is the commit log sufficient? https://github.com/felixfbecker/php-language-server/commits/master

I can't fill the VS Code changelog tab because the changes happen in this repo, not in the extension repo.

**Comment by Hexodus** [comment]
Thank you. Yes this is helpful. Maybe github releases would be a good addition to be able to track the progress?

[https://help.github.com/articles/creating-releases/](url)

**Comment by felixfbecker** [comment]
I used to do it, but it was just a lot of work for basically 1:1 copying the commit messages to a change summary.
