### ISSUE TITLE
No tooltip info

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#369]
_From @regs01 on April 26, 2017 12:48_

Won't show tooltip when you open a function with function description and variations.

_Copied from original issue: felixfbecker/vscode-php-intellisense#115_

**Comment by felixfbecker** [comment]
Please provide a code snippet to reproduce.

**Comment by regs01** [comment]
those kind of tooltips. this is another extension. not php intellisense.
http://imgur.com/l7WnKdL

**Comment by felixfbecker** [comment]
Duplicate of #18
