### ISSUE TITLE
PHP 7.1 Features missing

### ISSUE THREAD

**Issue by NicoAiko** [felixfbecker/php-language-server#370]
As of now, new features introduced in PHP 7.1 are marked as errors.
Here's a list of the new features in PHP 7.1. http://php.net/manual/de/migration71.new-features.php

Would be nice to see them in the future.

For example:

![image](https://cloud.githubusercontent.com/assets/22343587/25558616/9bde0fea-2d2a-11e7-8aa7-0633ff432143.png)

**Comment by jens1o** [comment]
I don't get this error. Silly question: What's your php version you use locally?

**Comment by felixfbecker** [comment]
There is no "plain code validation", these are errors reported by the parser

**Comment by jens1o** [comment]
I'm curious:
![image](https://cloud.githubusercontent.com/assets/11234139/25559021/54eb39ce-2d33-11e7-9e97-cc4fbdd6fbff.png)
![image](https://cloud.githubusercontent.com/assets/11234139/25559028/617d7012-2d33-11e7-8a91-db5e06665352.png)

**Comment by jens1o** [comment]
You say php 7.1 features could only be parsed by php 7.1, didn't you?

**Comment by NicoAiko** [comment]
It seems... this problem wasn't a problem with the extension.
It seems some backup reset my PATH back to php7.0.
Sorry about that.

Can be closed...
