### ISSUE TITLE
Can't get parameter information when calling class methods or global functions

### ISSUE THREAD

**Issue by fyndor** [felixfbecker/php-language-server#373]
If I try and define the parameters of a class method or a function and write a description of them I do not get information about which parameter I am on or what its description is.  I try and hit CTRL+SHIFT+SPACE when my cursor is inside the function and nothing appears.  Am I doing something wrong, is this not implemented, or is it a bug?  Below is an example of what I am doing.  I expect when my cursor is inside method calls in the last two statements to be able to see the parameter information about the parameter my cursor is on.

```
<?php
    /**
     * Does stuff
     *
     * @param string $stuff Does stuff with this parameter
     */
    function Stuff(string $stuff) {

    }
    /**
     * MyDbClient - A class for connecting to a database  
     */
    class MyDbClient
    {
        /**
         * Executes a sql statement
         *
         * @param string $sql SQL statement to execute
         */
        function query(string $sql) {
            //Code goes here
        }
    }    

    $test = new MyDbClient();
    $test->query("select * from mytable");
    Stuff();
?>
```

**Comment by jens1o** [comment]
This is currently not supported. See #18
