### ISSUE TITLE
hello vs code The language server needs at least PHP 7 installed. Version found: 5.6.26

### ISSUE THREAD

**Issue by t67132** [felixfbecker/php-language-server#376]
settings.json
"php.validate.executablePath": "C:\\\AppServ\\\php7\\\php.exe",
// "php.validate.executablePath": "C://AppServ//php7//php.exe",
"php.suggest.basic": false
The language server needs at least PHP 7 installed. Version found: 5.6.26
Why? Please help

**Comment by felixfbecker** [comment]
`"C:\AppServ\php7\php.exe"` is not valid JSON and VS Code should show you an error for that. You need to escape backslashes.

**Comment by t67132** [comment]
hello !! felixfbecker 
Thanks for the reply
Error!! install Results
"php.validate.executablePath": "C:\\AppServ\\php7\\php.exe",
// "php.validate.executablePath": "C://AppServ//php7//php.exe",
Which part of the problem??

**Comment by felixfbecker** [comment]
You need to escape them, not change them to double forward slashes.
`"C:\\AppServ\\php7\\php.exe"`

**Comment by t67132** [comment]
![image](https://cloud.githubusercontent.com/assets/20123094/26193206/211de6ec-3be7-11e7-89e2-61f61ce9674c.png)

**Comment by felixfbecker** [comment]
`php.validate.executablePath` is the wrong setting. It's `php.executablePath`.
https://github.com/felixfbecker/vscode-php-intellisense#installation

**Comment by t67132** [comment]
Thanks for the help
