### ISSUE TITLE
requirements could not be resolved / 4.4.1 / php_codesniffer 3.0.0RC3

### ISSUE THREAD

**Issue by kmindi** [felixfbecker/php-language-server#377]
Problem 1
    - felixfbecker/language-server v4.4.1 requires squizlabs/php_codesniffer 3.0.0RC3 -> satisfiable by squizlabs/php_codesniffer[3.0.0RC3] but these conflict with your requirements or minimum-stability.
    - felixfbecker/language-server v4.4.0 requires squizlabs/php_codesniffer 3.0.0RC3 -> satisfiable by squizlabs/php_codesniffer[3.0.0RC3] but these conflict with your requirements or minimum-stability.
    - Installation request for felixfbecker/language-server ^4.4 -> satisfiable by felixfbecker/language-server[v4.4.0, v4.4.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by felixfbecker** [comment]
The error message is pretty clear - the dependencies could be resolved, but _conflict with your requirements or minimum-stability_. You need to lower you minium-stability.

This is the second result if google your error message: http://webtips.krajee.com/setting-composer-minimum-stability-application/

**Comment by kmindi** [comment]
Ok I have to be more specific, the mentioned error message appears after a clean install of composer (without setting anything) and using the provided *install* command (from this projects readme)
> `composer require felixfbecker/language-server`

and executing that without creating anything else with composer.

**Comment by felixfbecker** [comment]
Did you try one of the options in the linked blog post?

**Comment by kmindi** [comment]
If I execute 

`composer config minimum-stability dev` and then use `composer require felixfbecker/language-server` it works, but I don't see what the consequences of this setting now are.
Anyway it would be good if the provided installation command would work out of the box.

**Comment by felixfbecker** [comment]
The consequences are that composer will now install dependencies of a lower stability. I would recommend you to set `preferStable: true` as explained in the blog post (3), that way it will still use stable versions if available. CodeSniffer will go away soon anyway.
