### ISSUE TITLE
Don't keep content in memory in addition to AST

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#397]
@roblourens I see `SourceFileNode` has a `content` property now. But we also store `PhpDocument->content`, which sounds like duplicate memory usage. Can we just remove the `content` property and always rely on the `SourceFileNode`'s `content` property? Or can there be a case where parsing fails so hard the `SourceFileNode` is `null`?

**Comment by felixfbecker** [comment]
ping @roblourens ?

**Comment by roblourens** [comment]
Good point, SourceFileNode will never be null, so we should get rid of PhpDocument's `content`.
