### ISSUE TITLE
Globally defined variables should be available

### ISSUE THREAD

**Issue by scriptcoded** [felixfbecker/php-language-server#403]
Within a scope, if a variable is marked as global, autocompletion should be available for that variable.

`$global` should autocomplete within the function even though the file in which it is defined is not included.

    function test() {
      global $config;
    }

**Comment by felixfbecker** [comment]
Do you have an `include`/`require` statement at the top of the file? Then https://github.com/felixfbecker/php-language-server/issues/379 would solve it

**Comment by scriptcoded** [comment]
No I have not, since it is within a class. Although, by marking it as `global`, we are after all saying that it should be available. Right?

**Comment by felixfbecker** [comment]
But that doesn't tell the language server where to find it

**Comment by scriptcoded** [comment]
Ah, okey. Makes sense then. I assume this should be closed then.
