### ISSUE TITLE
Testing and drive to publish extension with php-language-server using the new parser

### ISSUE THREAD

**Issue by roblourens** [felixfbecker/php-language-server#404]
Where can we post a vsix for testing, where it will get attention and some usage? 

---

Here are the issues that are regressions vs the old parser. Currently, a total of 6 issues:

https://github.com/felixfbecker/php-language-server/issues?q=is%3Aissue+is%3Aopen+label%3ARegression

https://github.com/Microsoft/tolerant-php-parser/issues?q=is%3Aissue+is%3Aopen+label%3Alang-server-regression

I'm not sure whether all of them are blockers?

**Comment by felixfbecker** [comment]
I would do pre-releases here: https://github.com/felixfbecker/vscode-php-intellisense/releases and tweet it

**Comment by jens1o** [comment]
Could you ping me up when there's a new one?

**Comment by felixfbecker** [comment]
I would recommend you https://sibbell.com/

**Comment by jens1o** [comment]
Ah, thanks. Set up. :)

**Comment by felixfbecker** [comment]
@roblourens I am looking into better automatic release of the extension. I have automatic release in CI, but to trigger it I have to push a new tag. It would be possible to generate a vsix for every release and publish it to the GitHub releases page. I could run a Travis cron job every day to release, but it would need to bump the version in package.json like semantic-release does. The hard part is finding out whether the language server got a new release or not, maybe Composer has a command for this.

**Comment by staabm** [comment]
https://developer.github.com/v3/activity/events/types/#releaseevent

**Comment by felixfbecker** [comment]
That's great, but can it trigger a Travis build?

**Comment by staabm** [comment]
https://docs.travis-ci.com/user/triggering-builds/ ;-)

**Comment by felixfbecker** [comment]
And where would that be hosted? Doesn't look like a viable solution to me

**Comment by roblourens** [comment]
I don't know of a better way to automate it - seems like pushing a tag to release when there's a new version we want to test would work for now. Hopefully we won't be in prerelease mode for too long?

What do we need to do to get a new release of the language server?

**Comment by roblourens** [comment]
Also, can you assign this issue to me? We've linked it from the iteration plan to track the task to update the extension with the new parser.

**Comment by felixfbecker** [comment]
I setup Travis to automatically upload vsix packages for every release to the GitHub releases page.
In theory we don't have to do a prerelease at all if it turns out to be pretty stable. Do you think there are any major thing we should fix before going public to prevent issue spam?

**Comment by roblourens** [comment]
The only things I'm aware of are the issues in the linked queries above. I don't even know if they are necessarily blockers - template string support (for find all refs including variables in template strings, etc) is probably the most annoying but I don't know that it would destroy anyone's workflow.

If you just want to go ahead with it and see what happens, I'd be 👍 for that. Or we can try to get one prerelease out there just to see what happens. Up to you.

**Comment by roblourens** [comment]
@felixfbecker Can we get a prerelease out? Waiting for anything?

**Comment by jrobeson** [comment]
this did happen already didn't it?
