### ISSUE TITLE
Method call whose target is field in parent class couldn't be resolved.

### ISSUE THREAD

**Issue by zfy0701** [felixfbecker/php-language-server#407]
Take following code as example, it looks `$this->f->foo();` works in base class, but doesn't work in sub class.

It looks like the problem is we alway try to construct a fqn before query, so for second one, we might have constructed a bad fqn in the first place.  Is this a intended behavior?

```php
<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

Class C {
	public function foo() {

	}
}

class A {
	/**
	* @var C
	*/
	public $f;

	public function __construct($c) {
		$this->f = $c;
	}

	public function test() {
		$this->f->foo(); // foo can be resolve
	}
}

class B extends A {
	public function main() {
		$this->f->foo(); // foo couldn't be resolve
	}
}
```

**Comment by felixfbecker** [comment]
What exactly doesn't work? Completion or go to definition?

**Comment by zfy0701** [comment]
go to defintion, you could paste this code to vs code, and try to click the two "foo" reference, the first one could correctly jump to definition but the second one can't.

**Comment by autoferrit** [comment]
Same happens in my case. Example

```php
class Document {
    protected static something($param)
    {
        return array(...);
    }
}

class Pdf extends Document {
    protected static something($param)
    {
        $param[] = 'newitem';
        $parent = parent::something($param);
        return $parent;
    }
}

```

for me, when I go to  definition on `parent::something(...)` it does not know what it is. even clicking just on the `parent` part does not go to the parent class.

**Comment by felixfbecker** [comment]
@autoferrit that likely is a different issue related to the `parent` keyword.
