### ISSUE TITLE
PHP7.1 Private class const triggers syntax error

### ISSUE THREAD

**Issue by erwinw** [felixfbecker/php-language-server#409]
Hi,

I'm getting a syntax error when using [private class constants](http://php.net/manual/en/language.oop5.constants.php#language.oop5.basic.class.this) in PHP 7.1:
`'syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)'`

The code in question is: 
```PHP
class TestDbServiceProvider extends ServiceProvider
{
  private const KEYS = ['DB_HOST', 'DB_DATABASE', 'DB_USERNAME', 'DB_PASSWORD'];
...
}
```

Am I doing anything wrong?

Cheers,
Erwin

**Comment by felixfbecker** [comment]
What PHP version are you running?

**Comment by erwinw** [comment]
PHP 7.1.5.

**Comment by felixfbecker** [comment]
Are you absolutely sure? I cannot reproduce this, the above parses fine for me.

**Comment by erwinw** [comment]
That would be v4.4.1, as far as I can deduce from `~/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/composer.lock`.

**Comment by felixfbecker** [comment]
Can't reproduce on master.

**Comment by erwinw** [comment]
Damned, I'm sorry; this turned out to be caused by a hard-coded (and incorrect) php executablePath setting. Maybe echoing the php version in the output is a good idea? Not sure how frequently that info is useful?

Anyway, my apologies for the time wasted, @felixfbecker.

**Comment by felixfbecker** [comment]
That's actually a great idea. Would appreciate a PR.
