### ISSUE TITLE
php language server is crashed in vscode version 1.13.1

### ISSUE THREAD

**Issue by andares** [felixfbecker/php-language-server#422]
VSCode Version: 1.13.1
OS Version: Ubuntu 16.04 LTS @ Gnome
PHP Version: 7.1.2

```
Linux desktop16 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
➜  ~ php -v
PHP 7.1.2 (cli) (built: Mar 14 2017 11:11:05) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.2, Copyright (c) 1999-2017, by Zend Technologies
```

Steps to Reproduce:
1. update to version 1.13.1
2. open a php project
3. output:
[Info - 12:22:13 PM] Connection to server got closed. Server will restart.
[Info - 12:22:14] PM Connection to server got closed. Server will restart.
[Info - 12:22:15 PM] Connection to server got closed. Server will restart.
[Info - 12:22:22 PM] Connection to server got closed. Server will restart.
[Error - 12:22:23 PM] Connection to server got closed. Server will not be restarted.

now it can not search for php symbol.

I have not upgrade php within three month, just upgrade vscode.

**Comment by andares** [comment]
should I remove ~/.config/Code dir to reset cache file & reinstall all extensions? I had repeatedly reinstall vscode 1.13.1 & 1.13.0, it always crash.

**Comment by felixfbecker** [comment]
"open a php project" is not enough for me to reproduce, can you narrow it down to a specific set of files and share them? Also try upgrading PHP, the newest version contains bug fixes

**Comment by ADmad** [comment]
@andares Since you are using PHP 7.1.2. this is probably the same as #418. There's a bug in this particular PHP version. Upgrading PHP will most likely fix your problem.

**Comment by andares** [comment]
OK, I try to upgrade php.

**Comment by andares** [comment]
I upgrade php to version 7.1.6, problem is resolved. thanks all :-)
