### ISSUE TITLE
Remove Docker images

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#427]
Deploying the Docker images makes us require sudo and Docker in CI, which increases build time. Is anyone using them? Otherwise I would remove them

**Comment by jens1o** [comment]
I don't use them.

**Comment by cweagans** [comment]
You shouldn't have to build these images in your CI process manually. Docker Hub can build it for you.

**Comment by felixfbecker** [comment]
I didn't know that - can you explain how?

**Comment by cweagans** [comment]
https://docs.docker.com/docker-hub/builds/

**Comment by cweagans** [comment]
;)

**Comment by felixfbecker** [comment]
Wouldn't that require me to add _build_ dependencies to the Docker images that end up there at runtime? E.g. I'd have to add Composer to the container just to install dependencies

**Comment by cweagans** [comment]
Probably, but that's okay IMO. Just base the langserver image on the official composer image and call it a day. Disk space is cheap, and even a slightly larger image is preferable to no image at all.

**Comment by felixfbecker** [comment]
I'll just keep them around
