### ISSUE TITLE
Syntax errors sometimes get "stuck"

### ISSUE THREAD

**Issue by filliph** [felixfbecker/php-language-server#428]
https://i.imgur.com/wacZGc9.png

It is not recognising that I typed an expression, and also the **php** process is running rampant, using 100% CPU and causing my fans to go into overdrive. This happens seemingly randomly, and has happened since I first installed this extension around the start of April.

The only fix is to completely close VSCode and Force Quit the **php** process, then restarting VSCode.

Unfortunately all my attempts at reliably reproducing this have failed, it seems entirely random when it decides to not realise there isn't actually a syntax error.

**Comment by jens1o** [comment]
@felixfbecker Do you think there's a infinite loop in the tolerant php parser that does not respond anymore?

**Comment by roblourens** [comment]
> happened since I first installed this extension around the start of April.

 Doesn't sound specific to the new parser.

**Comment by staabm** [comment]
Maybe a CatachableFatalError vs Throwable case

**Comment by HipeL** [comment]
"Same" problem here, typing for example this 
`return response()->json(["response"=> false]);`
Gets my VScode stuck, and sound starts to repeat second after second, mouse and keyboard input get like 5 seconds delay and sometimes i even had to restart the machine to get it running again.

**Comment by felixfbecker** [comment]
This sounds like an infinite loop/recursion. Could you try the following:
Install/Enable XDebug and make sure `xdebug.max_nesting_level` is set (but not too low)
Go into `~/.vscode/extensions/felixfbecker.php-intellisense-x.x.x/vendor/felixfbecker/language-server/php-language-server.php` and uncomment [line 35](https://github.com/felixfbecker/php-language-server/blob/master/bin/php-language-server.php#L35).
Try again and see if you get an error like "Maximum function nesting level is reached" - if yes post the stack trace

**Comment by lockcole** [comment]
I am having similar problem but I am not sure it is syntax error problem or memory leak problem on Issue #425.
It usually happen when I am typing. When it got stuck there is usually a syntax error highlighting on the screen.
On my windows PC, the whole system will freeze when it got stuck. It keeps busy writing swap file until VS code reports that the host extension terminated unexpectedly.

It is what I could get from VS code development console after the system freeze.

![2017-07-17 18_44_26-clipboard](https://user-images.githubusercontent.com/3402682/28265708-b7dddd38-6b23-11e7-9a57-ef06f0c1fe80.png)

**Comment by TomasDuda** [comment]
I can confirm this problem - RAM, CPU and swap go to 100% for me on Arch Linux and the system completely freezed. I was working with DateTime.
