### ISSUE TITLE
Feature request on display function params

### ISSUE THREAD

**Issue by dcboy95** [felixfbecker/php-language-server#430]
Hi I was wondering if its possible to display the parameters of a function, similar to VS code's builtin like so:

![image](https://user-images.githubusercontent.com/8877998/27498227-53f4ee58-581b-11e7-980d-15aeddd40be6.png)

instead of having to highlight the function itself like:

![image](https://user-images.githubusercontent.com/8877998/27498283-960ffea4-581b-11e7-9183-e79fc97f4bf3.png)

Because as soon as I start typing it goes away, and I might not remember what was next

Thanks!

**Comment by jens1o** [comment]
dup #18

**Comment by felixfbecker** [comment]
PR welcome
