### ISSUE TITLE
Refactoring Support of external Files

### ISSUE THREAD

**Issue by zodiark23** [felixfbecker/php-language-server#433]
Using `Change All Occurrences` in vscode refactors code base within the file. But **other classes from external source** that is `referencing the class is not in the scope` of the said action. After clicking `Change All Occurrences`   only local file are affected. This may cause a discrepancy in other file that uses this class.

**Comment by felixfbecker** [comment]
"Change All Occurences" has no corresponding LSP method, the language server cannot provide any help here. There are open issues at the LSP repo for refactoring support, I suggest you direct your feedback there
