### ISSUE TITLE
php extract method from selection - feature request

### ISSUE THREAD

**Issue by rrd108** [felixfbecker/php-language-server#434]
It would be rally nice to have a PHP extract method from selection, like PHP Storm has. It is a very useful refactoring tool.

**Comment by felixfbecker** [comment]
Could you more describe in more detail what you mean with "extract method from selection"?

**Comment by rrd108** [comment]
here is an example: https://www.youtube.com/watch?v=MhwE52kdylI

**Comment by felixfbecker** [comment]
LSP doesn't have any method for this (and VS Code also has no UI for it). That would need to be added first before the language server can implement it.
