### ISSUE TITLE
Uncaught Error: Class 'phpDocumentor\Reflection\Types\Mixed' not found in /var/www/language-server/vendor/felixfbecker/lang uage-server/src/DefinitionResolver.php

### ISSUE THREAD

**Issue by sutem** [felixfbecker/php-language-server#442]
https://github.com/phpDocumentor/TypeResolver/releases/tag/0.4.0 (Renamed Mixed to Mixed_)
You either need to make edits to the file (LanguageServer\DefinitionResolver) or change the package version to an earlier version.

**Comment by felixfbecker** [comment]
See 7ce228417605bc8559716d300f21d0ce26209fda and https://github.com/phpDocumentor/ReflectionDocBlock/issues/109
