### ISSUE TITLE
Poorer intellisense than default?

### ISSUE THREAD

**Issue by Morgy93** [felixfbecker/php-language-server#444]
Hello,

you recommend: 
> I recommend to disable VS Code's built-in PHP IntelliSense by setting php.suggest.basic to false to avoid duplicate suggestions.

Before:
![image](https://user-images.githubusercontent.com/7961978/28617144-7e1689dc-71ff-11e7-8a9f-44d59e0195a9.png)
![image](https://user-images.githubusercontent.com/7961978/28617146-82a8ccf8-71ff-11e7-98c0-8c700e833f1c.png)

After:
![image](https://user-images.githubusercontent.com/7961978/28617108-59aaac5e-71ff-11e7-9a82-8dede5d51c98.png)
![image](https://user-images.githubusercontent.com/7961978/28617131-71adb72e-71ff-11e7-8d75-bbad77f37518.png)

I'm not quite sure if something is wrong here, but I think the way it was "before" is much nicer. 😁 

Maybe someone can clear things up here.

**Comment by felixfbecker** [comment]
I think what you are missing is #18. Check out #438 (thanks @probot-dup!)

The built-in IntelliSense uses regexps to find methods. It is far superior in detecting own symbols and doesn't do any attempt to resolve types, e.g.
```php
$foo->bar->baz // no IntelliSense for baz, guaranteed!
```

Descriptions of the standard library are the same as in PHPStorm, you can do PRs to https://github.com/JetBrains/phpstorm-stubs to improve them
