### ISSUE TITLE
auto completion adds backslash at the beginning

### ISSUE THREAD

**Issue by mustafawm** [felixfbecker/php-language-server#452]
when selecting from suggestions list (by `tab` or `enter`) a slash is added at the beginning of the command! 

![screen shot 2017-08-07 at 5 12 17 pm](https://user-images.githubusercontent.com/13101565/29015976-acf03698-7b93-11e7-9e67-be04f52a1ebf.png)

![screen shot 2017-08-07 at 5 12 30 pm](https://user-images.githubusercontent.com/13101565/29015979-b05af26e-7b93-11e7-9f44-d947bfccea5b.png)

user defined php settings:
```
   "php.validate.run": "onType",
    "php.executablePath": "/usr/local/bin/php",
    "php.suggest.basic": false,
    "php.validate.executablePath": "/usr/local/bin/php",
```

**Comment by mustafawm** [comment]
sorry to disappoint @probot-dup[bot] but you're wrong.

**Comment by felixfbecker** [comment]
Are you inside a namespace?

**Comment by mustafawm** [comment]
That's correct. I am, any workaround?

**Comment by felixfbecker** [comment]
Then this is as designed, it's a global function and it's faster because it saves PHP a lookup in the current namespace

**Comment by mustafawm** [comment]
Thanks for explaining that. Have a good day/night :)

**Comment by benignant** [comment]
Hey @felixfbecker. Any chance we could get a setting to control this?

**Comment by felixfbecker** [comment]
PRs welcome.
