### ISSUE TITLE
unable to open file at go to definition

### ISSUE THREAD

**Issue by alioygur** [felixfbecker/php-language-server#454]
hello,

I have created a project, then I moved to another path. After that Go to definition does not works. it search it in old path.

how to I delete cache, or restart server?

**Comment by felixfbecker** [comment]
Just restart your editor.
You can also delete the cache: https://github.com/felixfbecker/php-language-server/blob/master/src/Cache/FileSystemCache.php#L21

**Comment by alioygur** [comment]
I have restarted editor many times but it doesn't work

Also I removed project folder and recreated but result wasn't changed

8 Ağu 2017 Sal, saat 18:28 tarihinde Felix Becker <notifications@github.com>
şunu yazdı:

**Comment by felixfbecker** [comment]
Try to delete the cache folder. It depends on your OS, see the above link.
