### ISSUE TITLE
Is there a way to disable the formatter?

### ISSUE THREAD

**Issue by MortimerCat** [felixfbecker/php-language-server#456]
We want to use PHP Intellisense vscode plugin but we do not want to use the format - (We have another php formatter already configured as a house standard). 

The "php-language-server" formatter overrides our existing one with the autosave option and the right-click "format document" menu option. I have not been able to find a way to get our existing formatter to take precedence.  

The plugin is called Intellisense and thats want I want to use.

**Comment by felixfbecker** [comment]
Feel free to do a PR

**Comment by MortimerCat** [comment]
I'll take that as a no!

**Comment by kyotoprotokollet** [comment]
I second this. Strange that you can't just disable such a feature, which has nothing to do with Intellisense.
