### ISSUE TITLE
Improvements for file indexing

### ISSUE THREAD

**Issue by mniewrzal** [felixfbecker/php-language-server#46]
I would like to propose two changes in actual indexing implementation:
- keep source file content only for opened files. Content should be assigned after opening file and removed on close. This should give substantial memory saving. 
- Similar to previous, send publishDiagnostics notification also only for opened file. This is just minor optimization but sending lots of events that will be not used in client is just wasting resources.

If there will be no objections I will prepare PR.

**Comment by felixfbecker** [comment]
> keep source file content only for opened files. Content should be assigned after opening file and removed on close. This should give substantial memory saving. 

That would kind of remove the whole point of parsing at initialization. If you do a global symbol search, you need all ASTs (or at least a list of all symbols, in any case the `PhpDocument` object). I think it is a good idea for a later improvement to only keep the information relevant to us in memory and discard the AST (and reparse if needed). But this is better done once we actually have all the major requests implemented and know what we actually need. Memory optimization is a low priority for now. Personally I also value fast response times higher than low memory usage.

> Similar to previous, send publishDiagnostics notification also only for opened file. This is just minor optimization but sending lots of events that will be not used in client is just wasting resources.

I wouldn't say they are not used - they are shown in the error panel of VS Code for example.

**Comment by mniewrzal** [comment]
At the moment PhpDocument keeps only content of source file (as string) and SymbolInformation[], AST is used only to find all symbols in file and later isn't stored in PhpDocument. That's the reason why amount of memory allocated after parsing is relatively small. After parsing file content is used only for formatting and formatting is done only for opened files. In general source file content will be used only in context of editor (read: opened file).

From my experience I can only say that keeping memory consumption low should be equally important to keeping high performance ;)

> Personally I also value fast response times higher than low memory usage.

Is there any problem with response time?

> I wouldn't say they are not used - they are shown in the error panel of VS Code for example.

Ahh you are right :) I forgot about Problems panel.

**Comment by felixfbecker** [comment]
Sorry I did not remember this was implemented already. Discarding the content should be fine I guess, we only need it for formatting and for calculating the columns after AST parsing and on parsing errors.

> Is there any problem with response time?

No, in this case not. I thought you suggested re-parsing JIT vs keeping AST in memory.

**Comment by MadHed** [comment]
> keep source file content only for opened files. Content should be assigned after opening file and removed on close. This should give substantial memory saving.

Makes sense. Although I don't think the savings will be that big. :)

**Comment by kaloyan-raev** [comment]
> Although I don't think the savings will be that big. :)

A project with 10,000 PHP files with 1 KB each == 10 MB memory. There are bigger project and bigger files, so the savings for real life projects is measured in 10s of MB.

**Comment by mniewrzal** [comment]
Of course it depends on project size. It makes more sense for larger projects. For 24k files project memory allocation result was 630MB => 520MB (~20%).
