### ISSUE TITLE
 php.exe Has been out of memory

### ISSUE THREAD

**Issue by tiansin** [felixfbecker/php-language-server#460]
/**
 * This is the platform-independent base Query Builder implementation class
 * @var CI_DB_mysql_driver|CI_DB_query_builder
 */
 protected $db;

use $this->db-> 
Will make php.exe process memory unlimited,
Has been out of memory
![qq 20170817122903](https://user-images.githubusercontent.com/4232281/29396035-dde1aa64-8347-11e7-81d8-4cbac9367196.png)

php version:7.18

**Comment by felixfbecker** [comment]
Please provide a description.

**Comment by tiansin** [comment]
Sorry, just because it was wrong...

**Comment by felixfbecker** [comment]
Possible duplicate of #425
