### ISSUE TITLE
instantiated class assigned to class proprites don't provide intellesense

### ISSUE THREAD

**Issue by dking3876** [felixfbecker/php-language-server#463]
When assigning an instatiated class to a class variable it doesn't provide hints

```php
class A{

    public function method_a(){
        
    }
}


class B{

    public function __construct(){
        $this->A  = new A();
    }
    public function test(){
        $this->A-> ///no intellisense
    }
}
```

**Comment by felixfbecker** [comment]
You are missing the property definition for `$A`. Do
```php
class B {
  /** @var A */
  private $A;
}
```

**Comment by dking3876** [comment]
No that isn't it. this was just an example of a larger class. it doens't work even with the definition

**Comment by felixfbecker** [comment]
Then please provide a self-contained, reproducable example

**Comment by dking3876** [comment]
[index.zip](https://github.com/felixfbecker/php-language-server/files/1236685/index.zip)

this reproduces the issue. when classes are in a different file this doesn't work.  in my live code im using dI as you can see from the sample but it also doesn't work with the new keyword

thanks

**Comment by felixfbecker** [comment]
It works just fine if you add the `@var` declaration like I said in my previous comment.

![image](https://user-images.githubusercontent.com/10532611/29491747-d6274526-8519-11e7-8284-9edf2ab58013.png)

**Comment by dking3876** [comment]
You were correct, as im sure you knew. my apologies. thanks for the help, i had misunderstood your previous comment
