### ISSUE TITLE
how do i have it store intellisense data, so it doesnt get rerun on every program start

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#466]
_From @OliverLeitner on August 22, 2017 6:18_

as the title says...

i would like to reduce the system i/o load by have it not rescan stuff it already scanned.

is that possible?

_Copied from original issue: felixfbecker/vscode-php-intellisense#147_

**Comment by felixfbecker** [comment]
It already saves (caches) the index, but will still reindex because the files could have changed since the last run. I would be open to a PR that implements an option for this

**Comment by OliverLeitner** [comment]
thanks for redirecting my request.

i wouldnt exactly call this a bug, its more of a feature request that might help with the cpu load thing mentoined at #465 

ya, i noticed the caching (thanks btw. @felixfbecker , so if its already caching, one "might" make a "directory checksum" type thingy and then just compare the dirs for changes. afaik most filesystems that i know have directory changes in the "directory entry bit" (size..., date modified...).

**Comment by str** [comment]
- Where is the cache stored?
- What if we do not reindex if the cache has 24h or less? 
- What if we do not reindex the full project but only the the files when open?
- What if we [renice](http://www.thegeekstuff.com/2013/08/nice-renice-command-examples/?utm_source=tuicool) the reindex so it doesn't block the CPUs making the IDE useless for the first 10 minutes every time we open a project?

**Comment by felixfbecker** [comment]
> Where is the cache stored?

In the standard cache locations depending on OS. Check the FileSystemCache.php file for details.

> What if we do not reindex if the cache has 24h or less?

Then the index would become out of date.

>What if we do not reindex the full project but only the the files when open?

Then most IntelliSense features would not work.

> What if we renice the reindex so it doesn't block the CPUs making the IDE useless for the first 10 minutes every time we open a project?

Then you would renice the whole language server. The indexing is not in a different process.

**Comment by str** [comment]
I'll continue the discussion in  [gitter](https://gitter.im/felixfbecker/vscode-php-intellisense).

**Comment by felixfbecker** [comment]
Duplicate of #578
