### ISSUE TITLE
Unable to format file

### ISSUE THREAD

**Issue by karimsaieh** [felixfbecker/php-language-server#468]
```
[Error - 13:49:16] Request textDocument/formatting failed.
Message: Exception: Unable to format file in C:\Users\karim\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\Formatter.php:52
Stack trace:
#0 C:\Users\karim\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\PhpDocument.php(179): LanguageServer\Formatter::format('<?php\n\nnamespac...', 'file:///c:/wamp...')
#1 C:\Users\karim\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\Server\TextDocument.php(172): LanguageServer\PhpDocument->getFormattedText()
#2 C:\Users\karim\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#3 C:\Users\karim\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#4 C:\Users\karim\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#5 C:\Users\karim\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#6 C:\Users\karim\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#7 C:\Users\karim\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#8 {main}
  Code: -32603 
```

I noticed this error happens when i try to format a file already formatted

**Comment by thc1967** [comment]
I get a similar error when I try to format a PHPUnit test case class.

`[Error - 9:09:56 PM] Request textDocument/formatting failed.
  Message: Exception: Unable to format file in C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\Formatter.php:52
Stack trace:
#0 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\PhpDocument.php(179): LanguageServer\Formatter::format('<?php\n\nnamespac...', 'file:///d:/thc/...')
#1 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\Server\TextDocument.php(172): LanguageServer\PhpDocument->getFormattedText()
#2 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#3 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#4 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#5 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#6 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#7 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#8 {main}
  Code: -32603 
`

**Comment by balsagoth** [comment]
same here

**Comment by felixfbecker** [comment]
Formatting is done through PHP CodeSniffer. I'm waiting on pretty printing support from @roblourens to switch over

**Comment by gvmohzibat** [comment]
same here

**Comment by tkmattos** [comment]
same problem here

**Comment by stormpat** [comment]
Same

**Comment by TortleWortle** [comment]
Same here :/

**Comment by abekroenem** [comment]
same here

**Comment by qetee** [comment]
same here

**Comment by cobaltutby** [comment]
same:(
