### ISSUE TITLE
textDocument/formatting failed.

### ISSUE THREAD

**Issue by rainsun007** [felixfbecker/php-language-server#472]
`
Request textDocument/formatting failed.
  Message: Exception: Unable to format file in C:\Users\rain\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\Formatter.php:52
Stack trace:
#0 C:\Users\rain\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\PhpDocument.php(179): LanguageServer\Formatter::format('<?php\n\n/**\n * h...', 'file:///e:/proj...')
#1 C:\Users\rain\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\src\Server\TextDocument.php(172): LanguageServer\PhpDocument->getFormattedText()
#2 C:\Users\rain\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#3 C:\Users\rain\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#4 C:\Users\rain\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#5 C:\Users\rain\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#6 C:\Users\rain\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#7 C:\Users\rain\.vscode\extensions\felixfbecker.php-intellisense-1.5.1\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#8 {main}
  Code: -32603 
`

**Comment by felixfbecker** [comment]
#468 #445 #423

**Comment by tkmattos** [comment]
same problem here
