### ISSUE TITLE
Catch multiple exceptions

### ISSUE THREAD

**Issue by umpirsky** [felixfbecker/php-language-server#475]
Testing with:

```php
try {
//...
} catch (FirstException | SecondException $e) {
//...
}
```
got "Variable name expected" error. Looks like it uses old version of PHP.
I'm using it with https://github.com/atom/ide-php.

### Versions

```
atom-beta --version
Atom    : 1.21.0-beta0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
apm --version
apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.12
git 2.7.4
```
```
cat /etc/issue
Ubuntu 16.04.3 LTS \n \l
```

```
php -v
PHP 7.1.9-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep  2 2017 05:56:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by felixfbecker** [comment]
Thanks for reporting!
@roblourens looks like a parser issue?

**Comment by umpirsky** [comment]
@felixfbecker Yes, I don't have PHP 7.0 instlled, but looks like old PHP version.

Linted the code with `php -l` - no errors.

**Comment by felixfbecker** [comment]
Do you have a stack trace with the error?

**Comment by nesl247** [comment]
I too have the same issue using ide-php. This is on macOS with `php71` installed via homebrew.

**Comment by roblourens** [comment]
I thought there was an issue for this already but I guess not, I opened https://github.com/Microsoft/tolerant-php-parser/issues/173

**Comment by umpirsky** [comment]
It's opened on Feb 13.

**Comment by nesl247** [comment]
Is there any information that I can provide to get this resolved?

**Comment by nesl247** [comment]
Mentioning https://github.com/Microsoft/tolerant-php-parser/issues/103 so it gets related.

**Comment by robsonvn** [comment]
I still facing this problem. 
The problem seems to be fixed at the tolerant-php-parser project but not here. Any update?

**Comment by felixfbecker** [comment]
What do you mean with "but not here"?

**Comment by robsonvn** [comment]
I meant this project.

**Comment by felixfbecker** [comment]
If it's fixed in tolerant-php-parser, what work is left to do here?

**Comment by robsonvn** [comment]
Sorry, I thought tolerant-php-parser as a dependency for this project and the project should be updated.

**Comment by felixfbecker** [comment]
Yes, it's a dependency, so Composer will pull down the latest version of it. How are you using the language server?

**Comment by robsonvn** [comment]
I was using atom php ide so I updated the dependencies manually.

Thanks

**Comment by felixfbecker** [comment]
Then it's on atom ide-php to update the dependencies. For https://github.com/felixfbecker/vscode-php-intellisense it's automated
