### ISSUE TITLE
Static analysis: Using $this in a static method should show an error

### ISSUE THREAD

**Issue by lfbn** [felixfbecker/php-language-server#476]
Hi there,

I've checked this situation in Atom IDE 1.21 beta, with ide-php package installed. It should check for this incorrect usage of $this.

**Comment by MaartenStaa** [comment]
I pretty much have a working implementation of this. Should this be incorporated into this repository, or in the tolerant PHP server's DiagnosticProvider like other diagnostics currently are? Not sure if it's desirable to provide additional diagnostics from this package.

**Comment by felixfbecker** [comment]
Awesome. Semantic analysis should go into the language server, the parser should only be concerned with parsing.
