### ISSUE TITLE
@param PHPDoc doesn't support "|" pipe for multiple parameter types.

### ISSUE THREAD

**Issue by kwilliams1987** [felixfbecker/php-language-server#478]
As documented here: https://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.param.pkg.html

The following syntax:

```
/****
 * Super cool function
 *
 * @param Class1|Class2 $param1
 **/
function coolFunc($param1) {
    $param1-> // Carat here
}
```

Intellisense should highlight Class1 and Class2 as class types but only Class1 is highlighted.
Also, when IntelliSensing into the object there is no differentiation between which class provided the auto-complete member.

**Comment by felixfbecker** [comment]
The language server does consider union types. What do you mean with "highlight"?

**Comment by kwilliams1987** [comment]
See image:

![image](https://user-images.githubusercontent.com/2725436/30695741-921ad602-9ed9-11e7-83fe-49ab19d0848c.png)

You see that the class declaration to the left of the pipe is syntax highlighted, but the class-array declaration to the right of the pipe is not.

**Comment by felixfbecker** [comment]
This extension is not involved with syntax highlighting. Please file at VS Code.
