### ISSUE TITLE
LSP error on textDocument/definition

### ISSUE THREAD

**Issue by beyang** [felixfbecker/php-language-server#480]
Issue report from @AlexMax:

I am attempting to use felixfbecker/php-language-server with sourcegraph/sublime-lsp, and I'm running into problems.  I believe I have the language server properly configured, but something weird is being returned.  For example, if I try and right click -> Go To Symbol Definition, I find the following debug dump in the console:

```js
LSP: checking for clients on on  /Users/alex/Documents/Workspace/Git/op3
LSP: request 15: textDocument/definition 
LSP: got json:  {"result":{"uri":"file:\/\/\/Users\/alex\/Documents\/Workspace\/Git\/op3\/app\/src\/Outposter\/Page.php","range":{"start":{"line":19,"character":0},"end":{"line":530,"character":1}}},"id":15,"jsonrpc"
LSP: error handling response 15
LSP: Error handling server content: 0
```

This is something that happens repeatedly with tags in my own project - generated built-in PHP tags (that I generated using php-language-server's instructions) seem to work fine.

Is this a LSP problem, or is it a PHP language server problem?

My configuration is thus:

```js
{
	"clients": {
		"php-language-server": {
			"command": ["/usr/local/Cellar/php71/7.1.8_20/bin/php", "/Users/alex/.composer/vendor/felixfbecker/language-server/bin/php-language-server.php"],
			"scopes": ["source.php"],
			"syntaxes": ["Packages/PHP/PHP.sublime-syntax"],
			"languageId": "php"
		}
	},
	"log_debug": true,
	"log_stderr": true
}
```

**Comment by tomv564** [comment]
This is not `sourcegraph/sublime-lsp` but `https://github.com/tomv564/LSP`

The error is not helpfully displayed, but the LSP package is likely converting the uri `file:\/\/\/Users\/alex\/Documents\/Workspace\/Git\/op3\/app\/src\/Outposter\/Page.php` to a windows path. 

The Sublime logging doesn't add the escaping, so I suspect the PHP language server he is running is returning incorrect uris.

**Comment by felixfbecker** [comment]
@tomv564 what's wrong about that URI?

**Comment by tomv564** [comment]
The backslashes shouldn't be there? (At least, this is the first I've seen a language server return them...)
Nothing to do with Windows paths, that was a flashback from this morning :)

**Comment by felixfbecker** [comment]
that is valid JSON https://stackoverflow.com/a/10314758/4208018

**Comment by tomv564** [comment]
Missed the `Location` case instead of `Location[]` - fixed.
Next release will also contain proper exception logging :)

Thanks for the explanation!

**Comment by felixfbecker** [comment]
So this can be closed?

**Comment by tomv564** [comment]
Yes, fix won't be released for a few days, but the user could install from Github master as well.
