### ISSUE TITLE
Remove Images Directory

### ISSUE THREAD

**Issue by vinkla** [felixfbecker/php-language-server#485]
The `php-language-server`, `vscode-php-debug` and `vscode-php-intellisense` packages include a directory called `images` with screenshots and gifs in it. I suggest we move these images to [GitHub's CDN](https://gist.github.com/vinkla/dca76249ba6b73c5dd66a4e986df4c8d) instead. Right now every time someone downloads one of these packages they also have to download the `images` directory. This takes up bandwidth and unnecessary space.

[Here is a guide how to upload images to GitHub's CDN.](https://gist.github.com/vinkla/dca76249ba6b73c5dd66a4e986df4c8d)

**Comment by felixfbecker** [comment]
I would like to have the screenshots versioned in the repo (they are not _that_ big), but we can exclude them from the distribution 👍

**Comment by vinkla** [comment]
> I would like to have the screenshots versioned in the repo...

They will still be versioned since every time you update the urls it will be visible in the commits.

**Comment by felixfbecker** [comment]
I understand, but I want everyone to be able to just git clone and update the screenshots without requiring to copy+paste that image into a GitHub issue to get the URL.

**Comment by vinkla** [comment]
I understand. Lets keep them and exclude them from distribution.
