### ISSUE TITLE
goto definition wrong folder

### ISSUE THREAD

**Issue by hamzternaja** [felixfbecker/php-language-server#492]
goto definition wrong folder 
I tried to delete the folder "/Users/hamzter/.vscode" and "/Users/hamzter/Library/Application Support/Code" and reinstalled vscode, but the problem is still there.
tried using goto definition in another account has no problem. 
I tried disable extension "PHP IntelliSense(Felix Becker)" and enable extension "PHP Intellisense - Crane" then goto definition is works.
osx 10.13
vscode 1.17.0

![image](https://user-images.githubusercontent.com/13031401/31313249-b1de1fa4-ac07-11e7-8ea8-9ffc8348507d.png)

**Comment by roblourens** [comment]
Can you share the project so we can try it?

**Comment by hamzternaja** [comment]
I downloaded the new file from
https://github.com/yiisoft/yii2/releases/download/2.0.12/yii-advanced-app-2.0.12.tgz and move the extract file to anywhere then tried goto definition

**Comment by felixfbecker** [comment]
Try to delete `~/.phpls`

**Comment by hamzternaja** [comment]
problem solved, thank
