### ISSUE TITLE
Autocomplete not working

### ISSUE THREAD

**Issue by carlevison** [felixfbecker/php-language-server#494]
<img width="558" alt="screen shot 2017-10-12 at 17 52 03" src="https://user-images.githubusercontent.com/6619631/31508488-27a1c2ce-af76-11e7-936e-057041bfb8be.png">

I'm on dev build 3148 and MacOS 10.13

autocomplete isn't showing up, it flashes up, I see all my available methods but then it gets replaced by what you see here.

**Comment by felixfbecker** [comment]
I don't know what you mean with "dev build 3148". Is that Atom?
Please give a reproducible code example.

**Comment by carlevison** [comment]
Sorry I'm using Sublime with (https://github.com/tomv564/LSP) with a fresh installation of Laravel on app/Http/Controllers/Controller.php when it does work I don't get access to all the available methods.

Here is CodeComplice

<img width="528" alt="screen shot 2017-10-12 at 19 12 05" src="https://user-images.githubusercontent.com/6619631/31512116-bc3fa1f2-af81-11e7-8165-bf85c0439767.png">

And here is what I see with yours.

<img width="730" alt="screen shot 2017-10-12 at 19 14 03" src="https://user-images.githubusercontent.com/6619631/31512138-cc12896e-af81-11e7-900d-0fda43d09756.png">
<img width="724" alt="screen shot 2017-10-12 at 19 14 13" src="https://user-images.githubusercontent.com/6619631/31512140-cc2d8d5e-af81-11e7-8817-bf6c9980e1db.png">

**Comment by felixfbecker** [comment]
I am not familiar with laravel, could you please give me a [self-contained example](http://sscce.org/)?

**Comment by carlevison** [comment]
I'm not sure if this is what you mean but here goes.

1. clone https://github.com/laravel/laravel
2. Open app/Http/Controllers/Controller.php
3. Create a new method inside Controller.php and type $this-> to access available methods.
4. Check use statements to see which methods aren't being displayed.

**Comment by felixfbecker** [comment]
I cannot reproduce. I get all the methods that are defined in this class and `BaseClass`. I do not get the suggestions for `mcrypt` etc you are seeing.

![image](https://user-images.githubusercontent.com/10532611/31564795-3ba4ff40-b019-11e7-832e-2501fca22662.png)

Traits are not supported, see https://github.com/felixfbecker/php-language-server/issues/331.
