### ISSUE TITLE
Remove formatting

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#501]
At this point there are [countless issues](https://github.com/felixfbecker/php-language-server/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3Aformatting%20) about the formatting done by CodeSniffer. It plain out doesn't work in many cases, overrides format options that are contributed by other extensions in VS Code and does not reuse any of our AST parsing. For that reason, I am starting to think there is no reason to keep it in here until we have proper pretty-printing support from https://github.com/Microsoft/tolerant-php-parser that actually reuses our ASTs and can work while editing. For people who want to use CodeSniffer to format their code, there could be a standalone CodeSniffer language server (like there is a TSLint language server and ESLint language server). As said, we don't reuse our state anyway.

cc @roblourens @mniewrzal @kaloyan-raev

**Comment by kaloyan-raev** [comment]
I agree. The CodeSniffer formatting looked like a good idea in the early days of the PHP LS. But if it causes so much trouble, it is better to look for an alternative.

**Comment by felixfbecker** [comment]
To be clear, I am proposing to remove it even without having an alternative

**Comment by roblourens** [comment]
I agree that tolerant-php-parser needs to support this, but in the meantime, is there no other alternative for PHP pretty printing?

**Comment by felixfbecker** [comment]
also cc @damieng

**Comment by damieng** [comment]
No change needed in the Atom package - although we register the ability to code format in the package.json it still degrades functionality dynamically based on the initializationResponse.
