### ISSUE TITLE
"php" autocompletes to "php<?php"

### ISSUE THREAD

**Issue by Jensen0710** [felixfbecker/php-language-server#514]
Every time i type "php" it auto completes it as  "php`<?php`" and that's a really annoying problem for my productivity. Anyone who knows about this? 
![giphy](https://user-images.githubusercontent.com/9888000/32264293-532e8a2c-bede-11e7-886a-72b37d3e5b8b.gif)

**Comment by hassamali** [comment]
Its the Code snippets builtin in your code editor or ide what ever it is, can you tell me which code editor you are using?
