### ISSUE TITLE
Expected ";" when you have a "use Object;" statement.

### ISSUE THREAD

**Issue by SilbinaryWolf** [felixfbecker/php-language-server#516]
Silverstripe 3.6 uses the class name "Object" and runs fine in PHP 7.1.

I'm aware Object is a soft keyword and could stop working in future PHP versions, but until then, can this please be fixed.

Example code that gets an error:
https://github.com/SilbinaryWolf/silverstripe-phpstan/blob/master/src/MethodClassReflectionExtension.php#L19

Test repo, should be able to just `composer install` and test with the language server:
https://github.com/SilbinaryWolf/silverstripe-phpstan-testproject

**Comment by felixfbecker** [comment]
This issue was moved to Microsoft/tolerant-php-parser#205
