### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by seanmars** [felixfbecker/php-language-server#519]
OS: Windows 10 and OSX 10
PHP: 7.0

Get error when install by `composer require felixfbecker/language-server`.
The error information is below:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for felixfbecker/language-server ^5.0 -> satisfiable by felixfbecker/language-server[v5.0.0].
    - felixfbecker/language-server v5.0.0 requires jetbrains/phpstorm-stubs dev-master -> satisfiable by jetbrains/phpstorm-stubs[dev-master] but these conflict with your requirements or minimum-stability.
```

**Comment by felixfbecker** [comment]
> satisfiable by jetbrains/phpstorm-stubs[dev-master] but these conflict with your requirements or minimum-stability

You need to set your `minimum-stability` lower to allow jetbrains/phpstorm-stubs[dev-master]. 
https://getcomposer.org/doc/04-schema.md#minimum-stability
