### ISSUE TITLE
Installation of "php-language-server" FAILED:

### ISSUE THREAD

**Issue by steven7mwesigwa** [felixfbecker/php-language-server#521]
Hello ,

Am trying to install this "_php-language-server_" as a requirement to use **PHP IntelliSense** by "_Felix Becker_" in VSCODE.

As advised on the repo page i run:

`composer require felixfbecker/language-server`

And i received this ERROR:

```
Using version ^5.0 for felixfbecker/language-server
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for felixfbecker/language-server ^5.0 -> satisfiable by felixfbecker/language-server[v5.0.0].
    - felixfbecker/language-server v5.0.0 requires jetbrains/phpstorm-stubs dev-master -> satisfiable by jetbrains/phpstorm-stubs[dev-master] but these conflict with your requirements or minimum-stability.


Installation failed, deleting ./composer.json.
```

I have **php7** and **composer** installed. Am running _DEBIAN_ .
PLEASE.. Advise me on how to rectify this issue. Thanks in advance.

**Comment by jens1o** [comment]
It is included in the `PHP Intellisense` package, you do not need to install anything else.

**Comment by felixfbecker** [comment]
This is stated in the readme.

**Comment by steven7mwesigwa** [comment]
@jens1o,   Do you mean i should just **ignore** the "error message" ?.
Challenge is: PHP IntelliSense by @felixfbecker   is installed succesfully but isn't working.......

**Comment by felixfbecker** [comment]
@steven7mwesigwa you don't have to run `composer require felixfbecker/language-server`. All you need is to install the PHP IntelliSense extension through the VS Code UI.

**Comment by steven7mwesigwa** [comment]
@felixfbecker  Thanks for the quick reply.
But am wondering why amnot receiving the promised "Intellisense" once i have disabled the one that comes from default VSCode.
Is there anything i should look at first..?

**Comment by felixfbecker** [comment]
Do you have log output in your output panel?

**Comment by steven7mwesigwa** [comment]
@felixfbecker  I just Launched VS Code Quick Open (Ctrl+P),  pasted `ext install felixfbecker.php-intellisense`, and pressed enter. Then clicked Install, And pressed reload when it was done.
I dont know what you mean by **_Output panel_**

**Comment by felixfbecker** [comment]
This

![image](https://user-images.githubusercontent.com/10532611/32989620-af9432be-ccce-11e7-9589-904a2515e4b7.png)

**Comment by steven7mwesigwa** [comment]
@felixfbecker ... Oooh i see... Well i didn't check.
Let me Uninstall & Reinstall the Package and give you any feedback i happen to find. 
Thank you for your time....

**Comment by felixfbecker** [comment]
You don't need to reinstall. There should be output there whenever you open a PHP project and open a PHP file.

**Comment by steven7mwesigwa** [comment]
@felixfbecker  i guess am just unlucky...
i have tried yours and my option of re-installation  but in vain. "Didn't receive any output.. installation seems to work successfully."
i just pray that may be at some point it will pick up the intellisense.
i will just use the default intellisense in the mean time....

**Comment by steven7mwesigwa** [comment]
@felixfbecker  ... It now WORKS!!!!!
I simply upgraded to the latest VSCODE version...and some how it worked.
Though one other **challenge** is that : "_**It is kinda slow**_"...Basically slower than the _Default vscode php intellisense_...
I checked around... and i presume you guys are working on the **"Speed Issue"**
