### ISSUE TITLE
Add custom stubs

### ISSUE THREAD

**Issue by natanfelles** [felixfbecker/php-language-server#522]
Like the [phpstorm-stubs](https://github.com/JetBrains/phpstorm-stubs) I want to add [phalcon-stubs](https://github.com/phalcon/ide-stubs) to all my environments.

I added the generated phalcon-devtools stubs path in [this loop](https://github.com/felixfbecker/php-language-server/blob/1804ac8d978a318a4a6b88dc02b4362854b6a65b/src/ComposerScripts.php#L37).

Perhaps a way to the user add custom stubs be good. 

Thank you.

**Comment by natanfelles** [comment]
*Also read all php files inside all child folders*...

**Comment by jens1o** [comment]
would love to see this too, because I work heavily with a project and waiting for 1200 files to finish indexing is annoying :(

**Comment by felixfbecker** [comment]
Why don't you just add them as a devDependency with Composer?

**Comment by jens1o** [comment]
Because they do not expose itself as a composer package, since it's more like a software, with its own setup.

**Comment by felixfbecker** [comment]
The readme literally tells the user to add it as a Composer devDependency.

**Comment by jens1o** [comment]
Pardon me?

**Comment by felixfbecker** [comment]
did you click the link in the post?

**Comment by jens1o** [comment]
Oh, I get it. Unfortunately, it does not match my solution. :(

**Comment by natanfelles** [comment]
More info: 

Phalcon is a PHP Module and his docs are not in the phpstorm-stubs.

Using the Phalcon ide-stubs project by project is necessary wait the time of indexing every time that the editor is open.

This issue is just a suggestion, to have an option to the user add more default stubs.

Of course is possible to use as a composer dev dependency, thought about to use it as a global package.

**Comment by felixfbecker** [comment]
The advantage of "custom stubs" vs a devDependency is still not clear to me. Could you please explain? Composer indexes are cached, so they should not cause a reindex.

**Comment by natanfelles** [comment]
Forgot Composer. It was just a suggestion to have an option to the user add more default stubs.

Why will be done is not relevant. But can do it or not is. 

The Phalcon stubs was an usage example.

It seems like this is not useful. Thank you.
