### ISSUE TITLE
Multi catch exception handling support

### ISSUE THREAD

**Issue by eduardoweiland** [felixfbecker/php-language-server#526]
The new feature [Multi catch exception handling](http://php.net/manual/en/migration71.new-features.php#migration71.new-features.mulit-catch-exception-handling) added in PHP 7.1 is showing as error in VSCode. Other new features are working, like class constant visibility, so it's not the same error as #370 or #409.

VSCode 1.18.0
PHP 7.1.11
PHP IntelliSense extension v1.5.4

![screenshot2](https://user-images.githubusercontent.com/1799015/32779615-90a13b9c-c925-11e7-819f-43bcdd85e456.png)

![screenshot1](https://user-images.githubusercontent.com/1799015/32779595-7605f96c-c925-11e7-9efd-262f56f6cbac.png)

Running php lint in terminal does not show any error:

    $ php -l myfile.php
    No syntax errors detected in myfile.php

**Comment by felixfbecker** [comment]
Tracked in https://github.com/Microsoft/tolerant-php-parser/issues/103

cc @roblourens
