### ISSUE TITLE
question: alternative installation method

### ISSUE THREAD

**Issue by dodyagung** [felixfbecker/php-language-server#530]
is it safe to install this project with
`composer global require felixfbecker/language-server`
or
`composer require felixfbecker/language-server --dev`

instead of the default one :
`composer require felixfbecker/language-server`

thanks!

**Comment by nicolasmure** [comment]
I'm using `$ composer global require felixfbecker/language-server` so it is installed in my home directory (`~/.config/composer`).

**Comment by felixfbecker** [comment]
You can do whatever you want :)
