### ISSUE TITLE
Include paths for code completion and reference resolution

### ISSUE THREAD

**Issue by vuongggggg** [felixfbecker/php-language-server#534]
Sorry if I have any mistake!

I want to add some external libraries path (ex: global composer folder) for code completion and reference to my VSCode, but it's not show in the explorer as my main source. For detail, it looks like *Include Paths* feature of PHPStorm.

![image](https://user-images.githubusercontent.com/3168632/33000768-9e775272-cddc-11e7-9da0-316fd91b9bbf.png)

Can anyone give me a solution or suggest this as a new feature?

Thanks.

**Comment by felixfbecker** [comment]
There is no concept of include paths atm. Your project folder is considered self-contained.

**Comment by will-in-wi** [comment]
This would be super useful for developing plugins for things like Magento, Drupal, WordPress, et cetera. Often I have the main source code on disk somewhere, and I don't get autocomplete for anything other than my particular plugin in the current folder. It'd be nice to be able to define a folder where the definitions can be used in my project.
