### ISSUE TITLE
Setting to disable "$this can only be used in an object context."

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#536]
_From @Gauss23 on November 20, 2017 15:23_

Hello,

we just wondered about a lot of "syntax"-errors in our code. The message is:

> $this can only be used in an object context.

Before your update to version 2.0.0 everything was fine. The files IntelliSense is now marking as wrong are config files, which are required/included in object context, so they are perfectly working. Of course IntelliSense cannot know that. Is there a chance to make this check optional?

Best regards,
Christopher

_Copied from original issue: felixfbecker/vscode-php-intellisense#201_

**Comment by felixfbecker** [comment]
@Gauss23 is there a way to identify these config files? E.g. do they have a top-level return?

**Comment by Gauss23** [comment]
Unfortunately no, we are using this in config files and templates. Our renderer is an object, the templates it is parsing are PHP files and are using $this for multiple reasons. PHP is not complaining and everything is working. We don´t want to make too much trouble about it,.

A simple config switch would be sufficient for us. For the majority of the people, the error will be correct.

**Comment by felixfbecker** [comment]
Want to do a PR?

**Comment by Gauss23** [comment]
I just looked into the sources. I can see how to add a config var in extension.ts and how to push it as a cmd option to bin/php-language-server.php.
How do you want to push the config variable to the TreeAnalyzer? I saw it´s created by PhpDocument.php.
Using a global would not be the preferred method I think. Is there already some kind of infrastructure to pass something from the outside deeply into the the objects? 
Maybe there will be more config settings in the future. 

Best regards

**Comment by felixfbecker** [comment]
No, it would have to implement `didChangeConfiguration`: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#workspace_didChangeConfiguration

**Comment by Gauss23** [comment]
I thought I can add a line in: `vscode-php-intellisense/src/extension.ts`
Like this line:
`    const memoryLimit = conf.get<string>('memoryLimit') || '-1';`
I would add:
`    const checkThisInClasses = conf.get<string>('checkThisInClasses') || '1';`

And then add a command option in the same file.

Can´t see how to implement didChangeConfiguration, sorry.

**Comment by felixfbecker** [comment]
That wouldn't help. The configuration can change.

**Comment by Gauss23** [comment]
At the moment you´re not handling config changes, at least I can´t find an implementation of this didChangeConfiguration in intelliSense.
I´ll try to find an example for this implementation.

**Comment by felixfbecker** [comment]
Because at the moment there is no config

**Comment by Gauss23** [comment]
Memory limit and php executable are config variables in VS Code. Am I wrong? What if those settings are changed? Where is the trigger to restart the language-server?
Sorry, those are my first steps with vs code extensions.

**Comment by felixfbecker** [comment]
Memory limit and PHP executable are settings for the VS Code extension that modify how the language server is spawned, it's not a setting that is used in the language server at runtime or can change. Customisation of the static analysis should happen through the protocol.

**Comment by Gauss23** [comment]
I see, I think I´ll leave that one for a more experienced vs code extension developer.

Thank you for your patience.

**Comment by str** [comment]
Hi! I'm getting the same error message now in 2.0. In my case (current project: Magento) This happens in different files. I think this message should be ignored if `$this` is used in the document's root scope.  I also remember in CakePHP views, `$this` was used a lot.

I'm trying to find when this error can be useful, and I can only think of, if `$this` is called within a function (not class method)

**Comment by qiutuleng** [comment]
I have the same problem

**Comment by luispuig** [comment]
Same problem

**Comment by luispuig** [comment]
I was expecting to config rules like ESlint

**Comment by jens1o** [comment]
@luispuig You may want to implement the protocol ;)

**Comment by jens1o** [comment]
@felixfbecker I want to take a shot. I added a method to `Server\Workspace` called `didChangeConfiguration`. How can I manage that this is being called automatically? It looks like the AdvancedJsonRPC dispatcher is not recognizing it.

**Comment by MaartenStaa** [comment]
@jens1o if you're going to look into this, I just wanted to offer the suggestion to be able to configure a whitelist or blacklist for where (not) to check for the error. Then people could just add the path to their views.

**Comment by jens1o** [comment]
First of all, I want to implement the ConfigurationWatcher, before I can resolve this issue(and others) ;)

**Comment by felixfbecker** [comment]
@jens1o you don't need to do anything to make it called automatically as long as the client calls it. But you may have to declare a ServerCapability in `initialize`.

**Comment by felixfbecker** [comment]
@MaartenStaa a lot of people are hitting this issue, I think it's reasonable to ignore the error if it is in the global context and not in a function. Would you be up for implementing that?

**Comment by jens1o** [comment]
@felixfbecker I don't find the server capability in the protocol... I'm sorry.

Could you give me a pointer? https://github.com/jens1o/php-language-server/tree/jens1o-workspace-settings

**Comment by kilbiller** [comment]
Hi,

I have the same problem. I use kahlan a test framework https://github.com/kahlan/kahlan that uses a describe-it syntax to write tests and in these tests (which are functions) $this can be called a lot.
So throwing an error in the context of a function would not work for kahlan users.

I'm not sure what the solution should be.

**Comment by soren121** [comment]
Is reverting #528 off the table? It seems apparent that the rules that it checks against are too simplistic and result in many false positives. In my case, it complains that the use of $this in the [Slim Framework's route group closures](https://www.slimframework.com/docs/objects/router.html#route-groups) is invalid.

I don't like the idea of a configuration option that suppresses this error. It seems like the PHP parser could conceivably validate that `$this` is available at compile-time, it just doesn't at the moment. It should not be up to the developer to suppress errors for code that is safe and valid.

**Comment by tellkonkle** [comment]
I'd sooner have $this error turned off completely then put up with it giving false positives like what it's doing now. Red swirleys under every single $this variable in a script full of closures is very, very distracting.
