### ISSUE TITLE
my code can't format

### ISSUE THREAD

**Issue by Edison6351** [felixfbecker/php-language-server#537]
vscode version:1.18.1
php IntelliSense version:2.0.1
os version: mac os High Sierra 10.13

  well,i'm always using php intelliSense format my php code,but this week i can't find format in menu and format code option can't find, i have deleted my ~/.vscode/extension folder reinstall vscode but problem still in there,love this plugin thanks for help

**Comment by felixfbecker** [comment]
Please read the release notes. https://github.com/felixfbecker/vscode-php-intellisense/releases/tag/v2.0.0
