### ISSUE TITLE
Resolve types recursively

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#54]
From #49:

Go To Definition currently works for
- class instantiations
- static method calls
- class constant access
- static property access
- parameter type hints
- return type hints
- method calls, if the variable was assigned to a new object in the same scope
- property access, if the variable was assigned to a new object in the same scope
- variables
- parameters
- imported closure variables (`use`)
- `use` statements that import a class-like
- class-like after `implements`/`extends`
- function calls
- constant access

What does not work yet:

``` php
$x = new Whatever();
$y = $x;
$y->myMethod(); // cannot get definition for myMethod

$x = new Whatever();
$x->property->myMethod(); // cannot get definition for myMethod
$x->myMethod()->anotherMethod(); // cannot get definition for anotherMethod

$this->myMethod(); // cannot get definition for myMethod, $this is not resolved to the class

trait MyTrait {}
class MyClass {
  use MyTrait; // cannot get definition for MyTrait
}
```
- Method/property access on a return value needs to be resolved _recursively_
- Variable reassignments need to be resolved _recursively_
- DocBlocks need to be parsed

**Comment by z-ax** [comment]
Hi. Just checked with VSCode. I see a great work was done here but not yet looks usable to me.
Maybe, I'm doing something wrong, or that was not yet released to the VSCode extension?

From the checklist must say that `class constant access` doesn't work. As well as class constants auto-complete. I get huge list of everything except class constants, actually when typing `self::`

<img width="396" alt="screen shot 2016-11-01 at 01 17 00" src="https://cloud.githubusercontent.com/assets/1391015/19874866/017972e6-9fd1-11e6-96c3-cb4a004cda7d.png">

That list includes static functions, but not constants.

Also, can't get any completion for anything of other classes, even the list of available classes.

And no PhpDoc reading. E.g. I have a view with header like this:
```php
<?
/**
 * ...
 *
 * @var View $this
 * @var Meta $meta
 * @var bool $isUser
 * @var array|bool $release
 * @var array|bool $next
 * @var array|bool $previous
 */
```
No auto-complete at all as well.

**Comment by felixfbecker** [comment]
@z-ax This issue is about _go to definition_, not completion. Completion is tracked by #9

**Comment by z-ax** [comment]
Well, _go to definition_ doesn't work for those as well.
Thanks, will subscribe for both threads.

**Comment by felixfbecker** [comment]
@z-ax there is a unit test for class constant definition: https://github.com/felixfbecker/php-language-server/blob/master/tests/Server/TextDocument/Definition/GlobalTest.php#L71

If you found a bug, please open a separate issue, this issue tracks resolving types dynamically.
