### ISSUE TITLE
Configurable file size limit (for laravel-ide-helper)

### ISSUE THREAD

**Issue by jwhulette** [felixfbecker/php-language-server#548]
I'm using https://github.com/barryvdh/laravel-ide-helper but I get this message when indexing, Ignoring file.../_ide_helper.php because it exceeds size limit of 150000 bytes (539143).

Can I increase the file limit size?

**Comment by str** [comment]
Usually large files are the "let's put everything there" solution. I hate it, but it is what it is. We need to be able to set the size limit in the IDE configuration so we can include those ugly files.

**Comment by robberphex** [comment]
Maybe index a large file will cost a lot of time, but can we use some extension of PHP to accurate indexing? [php-ast](https://github.com/nikic/php-ast)

---
P.S.
*I am working on a project with 17921 `*.php` files, the largest file `Types.php`, 968KiB. I really want:*
1. accelerate the indexing.(via [php-ast](https://github.com/nikic/php-ast)?)
2. language server can index large files.
3. `Go to implements`

**Comment by AndisGrossteins** [comment]
I have two questions for developer of `php-language-server`:
1. WTF?
2. Why hardcode the limit in code?

https://github.com/felixfbecker/php-language-server/blob/26e3451e6123aff9e40c8465d5d7d013ba2a2724/src/PhpDocumentLoader.php#L109

```php
    public function load(string $uri): Promise
    {
        return coroutine(function () use ($uri) {
            $limit = 150000;
            $content = yield $this->contentRetriever->retrieve($uri);
            $size = strlen($content);
            if ($size > $limit) {
                throw new ContentTooLargeException($uri, $size, $limit);
            }
            if (isset($this->documents[$uri])) {
                $document = $this->documents[$uri];
                $document->updateContent($content);
            } else {
                $document = $this->create($uri, $content);
            }
            return $document;
        });
    }
```

**Comment by RobberPhex** [comment]
Excuse me, I'm not working on this, so I will close this PR.

**Comment by animalillo** [comment]
An option to configure this would be great, i have to deal with some huge files and are a pain to work with without intellisense working properly.

**Comment by phil-s** [comment]
Is this hard-coded limit connected to issue #245 ?

**Comment by phil-s** [comment]
I have nine files above the 150,000 byte limit in my project:

* 201,651
* 203,613
* 208,023
* 209,602
* 235,468
* 319,514
* 471,662
* 553,415
* 577,243

The project contains 4,692 PHP files, so these additional files, whilst large, do not represent a dramatic increase in the overall codebase to be parsed.  Together the files comprise less than 10% of the PHP: 2,980,191 bytes out of 33,292,778

By default, with the language server *ignoring* those files, the final result is:

> All 4692 PHP files parsed in 334 seconds. 274 MiB allocated.

If I lift the hard-coded file size limit so that it also processes the large files, the final result is:

> All 4692 PHP files parsed in 2767 seconds. 364 MiB allocated.

That is an increase from 5.5 minutes to 46 minutes!

The difference between the two runs seems a little crazy, and suggests that there may be some kind of quadratic or exponential time complexity issue going on in the parser?

**Comment by phil-s** [comment]
Some timing stats extracted from the log for the four largest files.  There is evidentially some kind of pathological case occurring in the 2nd-largest file, in particular.  I'll try to supply more details on that later.

1st pass = "Indexing project for definitions and static references"
2nd pass = "Indexing project for dynamic references"

* File 1 = 319,514 bytes

    1st pass: 00:01
    2nd pass: 00:01
    Total: 2 seconds

* File 2 = 471,662 bytes

    1st pass: 00:21
    2nd pass: 00:14
    Total: 35 seconds

* File 3 = 553,415 bytes

    1st pass: 13:55
    2nd pass: 23:07
    Total: **37 minutes**

* File 4 = 577,243 bytes

    1st pass: 01:03
    2nd pass: 01:09
    Total: 2 minutes

**Comment by phil-s** [comment]
In a project with *only* that one difficult file, I'm seeing:

1st pass: 11:54
2nd pass: 11:53
