### ISSUE TITLE
Remote PHP Interpreter from Docker Container

### ISSUE THREAD

**Issue by Jarzebowsky** [felixfbecker/php-language-server#549]
Hi,

Will it be somekind of problem to reproduce the thing that I can find only releated to PHPStorm: https://blog.jetbrains.com/phpstorm/2016/11/docker-remote-interpreters/

That's what I'm missing in my VSCode PHP Intelisense package.

**Comment by cardonator** [comment]
You can easily set up a script that runs php from a docker container and point the plugin at that. You do need to mount your home folder into the PHP container (this is for Linux, so YMMV)

```#!/bin/bash

docker run --rm -i \
  -v /home/cardonator:/home/cardonator \
  -v $PWD:/code \
  -w /code \
  php:alpine php "$@"```

**Comment by Jarzebowsky** [comment]
@cardonator May u explain me what `$PWD` stands for and last line: `php:alpine php "$@"` ?

**Comment by cardonator** [comment]
`$PWD` is the current working directory on the host machine. In the context of VS Code, it would end up being your workspace project folder.

The last line is what is passed to the docker container. in this case:

`php:alpine` is the image name

`php` is the program name to run inside the container.

`"$@"` essentially means "pass all additional parameters from the command in here.

I have this bash script in `/usr/local/bin/php` so from the command line I can just run php and it executes that code. I haven't tested it on Windows, but some variation of it should work on macOS.

**Comment by cardonator** [comment]
FWIW, I still think tighter integration between this plugin and the Docker plugin would be a great feature.

**Comment by Jarzebowsky** [comment]
It works, as you said - but, yeah. It would be a cool feature to have :)

**Comment by felixfbecker** [comment]
The language server is available as an image on Docker Hub: https://hub.docker.com/r/felixfbecker/php-language-server/

It speaks LSP and the language server is capable of receiving file contents remotely through the protocol.

**Comment by cardonator** [comment]
Does the vscode-intellisense plugin have the capability to connect to the docker language server?

**Comment by felixfbecker** [comment]
No, because vscode does not implement the remote files LSP extension.
