### ISSUE TITLE
php cannot go to the function,error:"register" is not defined

### ISSUE THREAD

**Issue by weinand** [felixfbecker/php-language-server#553]
_From @yecanlin on December 19, 2017 3:22_

- VSCode Version: 1.9
- OS Version: windows 64

Steps to Reproduce:

1.
![90 hvunr 1a 8l5x ihv9](https://user-images.githubusercontent.com/17768200/34139242-9782256c-e4ae-11e7-8422-846778213e5d.png)

2.
![c3_eybezia 8sa pjo 2](https://user-images.githubusercontent.com/17768200/34139257-bf57c9ca-e4ae-11e7-9509-501114a6ae8a.png)

3.
![dmv a x4e9 z n h 28 z o](https://user-images.githubusercontent.com/17768200/34139290-eb51ab4a-e4ae-11e7-8c9e-2785dc273332.png)

Reproduces without extensions: Yes/No

_Copied from original issue: Microsoft/vscode#40474_

**Comment by felixfbecker** [comment]
Could I get the full code?

**Comment by yecanlin** [comment]
@felixfbecker This is php framework : thinkphp 3.2 complete edition.
The problem is:the package can work yesterday, but next day can work, I only create a controller on the framework for a test.

**Comment by yecanlin** [comment]
[thinkphp_5.0.12_full.zip](https://github.com/felixfbecker/php-language-server/files/1573947/thinkphp_5.0.12_full.zip)
this php framework : thinkphp 5.0.12 complete edition.
Reinstall still no work.

**Comment by felixfbecker** [comment]
What file did you have open in your screenshot?

**Comment by yecanlin** [comment]
@felixfbecker Sorry, I forget!

**Comment by felixfbecker** [comment]
I'm sorry, but I can't help you then
