### ISSUE TITLE
To Not Merge Multi-line Comment into One

### ISSUE THREAD

**Issue by iven00000000** [felixfbecker/php-language-server#555]
Following is a block of example codes.
```
/**
 * Parse CSV the files into the array.
 * $csvStr will not be modified.
 * Usage:
 * str_getcsv_file(&$csvStr, $assoc=true, $fieldnames=null, 
 *                 $delimiter=",", $enclosure ='"', $escape ="\\")
 * str_getcsv_file(&$csvStr, $fieldnames=null, 
 *                 $delimiter=",", $enclosure ='"', $escape ="\\")
 * 
 * @param string    $csvStr     Input string of the whole CSV file. 
 *                              $csvStr is passed by reference just to only 
 * ...
 * ...
 * ...
function str_getcsv_file(&$csvStr, $assoc=true, $fieldnames=null, 
                         $delimiter=",", $enclosure ='"', $escape ="\\")
{
```
If I wrote the comments like this, the server will merge the multi-line comment into one line. The result showed in the pop-up window as the following.
![image](https://user-images.githubusercontent.com/11438642/34194330-3666a038-e593-11e7-9c59-6d0ef32c2b2f.png)

**Comment by felixfbecker** [comment]
The comment is interpreted as markdown. You can indent the code blocks by 4 spaces or put backticks around it

**Comment by iven00000000** [comment]
I got it. Thanks for your reply!

**Comment by staabm** [comment]
> The comment is interpreted as markdown. You can indent the code blocks by 4 spaces or put backticks around it

Why? I dont know any IDE which does it? Does the phpdoc standard define it like that?

**Comment by felixfbecker** [comment]
VS Code does it. I just give it the string content. And imo it makes a lot of sense

**Comment by iven00000000** [comment]
As a server, this project may not only want to serve for VS Code, and in the most situation, a team cannot ask all developers to use VS Code, so if someone made the comments into markdown style for beautiful display in VS Code, other developers have to read the comments with not straight layout.
I think it will be better and more user-friendly, if this project, php-language-server, implements a module to change the string content got from parsers to match the corresponding markdown format.

**Comment by felixfbecker** [comment]
@iven00000000 I don't understand your suggestion, I am literally just passing the precise string content of the docblock to the client. If a different client doesn't interpret it as markdown, that's up to him. But _escaping_ it as markdown is actually what would introduce assumptions about the docblocks being in markdown and clients trying to pretty-print that. This is a client issue, if you don't want a client (vscode) to render it as markdown, please ask them to add a setting for that. This language server should not make assumptions and just return the raw content.

**Comment by iven00000000** [comment]
Sorry, I didn't represent precisely. I suggested that this project could add a specialized module for VS Code to change the raw content, and could also add other specialized modules for other IDE. As the result of adding the specialized modules, users can see beautiful layout with different IDE by using the respective module corresponding to the IDE they use when the comments in codes were not written in  particular format, like markdown.

**Comment by felixfbecker** [comment]
I am against adding any client-specific code to the language server - LSP is about standardisation for servers, any differentiation / display questions need to happen in the client.

**Comment by iven00000000** [comment]
I am able to agree your opinion. It is good for this project that there is a clear position of this project. Thank you.
