### ISSUE TITLE
HTML inside intellisense popup not rendering

### ISSUE THREAD

**Issue by borlak** [felixfbecker/php-language-server#557]
![screen shot 2017-12-20 at 4 00 20 pm](https://user-images.githubusercontent.com/1967460/34234267-ea644864-e59e-11e7-8ef5-034b192d4fe7.png)

In the screenshot, you can see the "p" and "br" tags are not rendered.  I don't know if I need another extension to do this properly -- I searched the extensions and didn't see anything that seemed to fit.

I'm on a Mac, using Code version 1.19.1 and the intellisense extension version 2.1.0.

**Comment by felixfbecker** [comment]
This is controlled by vscode - Markdown can contain HTML, but vscode chooses to escape all HTML. Imo simple HTML like `p`/`b`/`ul`/`li` etc should be whitelisted, there are npm modules that do this easily.

**Comment by felixfbecker** [comment]
This issue was moved to Microsoft/vscode#40607
