### ISSUE TITLE
Call to undefined method MemberAccessExpression::getName()

### ISSUE THREAD

**Issue by ymauray** [felixfbecker/php-language-server#563]
When I start VSCode (1.19.1), I get the `The PHP Language Server server crashed 5 times n the last 3 minutes. The server will not be restarted` error.

In the developer console, I have :
```
Error: Call to undefined method Microsoft\PhpParser\Node\Expression\MemberAccessExpression::getName() in /home/yannick/.vscode/extensions/felixfbecker.php-intellisense-2.2.1/vendor/felixfbecker/language-server/src/DefinitionResolver.php:574
```
(full stack trace attached).

Nothing special in the output console : 

```
[Info  - 22:22:55] 389 files total
[Info  - 22:22:55] Indexing project for definitions and static references
Parsing file:///....
Parsing file:///....
[Info  - 22:22:55] Connection to server got closed. Server will restart.
```

VSCode : 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:41:01.414Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

php intellisense : 2.2.1
php language server : the one bundled with php intellisence.

[php-language-server-stacktrace.txt](https://github.com/felixfbecker/php-language-server/files/1585060/php-language-server-stacktrace.txt)

**Comment by felixfbecker** [comment]
@phil-nelson may be another bug introduced by #551?

**Comment by ymauray** [comment]
In the meantime I rolled back to 2.1.0 using the VSIX and it's all fine.
