### ISSUE TITLE
PHP Intellisense, huge memory leak when building cache 

### ISSUE THREAD

**Issue by evoliatis** [felixfbecker/php-language-server#566]
We use vscode and php intellisense with Laravel project and we have a huge memory leak (16 Go in 5 minutes) with this file : **vendor/symfony/http-kernel/DependencyInjection/RegistrerControllerArgumentLocatorsPass.php** during building cache.

If I renamed this file  .OLD , all cache will be built without any problem. If i renamed it .php after the cache is build, all is OK.

My version : 

Version 1.19.0
Commit 816be6780ca8bd0ab80314e11478c48c70d09383
Date 2017-12-14T09:56:48.842Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
PHP Intellisense 2.2.2
Laravel Project

**Comment by jakewisse** [comment]
I'm experiencing this issue as well. In VSCode, the language server's output hangs when parsing [`Rule.php`][1] from [sabberworm/PHP-CSS-Parser][2].

[1]: https://github.com/sabberworm/PHP-CSS-Parser/blob/master/lib/Sabberworm/CSS/Rule/Rule.php

**Comment by felixfbecker** [comment]
https://github.com/felixfbecker/vscode-php-intellisense/issues/192

**Comment by phil-nelson** [comment]
> when parsing Rule.php

Yeah so this line (109) is the cause:

```foreach ($mValue->getListComponents() as $mValue) {```

The recent foreach handling has a bug where if the foreach collection variable is the same as the value (in this case `$mValue`) then it gets stuck in a loop trying to resolve `$mValue`. PR is up with a potential fix.

**Comment by jakewisse** [comment]
Thanks for the quick turnaround on that fix, @felixfbecker and @phil-nelson! 🙇
