### ISSUE TITLE
Notification handler 'textDocument/publishDiagnostics' failed with message: Illegal argument: line must be positive

### ISSUE THREAD

**Issue by felixfbecker** [felixfbecker/php-language-server#59]
Seems like we publish errors as diagnostics that don't have a line, which is kind of pointless

**Comment by kaloyan-raev** [comment]
The simplest test file I was able to reproduce the error with:

```php
<?php

qwerty

namespace A;
```

**Comment by kaloyan-raev** [comment]
In the above case the PHP Parser returns an error with:
- message: "Namespace declaration statement has to be the very first statement in the script"
- `startLine = 5`
- `endLine = -1`

The Range calculated for the Diagnostic receives a negative endLine, hence VS Code reports an error.

PHP Parser can return `-1` for both `startLine` and `endLine`: https://github.com/nikic/PHP-Parser/blob/a7120116b0931e72004b77bca962f4824f548dd0/lib/PhpParser/Error.php#L36-L52
