### ISSUE TITLE
Install failing when composer decides it must install both ^5.3 AND dev-master

### ISSUE THREAD

**Issue by phil-s** [felixfbecker/php-language-server#594]
$ composer require felixfbecker/language-server
    Using version ^5.3 for felixfbecker/language-server
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - Conclusion: remove felixfbecker/language-server dev-master
        - Can only install one of: felixfbecker/language-server[v5.3.0, dev-master].
        - Can only install one of: felixfbecker/language-server[v5.3.1, dev-master].
        - Can only install one of: felixfbecker/language-server[v5.3.2, dev-master].
        - Can only install one of: felixfbecker/language-server[v5.3.3, dev-master].
        - Can only install one of: felixfbecker/language-server[v5.3.4, dev-master].
        - Can only install one of: felixfbecker/language-server[v5.3.5, dev-master].
        - Installation request for felixfbecker/language-server dev-master -> satisfiable by felixfbecker/language-server[dev-master].
        - Installation request for felixfbecker/language-server ^5.3 -> satisfiable by felixfbecker/language-server[v5.3.0, v5.3.1, v5.3.2, v5.3.3, v5.3.4, v5.3.5].

    Installation failed, reverting ./composer.json to its original content.

I have no idea where the purported `Installation request for felixfbecker/language-server dev-master` is coming from, as it quite clearly says `Using version ^5.3 for felixfbecker/language-server` at the outset.

Without knowing why it thinks it needs it in the first place, composer's recommendation to `remove felixfbecker/language-server dev-master` did not help.

**Comment by felixfbecker** [comment]
This doesn't really sound like a language server issue. If you don't have a suspicion how I could fix this I would like to close this as not actionable.

Here's what I would try:
- delete composer.lock
- change the requirement in composer.json
- delete vendor
- run composer install

**Comment by phil-s** [comment]
> change the requirement in composer.json

Which requirement? What should it be changed to?

**Comment by felixfbecker** [comment]
I'm confused, could you describe what you are trying to do?

**Comment by phil-s** [comment]
I cloned this git repo, and followed the installation instruction by running the command:

    composer require felixfbecker/language-server

And the result was the output I posted initially.

**Comment by felixfbecker** [comment]
Wait, so you you tried to install the language server as a dependency of the language server?

**Comment by phil-s** [comment]
Maybe?  I just followed your instructions?

**Comment by phil-s** [comment]
I have the impression that you're telling me that we're not actually supposed to clone the git repo at all(?!).  Given that the instructions are part of the git repo, that seems bizarre to me, and should certainly be clarified in the instructions if that is the intention.

However, I've tried to test this by running the same command in a new/empty directory, with the following outcome:

    $ composer require felixfbecker/language-server
    Using version ^5.3 for felixfbecker/language-server
    ./composer.json has been created
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
	- felixfbecker/language-server v5.3.6 requires jetbrains/phpstorm-stubs dev-master -> satisfiable by jetbrains/phpstorm-stubs[dev-master] but these conflict with your requirements or minimum-stability.
	- felixfbecker/language-server v5.3.5 requires jetbrains/phpstorm-stubs dev-master -> satisfiable by jetbrains/phpstorm-stubs[dev-master] but these conflict with your requirements or minimum-stability.
	- felixfbecker/language-server v5.3.4 requires jetbrains/phpstorm-stubs dev-master -> satisfiable by jetbrains/phpstorm-stubs[dev-master] but these conflict with your requirements or minimum-stability.
	- felixfbecker/language-server v5.3.3 requires jetbrains/phpstorm-stubs dev-master -> satisfiable by jetbrains/phpstorm-stubs[dev-master] but these conflict with your requirements or minimum-stability.
	- felixfbecker/language-server v5.3.2 requires jetbrains/phpstorm-stubs dev-master -> satisfiable by jetbrains/phpstorm-stubs[dev-master] but these conflict with your requirements or minimum-stability.
	- felixfbecker/language-server v5.3.1 requires jetbrains/phpstorm-stubs dev-master -> satisfiable by jetbrains/phpstorm-stubs[dev-master] but these conflict with your requirements or minimum-stability.
	- felixfbecker/language-server v5.3.0 requires jetbrains/phpstorm-stubs dev-master -> satisfiable by jetbrains/phpstorm-stubs[dev-master] but these conflict with your requirements or minimum-stability.
	- Installation request for felixfbecker/language-server ^5.3 -> satisfiable by felixfbecker/language-server[v5.3.0, v5.3.1, v5.3.2, v5.3.3, v5.3.4, v5.3.5, v5.3.6].

    Installation failed, deleting ./composer.json.

**Comment by felixfbecker** [comment]
It depends on what you are trying to do.
Are you trying to _use_ the language server? Then you don't need to clone the repo, but follow the [installation instructions](https://github.com/felixfbecker/php-language-server#installation).
Are you trying to _contribute_ to the language server? Then you need to follow the [contribution instructions](https://github.com/felixfbecker/php-language-server#contributing) (includes cloning the repo) and _not_ the installation instructions.

**Comment by phil-s** [comment]
I am trying to *use* the language server, so following the [installation instructions](https://github.com/felixfbecker/php-language-server#installation) was what I was attempting to do.

> Then you don't need to clone the repo

*Please* state this in the instructions (both that you don't need to clone the repo, and also that doing so will actually result in errors), because that's not at all intuitive.

However, as the installation instructions have resulted in (different) errors even when I did *not* run the command from the cloned repo/working copy, it seems like those instructions are not quite correct even if a cloned repo is taken out of the equation.

**Comment by phil-s** [comment]
I was going to re-open this issue to make sure it didn't disappear from view in the interim, but I can no longer see the option for doing that... perhaps it's time-limited. If you still have the re-open ability, could you do that?
