### ISSUE TITLE
Using short echo syntax with commas: <?=$a, $b;?>

### ISSUE THREAD

**Issue by bibainet** [felixfbecker/php-language-server#596]
PHP IntelliSense reports error/problem on `<?=$a, $b;?>` constructs (short echo syntax with commas):

```
[php] ';' expected.
[php] Unexpected ','
```

Screenshot:

![vscode_php_echo_comma_bug](https://user-images.githubusercontent.com/9364619/36033264-94f975ca-0dc1-11e8-84aa-c43479ebb4a5.png)

* VSCode: 1.20 and lower.
* PHP IntelliSense: 2.2.7 and lower.
* Windows 7/10.

**Comment by felixfbecker** [comment]
Do you have short tags enabled?

**Comment by bibainet** [comment]
Yes. The 'php.executablePath' (and also 'php.validate.executablePath') option points to a working PHP 7 executable, and there is 'short_open_tag = On' option in 'php.ini' in this directory.
Short echo tags (<?=...?>) are always enabled in PHP 5.4+ regardless of this option.

**Comment by felixfbecker** [comment]
Just to be sure (because this issue has come up quite a few times and there can be multiple php.ini at play), could you run `php -i` and check? Where `php` is the php from `php.executablePath`

**Comment by bibainet** [comment]
The output of `php -i`:
```
PHP Version => 7.2.0
Loaded Configuration File => D:\Work\PHP7\php.ini
Scan this dir for additional .ini files => (none)
Additional .ini files parsed => (none)
...
short_open_tag => On => On
```

**Comment by felixfbecker** [comment]
This issue was moved to Microsoft/tolerant-php-parser#220
