### ISSUE TITLE
No rename (refactor) functionality

### ISSUE THREAD

**Issue by darthrevan13** [felixfbecker/php-language-server#597]
Hello,
I'm using neovim with [autozimu/LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) and i'm trying to use the rename functionality. But when I do I get a:
`Method LanguageServer\Server\TextDocument::rename() does not exist`

Can a rename feature be implemented? It's imperative for me because I refactor my code all the time.

Cheers!

**Comment by felixfbecker** [comment]
Duplicate of https://github.com/felixfbecker/php-language-server/issues/21

**Comment by erlangparasu** [comment]
wating for `rename` feature :) +1
