### ISSUE TITLE
Invalid syntax error with <?=

### ISSUE THREAD

**Issue by joanhey** [felixfbecker/php-language-server#620]
`<?=` is the short tag for `<?php echo`
And it's valid to use ',' for join
`<?= $var, $va2, 'Hello' ?>`
But it's marked like invalid

**Comment by felixfbecker** [comment]
Could you post the output if php -i?

**Comment by TysonAndre** [comment]
This looks to me like a duplicate of https://github.com/felixfbecker/php-language-server/issues/596 (Also `<?=` with commas)

**Comment by joanhey** [comment]
Yes, it's a duplicate.  8P
And short echo tags () are always enabled from PHP 5.4
