### ISSUE TITLE
Syntax error for multiple exception catch with OR ( | )

### ISSUE THREAD

**Issue by Skarlso** [felixfbecker/php-language-server#634]
Hi.

IntelliSense marks this as a syntax error:

```php
            try {
            } catch (AException | BException $e) {
            }
```

**Comment by Skarlso** [comment]
Thanks.

**Comment by Zerquix18** [comment]
Just came here while struggling with that

**Comment by gtfcugb** [comment]
with multi catch ,it is report error incorrectly

**Comment by felixfbecker** [comment]
This is tracked in https://github.com/Microsoft/tolerant-php-parser/issues/103
