### ISSUE TITLE
PHP process running on 100% on Mac

### ISSUE THREAD

**Issue by Jeppeskovsgaard** [felixfbecker/php-language-server#635]
I'm using PHP IntelliSense for VS Code but as of today this extension is causing the "PHP" process to constantly stay at 100% CPU on my MacBook. I have only 1 php file open which is almost empty, as you can see below. I do however have 4 local Wordpress sites in my workspace.

![screen shot 2018-04-18 at 16 45 51](https://user-images.githubusercontent.com/5428441/38939350-086cb1d4-4328-11e8-8c14-df0510ea46a9.png)
_With PHP IntelliSense enabled_

![screen shot 2018-04-18 at 16 45 39](https://user-images.githubusercontent.com/5428441/38939370-11bf122c-4328-11e8-8fda-99fde13914d5.png)
_Everything disabled_

I've tried disabling all extensions but PHP IntelliSense, restarting both VS Code and my computer, as well as reinstalling PHP IntelliSense.

PHP IntelliSense version: 2.3.1
VS Code version: 1.22.2
Local PHP version: 7.1.14
macOS High Sierra version: 10.13.4

**Comment by felixfbecker** [comment]
What does the output panel say?

**Comment by Jeppeskovsgaard** [comment]
It's parsing all the files. With Wordpress that's a lot! It takes 112 seconds for one project. After it's done the cpu usage is normal again.

My bad. 

Is there any way to ignore files like Wordpress core fx.?

**Comment by felixfbecker** [comment]
See https://github.com/felixfbecker/php-language-server/issues/159
