### ISSUE TITLE
more information about installation

### ISSUE THREAD

**Issue by MitaiGit** [felixfbecker/php-language-server#637]
[Error - 13:13:16] Server initialization failed.
  Message: UnexpectedValueException: RecursiveDirectoryIterator::__construct(/var/www/uporovo.site/tmp/smarty): failed to open dir: Permission denied in /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/webmozart/glob/src/Iterator/RecursiveDirectoryIterator.php:43
Stack trace:
#0 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/webmozart/glob/src/Iterator/RecursiveDirectoryIterator.php(43): RecursiveDirectoryIterator->__construct('/var/www/uporov...', 4128)
#1 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/webmozart/glob/src/Iterator/RecursiveDirectoryIterator.php(55): Webmozart\Glob\Iterator\RecursiveDirectoryIterator->__construct('/var/www/uporov...', 4128)
#2 [internal function]: Webmozart\Glob\Iterator\RecursiveDirectoryIterator->getChildren()
#3 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/webmozart/glob/src/Iterator/RegexFilterIterator.php(99): FilterIterator->rewind()
#4 [internal function]: Webmozart\Glob\Iterator\RegexFilterIterator->rewind()
#5 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/felixfbecker/language-server/src/FilesFinder/FileSystemFilesFinder.php(24): IteratorIterator->rewind()
#6 [internal function]: LanguageServer\FilesFinder\FileSystemFilesFinder->LanguageServer\FilesFinder\{closure}()
#7 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/sabre/event/lib/coroutine.php(64): Generator->valid()
#8 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/sabre/event/lib/coroutine.php(118): Sabre\Event\{closure}()
#9 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/felixfbecker/language-server/src/FilesFinder/FileSystemFilesFinder.php(33): Sabre\Event\coroutine(Object(Closure))
#10 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/felixfbecker/language-server/src/LanguageServer.php(204): LanguageServer\FilesFinder\FileSystemFilesFinder->find('/var/www/uporov...')
#11 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#12 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/sabre/event/lib/coroutine.php(88): Generator->send(NULL)
#13 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/sabre/event/lib/coroutine.php(118): Sabre\Event\{closure}()
#14 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/felixfbecker/language-server/src/LanguageServer.php(289): Sabre\Event\coroutine(Object(Closure))
#15 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(164): LanguageServer\LanguageServer->initialize(Object(LanguageServer\Protocol\ClientCapabilities), '/var/www/uporov...', 24789)
#16 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/felixfbecker/language-server/src/LanguageServer.php(131): AdvancedJsonRpc\Dispatcher->dispatch(Object(AdvancedJsonRpc\Request))
#17 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#18 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/sabre/event/lib/coroutine.php(64): Generator->valid()
#19 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/sabre/event/lib/coroutine.php(118): Sabre\Event\{closure}()
#20 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/felixfbecker/language-server/src/LanguageServer.php(154): Sabre\Event\coroutine(Object(Closure))
#21 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/sabre/event/lib/EmitterTrait.php(88): LanguageServer\LanguageServer->LanguageServer\{closure}(Object(LanguageServer\Protocol\Message))
#22 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/felixfbecker/language-server/src/ProtocolStreamReader.php(56): Sabre\Event\Emitter->emit('message', Array)
#23 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/sabre/event/lib/Loop/Loop.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#24 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/sabre/event/lib/Loop/Loop.php(233): Sabre\Event\Loop\Loop->runStreams(NULL)
#25 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#26 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#27 /home/mitai/.vscode/extensions/felixfbecker.php-intellisense-2.3.1/vendor/felixfbecker/language-server/bin/php-language-server.php(55): Sabre\Event\Loop\run()
#28 {main}
  Code: -32603
sorry I'm a noob, just installed this extension, the information file very little detail what to write, where to write, what must be done to rectify the error?

**Comment by felixfbecker** [comment]
You don't have permissions to read the folder in the error message, but presumably opened a parent folder of it.

**Comment by MitaiGit** [comment]
Thanks, problem solved, the issuance of the rights on the folder which was created by the template engine, you are cool :-))
