### ISSUE TITLE
False PHP syntax error when using "<?=" and commas

### ISSUE THREAD

**Issue by BrianLeishman** [felixfbecker/php-language-server#642]
- VSCode Version: 1.23.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

In a PHP file, use shorter echo tags and commas like this:

```php
<?php for ($i = 0; $i < 12; $i++) { ?><option value="<?= $i + 1 ?>"><?= $i + 1, ' ', date('F', strtotime("1996-" . ($i + 1) . "-24")) ?></option>
<?php } ?>
```

![image](https://user-images.githubusercontent.com/1208702/40069961-bda3e686-583a-11e8-95b2-c725cdac88b3.png)

Message says "[php] ';' expected."

These tags are essentially "<?php echo ..." behind the scenes, which you can use commas for, so it should also expect commas to be used with those shorter echo statements (NOT short tags, those are unrelated to this)

**Comment by felixfbecker** [comment]
Do you have short tags enabled in the php.ini for your php CLI?

**Comment by yuloh** [comment]
The fix for this in microsoft/tolerant-php-parser [was merged](https://github.com/Microsoft/tolerant-php-parser/commit/bce97ae2fc06d9259368afdd813fe30e6415b6e5), a `composer update` should fix it.
