### ISSUE TITLE
Extension using too much CPU

### ISSUE THREAD

**Issue by curruwilla** [felixfbecker/php-language-server#643]
This extension, PHP IntelliSense is consuming almost 100% CPU.

What is wrong?

**Comment by curruwilla** [comment]
![image](https://user-images.githubusercontent.com/7454081/40191329-8925f61c-59d7-11e8-9b20-aa949b490bf5.png)

**Comment by felixfbecker** [comment]
There is nothing wrong, it is doing expensive operations. Why should it not use the resources available? And how would it do that?
