### ISSUE TITLE
cpu100

### ISSUE THREAD

**Issue by jjshi** [felixfbecker/php-language-server#644]
Issue Type: <b>Bug</b>

开启PHP IntelliSense扩展之后，通过top命令看到有个进程占用cpu100%

![image](https://user-images.githubusercontent.com/16028668/40339415-fd1f204c-5dac-11e8-86e2-f1eb40c05304.png)

![image](https://user-images.githubusercontent.com/16028668/40339446-17b0ba74-5dad-11e8-9350-8f1e3d464e5b.png)

Extension version: 2.3.1
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T16:03:31.083Z)
OS version: Darwin x64 17.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (7.83GB free)|
|Process Argv|/private/var/folders/px/n53xlzts2f18fr3_cp9422540000gn/T/AppTranslocation/12300724-5DE9-49CB-B105-98A137481BFD/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by felixfbecker** [comment]
Is the language server still indexing? It's expected to use your CPU to do that

**Comment by jjshi** [comment]
how to close this? my pc is so hot.

**Comment by hiqsol** [comment]
I get same problem on big project while small projects are ok.

What information do you want me to provide to help to fix the problem?

**Comment by jjshi** [comment]
Thinks! i want to close this "langurage server" process and The IntelliSense still is used.Because it is so good to use.

**Comment by jjshi** [comment]
5mins later，this process is closed
