### ISSUE TITLE
Support Netbeans/Eclipse/Zend @var annotations

### ISSUE THREAD

**Issue by kAlvaro** [felixfbecker/php-language-server#650]
Netbeans/Eclipse/Zend [@var annotations](https://blogs.oracle.com/netbeansphp/defining-a-variable-type-in-comment-ii) (not to be confused with docblocks<sup>1</sup>) are a mechanism to declare variable types explicitly:

```
/* @var $db Database */
$db->prepare($sql);
```

It's a tool to provide hints for code intelligence and it comes in handy to overcome the limitations of static analysis, either when the engine is not powerful enough or in edge cases when static analysis is just not possible (variables in views defined elsewhere, dynamically generated code, undocumented third-party libraries...). As far as I know it's supported by a number of major IDEs including NetBeans and PhpStorm.

(<sup>1</sup>) Differences:

1. [phpdoc](http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.var.pkg.html) block comments start with `/**` and are placed right before the item _definition_:

        /**
         * @var Database $db Database connection instance
         */
        protected $db;

1.  Variable type inline comments start with `/*` (thus won't show up if you generate actual documentation with phpdoc) and are placed somewhere before the item _use_:

        $foo = $this->db;
        /* @var $foo Database */
        $foo->...

    Also, the arguments are swapped, though PhpStorm accepts any order:

**Comment by felixfbecker** [comment]
Supporting type hints in comments other that do not use `/**` syntax is out of scope as it would mean we cannot rely on phpDoc's parser anymore. It's also not in line with the PHP docblock PSR. I also don't see why you would want to document the reference and not the definition of the variable.

**Comment by kAlvaro** [comment]
I'd be glad to elaborate on the use cases I highlighted but if it isn't really doable because parsing needs to be done with a docblock parser then the feature is probably not worth considering.

**Comment by james2doyle** [comment]
I added support for this in my fork: https://github.com/james2doyle/php-language-server/commit/0c56bffd4c0699751c3688b5a122ef3ada000ea0

**Comment by kAlvaro** [comment]
@james2doyle Is there a way to install your fork and have a look at how it works?

**Comment by james2doyle** [comment]
Yeah it's the same as this one. Just swap out the package names

**Comment by kAlvaro** [comment]
@james2doyle Sorry if I didn't explain myself correctly. Since forks are obviously not available in the usual channels (Visual Studio Marketplace, Packagist...) it isn't always obvious how to use them.

I've figured how to install it right from GitHub:

```
{
    "minimum-stability": "dev",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/james2doyle/php-language-server"
        }
    ],
    "require": {
        "felixfbecker/language-server": "dev-master"
    }
}
```

I'll see if I can plug it into my editor.

**Comment by kAlvaro** [comment]
@james2doyle Got it. I just had to replace `%USERPROFILE%\.vscode\extensions\felixfbecker.php-intellisense-2.3.3\vendor` with yours. It also doesn't seem difficult to build the VSCode extension itself with Node but I haven't tried.

Now, perhaps I'm missing something but I can't make it work. I created a random class somewhere in the project and tried this:

```
<?php

function doStuff()
{
    /* @var $foo FastBender */
    global $foo;
    $bar = new FastBender();
}
```

But Visual Studio Code still seems unaware of what `$foo` is and offers entirely different code intelligence for `$foo` and `$bar`:

![$](https://i.imgur.com/HvunH3q.png)

![$bar->](https://i.imgur.com/YSnjQcS.png)

![$bar->printFrobble(](https://i.imgur.com/MSvyNlk.png)

![$foo->](https://i.imgur.com/utQe4b3.png)

![$bar->printFrobble(](https://i.imgur.com/g5psQia.png)

**Comment by james2doyle** [comment]
It supports docblocks not single line declarations. Try that and see

**Comment by kAlvaro** [comment]
I'm closing this ticket because, after some further research, I reached the conclusion that this annotation format is mostly dead. Tools that implement this kind of feature nowadays use the syntax proposed on the _PSR-5: PHPDoc_ draft:

    /** @var \Database $db */
