### ISSUE TITLE
Is it possible to have the php-language-server work for PHP 5.6?

### ISSUE THREAD

**Issue by jonnycyr** [felixfbecker/php-language-server#651]
I know that you need PHP 7 to run php-language-server - but is it possible to have php-language-server only scan PHP 5.6 stubs? That way, when editing a project written in PHP 5.6 it will give suggestions/etc for functions in the project as well as PHP 5.6 library functions.

**Comment by felixfbecker** [comment]
We use the stubs from JetBrains: https://github.com/JetBrains/phpstorm-stubs
So whatever is in there we give suggestions for.

**Comment by jonnycyr** [comment]
Sounds good! Thanks!
