### ISSUE TITLE
Xdebug loading issue

### ISSUE THREAD

**Issue by jordy-wittouck** [felixfbecker/php-language-server#653]
I have installed the intellisense for vscode and I'm constantly getting errors on xdebug. See screenshot

![screen shot 2018-07-10 at 2 23 56 pm](https://user-images.githubusercontent.com/26605351/42509804-5f902a34-844d-11e8-8684-8a96b0755753.png)

I'm using php 7.1.16 and installed xdebug manually.
Any clue?

**Comment by felixfbecker** [comment]
Does this actually affect any functionality? The logs you are seeing are expected
