### ISSUE TITLE
Goto Definition with external libraries

### ISSUE THREAD

**Issue by hirasso** [felixfbecker/php-language-server#655]
Hi there, great work on this, thank you!!

I would very much like to switch to VSCode, only one thing is stopping me until now. In Sublime Text 3, I use SublimeCodeIntel. They have a setting that lets me tell the package to also look inside folders somewhere else on my machine. I use this to also have `Goto Definition` for WordPress and WP Plugins functions, which are not part of my current working folder (the theme folder). Is there any way to tell `php-language-server` to do that? These are the settings that make it possible in ST3:
```json
{
  "codeintel_language_settings": {
      "PHP": {
          "php": "/Applications/MAMP/bin/php/php5.5.3/bin/php",
          "codeintel_scan_extra_dir": [
            "/Users/.../.../wordpress-core",
            "/Users/.../.../wordpress-plugins",
          ],
          "codeintel_scan_files_in_project": true,
          "codeintel_max_recursive_dir_depth": 15,
          "codeintel_scan_exclude_dir":["/Applications/MAMP/bin/php/php5.5.3/"]
      }
  }
}
```

**Comment by Ciantic** [comment]
I have hacked this to work with WordPress in different folder each time new release comes, right now the instructions that should work are here: https://gist.github.com/Ciantic/07f14ed0247ec3cd92457099cb26e0fe
