### ISSUE TITLE
Language Server Crashes complaining about nesting level.

### ISSUE THREAD

**Issue by valeryan** [felixfbecker/php-language-server#662]
In the developer console I see two errors:

`CRITICAL  Error: Maximum function nesting level of '256' reached, aborting!`

and then

`Error: Channel has been closed`

After which intellisense is completely dead.

**Comment by felixfbecker** [comment]
Sounds like you have XDebug running and configured with a function nesting limit. What are the full logs? It should log something about XDebug as it should disable XDebug automatically, unless you set an environment variable to not do so.

**Comment by valeryan** [comment]
Yeah, I forgot I had vscode pointed to a different instance of php and it had xdebug enabled. Thanks for quick response.
