### ISSUE TITLE
HTML tags shown in hover information

### ISSUE THREAD

**Issue by JohnstonCode** [felixfbecker/php-language-server#674]
When hovering over some PHP functions the tooltip shows HTML tags

![image](https://user-images.githubusercontent.com/10222719/46141449-da8fe800-c24b-11e8-94df-b9aa48a9b336.png)

**Comment by felixfbecker** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/40607

**Comment by JohnstonCode** [comment]
Yeah sorry also found https://github.com/felixfbecker/php-language-server/issues/288
