### ISSUE TITLE
Syntax highlighting with nested backtick `

### ISSUE THREAD

**Issue by aeisenberg** [felixfbecker/php-language-server#677]
Here is a simple situation that produces invalid syntax highlighting in vscode:

```
<?php
$a = 'SELECT`';
$b = 1;
?>
```

The backtick after SELECT is what causes it. This is a problem in large files where there are multiple SQL statements being built up over multiple statements.

Here is a screenshot of the issue:
<img width="237" alt="untitled-1_ _live-betting__workspace_" src="https://user-images.githubusercontent.com/363559/46548281-72f91e80-c883-11e8-87a9-c85889f449ce.png">

Note that this is valid php syntax.

**Comment by felixfbecker** [comment]
The language server does not provide syntax highlighting, this is vscode.
