### ISSUE TITLE
Go to definition - Unable to open file : File not found in vendor

### ISSUE THREAD

**Issue by RyanFarrah** [felixfbecker/php-language-server#678]
OS : Ubuntu 16.04
VSCode : 1.28

I'm in Symfony 3.4 project.

When I try to use the "Go to definition", i'm getting error "Unable to open file : File not found...". The error is encoutered only in vendor directory (only works for very, very few classes).

I reinstalled my VSCode, deleted every other extensions, clear editor history, set Search : Use Ignore Files to false in User Settings and Workspace Settings.

When I open manually a class file, the Go to works for this class.

The Go to definition works with another extension in PHP.
This also works with the integrated Go to definition with node_modules (which are also in a .gitignore).

**Comment by cprn** [comment]
Is this related to #586?

**Comment by felixfbecker** [comment]
Try clearing your cache (XDG cache root or ~/.phpls)

**Comment by RyanFarrah** [comment]
When I reinstalled the extension for follow your steps, the Go to definition worked again.

I don't know what caused the problem, to note that my computer have restarted between the 2 cases (maybe some problematic data were deleted).
