### ISSUE TITLE
Lines with diagnostic problems in PHP files are not marked with Red/Yellow icons	

### ISSUE THREAD

**Issue by Nainabhandari8** [felixfbecker/php-language-server#737]
**Steps:**
1. launch Brackets
2. Create and save a PHP document
3. Type below code and save the file

`<?php

var $abc = 100
echo('`

**Result**: Diagnostic problems are displayed in the panel for line 2 and 3
But red icon is not displayed in line number column for line 2 and 3

**Expected:** 
Diagnostic problems are displayed in the panel for line 2 and 3
Red icon is displayed in line number column for line 2 and 3

**Comment by felixfbecker** [comment]
This sounds like a client issue (i.e. in Brackets)?

**Comment by shubhsnov** [comment]
Yeah sorry about that. The reporter mistakenly reported it here.

**Comment by Nainabhandari8** [comment]
Closing this issue as this is not related to this project.
