### ISSUE TITLE
Go to definition doesn't work for method return type

### ISSUE THREAD

**Issue by mniewrzal** [felixfbecker/php-language-server#75]
Example:
```php
<?php
namespace TestNamespace;

class MyTest
{
    public function abc() : TestClass // it does not work
    {
        new TestClass(); // it works
    }
}
```

**Comment by felixfbecker** [comment]
It should o.o
https://github.com/felixfbecker/php-language-server/blob/master/tests/Server/TextDocument/Definition/NamespacedTest.php#L340

**Comment by mniewrzal** [comment]
Works ok for functions but not for methods. Function_ [from this line](https://github.com/felixfbecker/php-language-server/blob/master/src/PhpDocument.php#L346) should be replaced with FunctionLike.

**Comment by mniewrzal** [comment]
I can prepare PR for that but for now I'm fighting to adjust tests ;) Actual tests structure it a little bit too much change sensitive.

**Comment by mniewrzal** [comment]
I will add new fixture for now but I will also open additional issue to discuss tests structure improvements.
