### ISSUE TITLE
HTML tag is displayed in documentation popup

### ISSUE THREAD

**Issue by thephp1over** [felixfbecker/php-language-server#776]
Hi,

While using your great extension I faced following issue:

![image](https://user-images.githubusercontent.com/59211472/74827664-03be8600-5323-11ea-988b-748cadc0da55.png)

**Steps to reproduce the issue:**
1. Inside a valid .php file with proper opening tag (<?php), Try typing a name of a PHP function like print_r
2. Type opening parentheses '('
3. VS's autocomplete will close the parentheses and display documentation popup which is un-formatted

**The bug does not occur if you try hovering previously typed function name!**

P.S: First I opened issue on https://github.com/microsoft/vscode/issues/89241 but they sent me here!

**Comment by thephp1over** [comment]
@felixfbecker Would you mind take a look at this issue?
Thanks ❤

**Comment by felixfbecker** [comment]
Please see https://github.com/microsoft/vscode/issues/40607
