### ISSUE TITLE
Please add support for PHP 8.0

### ISSUE THREAD

**Issue by buismaarten** [felixfbecker/php-language-server#798]
Sometimes VS Code shows a notification that some ReflectionParameter functionality is deprecated, happening since I upgraded my MacBook to PHP 8.0

```
ErrorException:
Method ReflectionParameter::getClass() is deprecated in /Users/buismaarten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php:241

Stack trace:
#0 /Users/buismaarten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(241): {closure}(8192, 'Method Reflecti...', '/Users/buismaar...', 241)
#1 /Users/buismaarten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(198): phpDocumentor\Reflection\DocBlock\StandardTagFactory->getArgumentsForParametersFromWiring(Array, Array)
#2 /Users/buismaarten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(122): phpDocumentor\Reflection\DocBlock\StandardTagFactory->createTag('ClientCapabilit...', 'param', Object(phpDo...
```

**Comment by yob-yob** [comment]
https://php.watch/versions/8.0/deprecated-reflectionparameter-methods

`ReflectionParamter::getType()` is the recommended way to replace the deprecated methods. This method is available in PHP 7.0 and later.

not that I'm forcing anyone, just wondering if anyone is working on this?

**Comment by buismaarten** [comment]
It seems easy to do, just upgrade the phpdocumentor/reflection-docblock package to v5 which supports PHP 8.0. Hopefully the author would merge a future pull request or fix it himself after not touching the repostiry for nearly 2.5 years.

**Comment by xvoland** [comment]
@buismaarten 
Line 241 needs to be replaced
`$typeHint = $parameter->getClass() ? $parameter->getClass()->getName() : null;`

to

`$typeHint = new ReflectionClass($reflectionParam->getType()->getName()) ? new ReflectionClass($reflectionParam->getType()->getName())->getName() : null;`

**Comment by hetao29** [comment]
change file .vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php line 241 to this code
```php
                //$typeHint = $parameter->getClass() ? $parameter->getClass()->getName() : null;
                try{
                        $type = $parameter->getType();
                        if($type){
                                $name = new \ReflectionClass($parameter->getType()->getName());
                                if($name){
                                        $typeHint = $name->getName();
                                }
                        }
                }catch(Exception $e){
                }
```
