### ISSUE TITLE
Updated document isn't removing not existing FQN

### ISSUE THREAD

**Issue by mniewrzal** [felixfbecker/php-language-server#86]
Simple example:
```php
<?php
namespace Test2;

function fooFunction(){   
}
```
This file after processing (indexing) will add FQN in definitions 'Test2\fooFunction()'. When file will be opened in editor and namespace 'Test2' will be removed then new FQN will be added 'fooFunction()' but first one is not removed. Now we have two elements in definitions array. I'm not sure maybe similar problem is affecting references.

**Comment by felixfbecker** [comment]
Will be same for references. Need to first iterate over document definitions/references, unregister them from the project, then register the new definitions/references.

**Comment by mniewrzal** [comment]
I think also Project should be recreated on every initialization. Now its reused and can accumulate date from previous workspaces.

**Comment by felixfbecker** [comment]
Yes, never though about that.
